module Evergreen.Migrate.V14 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V13.ColorTheme
import Evergreen.V13.ContributorAccount
import Evergreen.V13.ContributorWikiSession
import Evergreen.V13.HostAdmin
import Evergreen.V13.Route
import Evergreen.V13.Store
import Evergreen.V13.Submission
import Evergreen.V13.SubmissionReviewDetail
import Evergreen.V13.Types
import Evergreen.V13.Wiki
import Evergreen.V13.WikiAdminUsers
import Evergreen.V13.WikiAuditLog
import Evergreen.V13.WikiRole
import Evergreen.V14.ColorTheme
import Evergreen.V14.ContributorAccount
import Evergreen.V14.ContributorWikiSession
import Evergreen.V14.HostAdmin
import Evergreen.V14.Route
import Evergreen.V14.Store
import Evergreen.V14.Submission
import Evergreen.V14.SubmissionReviewDetail
import Evergreen.V14.Types
import Evergreen.V14.Wiki
import Evergreen.V14.WikiAdminUsers
import Evergreen.V14.WikiAuditLog
import Evergreen.V14.WikiMarkdownEditorPane
import Evergreen.V14.WikiRole
import Lamdera.Migrations exposing (..)
import List
import Maybe
import RemoteData
import Result


frontendModel : Evergreen.V13.Types.FrontendModel -> ModelMigration Evergreen.V14.Types.FrontendModel Evergreen.V14.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V13.Types.BackendModel -> ModelMigration Evergreen.V14.Types.BackendModel Evergreen.V14.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V13.Types.FrontendMsg -> MsgMigration Evergreen.V14.Types.FrontendMsg Evergreen.V14.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V13.Types.ToBackend -> MsgMigration Evergreen.V14.Types.ToBackend Evergreen.V14.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V13.Types.BackendMsg -> MsgMigration Evergreen.V14.Types.BackendMsg Evergreen.V14.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V13.Types.ToFrontend -> MsgMigration Evergreen.V14.Types.ToFrontend Evergreen.V14.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V13.Types.FrontendModel -> Evergreen.V14.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , colorThemePreference = old.colorThemePreference |> migrate_ColorTheme_ColorThemePreference
    , systemColorTheme = old.systemColorTheme |> migrate_ColorTheme_ColorTheme
    , route = old.route |> migrate_Route_Route
    , navigationFragment = old.navigationFragment
    , store = old.store |> migrate_Store_Store
    , contributorWikiSessions = old.contributorWikiSessions |> Dict.map (\k -> migrate_ContributorWikiSession_ContributorWikiSession)
    , registerDraft = old.registerDraft |> migrate_Types_RegisterDraft
    , loginDraft = old.loginDraft |> migrate_Types_LoginDraft
    , headerSearchQuery = old.headerSearchQuery
    , wikiSearchPageQuery = old.wikiSearchPageQuery
    , newPageSubmitDraft = old.newPageSubmitDraft |> migrate_Types_NewPageSubmitDraft
    , pageEditSubmitDraft = old.pageEditSubmitDraft |> migrate_Types_PageEditSubmitDraft
    , pageDeleteSubmitDraft = old.pageDeleteSubmitDraft |> migrate_Types_PageDeleteSubmitDraft
    , reviewApproveDraft = old.reviewApproveDraft |> migrate_Types_ReviewApproveDraft
    , reviewDecision = old.reviewDecision |> migrate_Types_ReviewDecision
    , reviewRejectDraft = old.reviewRejectDraft |> migrate_Types_ReviewRejectDraft
    , reviewRequestChangesDraft = old.reviewRequestChangesDraft |> migrate_Types_ReviewRequestChangesDraft
    , submissionDetailEditDraft = old.submissionDetailEditDraft |> migrate_Types_SubmissionDetailEditDraft
    , adminPromoteError = old.adminPromoteError
    , adminDemoteError = old.adminDemoteError
    , adminGrantAdminError = old.adminGrantAdminError
    , adminRevokeAdminError = old.adminRevokeAdminError
    , wikiAdminAuditFilterActorDraft = old.wikiAdminAuditFilterActorDraft
    , wikiAdminAuditFilterPageDraft = old.wikiAdminAuditFilterPageDraft
    , wikiAdminAuditFilterSelectedKindTags = old.wikiAdminAuditFilterSelectedKindTags |> List.map migrate_WikiAuditLog_AuditEventKindFilterTag
    , wikiAdminAuditAppliedFilter = old.wikiAdminAuditAppliedFilter |> migrate_WikiAuditLog_AuditLogFilter
    , hostAdminAuditFilterWikiDraft = old.hostAdminAuditFilterWikiDraft
    , hostAdminAuditFilterActorDraft = old.hostAdminAuditFilterActorDraft
    , hostAdminAuditFilterPageDraft = old.hostAdminAuditFilterPageDraft
    , hostAdminAuditFilterSelectedKindTags = old.hostAdminAuditFilterSelectedKindTags |> List.map migrate_WikiAuditLog_AuditEventKindFilterTag
    , hostAdminAuditAppliedFilter = old.hostAdminAuditAppliedFilter |> migrate_WikiAuditLog_HostAuditLogFilter
    , hostAdminAuditLog = old.hostAdminAuditLog |> migrate_RemoteData_RemoteData identity (Result.mapError migrate_HostAdmin_ProtectedError >> Result.map (List.map migrate_WikiAuditLog_ScopedAuditEvent))
    , hostAdminLoginDraft = old.hostAdminLoginDraft |> migrate_Types_HostAdminLoginDraft
    , hostAdminCreateWikiDraft = old.hostAdminCreateWikiDraft |> migrate_Types_HostAdminCreateWikiDraft
    , hostAdminWikiDetailDraft = old.hostAdminWikiDetailDraft |> migrate_Types_HostAdminWikiDetailDraft
    , hostAdminWikis = old.hostAdminWikis |> migrate_RemoteData_RemoteData identity (Result.mapError migrate_HostAdmin_ProtectedError)
    , hostAdminSessionAuthenticated = old.hostAdminSessionAuthenticated
    , hostAdminExportInFlight = old.hostAdminExportInFlight
    , hostAdminImportInFlight = old.hostAdminImportInFlight
    , hostAdminBackupNotice = old.hostAdminBackupNotice
    , hostAdminWikiExportInFlightSlug = old.hostAdminWikiExportInFlightSlug
    , hostAdminWikiImportInFlightSlug = old.hostAdminWikiImportInFlightSlug
    , hostAdminWikiImportPendingSlug = old.hostAdminWikiImportPendingSlug
    , hostAdminWikisNotice = old.hostAdminWikisNotice
    , sideNavOpen = False
    , wikiMarkdownEditorPane = Evergreen.V14.WikiMarkdownEditorPane.EditorWrite
    }


migrate_ColorTheme_ColorTheme : Evergreen.V13.ColorTheme.ColorTheme -> Evergreen.V14.ColorTheme.ColorTheme
migrate_ColorTheme_ColorTheme old =
    case old of
        Evergreen.V13.ColorTheme.Light ->
            Evergreen.V14.ColorTheme.Light

        Evergreen.V13.ColorTheme.Dark ->
            Evergreen.V14.ColorTheme.Dark


migrate_ColorTheme_ColorThemePreference : Evergreen.V13.ColorTheme.ColorThemePreference -> Evergreen.V14.ColorTheme.ColorThemePreference
migrate_ColorTheme_ColorThemePreference old =
    case old of
        Evergreen.V13.ColorTheme.FollowSystem ->
            Evergreen.V14.ColorTheme.FollowSystem

        Evergreen.V13.ColorTheme.Fixed p0 ->
            Evergreen.V14.ColorTheme.Fixed (p0 |> migrate_ColorTheme_ColorTheme)


migrate_ColorTheme_Incoming : Evergreen.V13.ColorTheme.Incoming -> Evergreen.V14.ColorTheme.Incoming
migrate_ColorTheme_Incoming old =
    case old of
        Evergreen.V13.ColorTheme.Sync p0 p1 ->
            Evergreen.V14.ColorTheme.Sync (p0 |> migrate_ColorTheme_ColorThemePreference)
                (p1 |> migrate_ColorTheme_ColorTheme)

        Evergreen.V13.ColorTheme.System p0 ->
            Evergreen.V14.ColorTheme.System (p0 |> migrate_ColorTheme_ColorTheme)


migrate_ContributorAccount_LoginContributorError : Evergreen.V13.ContributorAccount.LoginContributorError -> Evergreen.V14.ContributorAccount.LoginContributorError
migrate_ContributorAccount_LoginContributorError old =
    case old of
        Evergreen.V13.ContributorAccount.LoginWikiNotFound ->
            Evergreen.V14.ContributorAccount.LoginWikiNotFound

        Evergreen.V13.ContributorAccount.LoginWikiInactive ->
            Evergreen.V14.ContributorAccount.LoginWikiInactive

        Evergreen.V13.ContributorAccount.LoginInvalidCredentials ->
            Evergreen.V14.ContributorAccount.LoginInvalidCredentials

        Evergreen.V13.ContributorAccount.LoginUsernameEmpty ->
            Evergreen.V14.ContributorAccount.LoginUsernameEmpty

        Evergreen.V13.ContributorAccount.LoginPasswordEmpty ->
            Evergreen.V14.ContributorAccount.LoginPasswordEmpty


migrate_ContributorAccount_RegisterContributorError : Evergreen.V13.ContributorAccount.RegisterContributorError -> Evergreen.V14.ContributorAccount.RegisterContributorError
migrate_ContributorAccount_RegisterContributorError old =
    case old of
        Evergreen.V13.ContributorAccount.RegisterWikiNotFound ->
            Evergreen.V14.ContributorAccount.RegisterWikiNotFound

        Evergreen.V13.ContributorAccount.RegisterWikiInactive ->
            Evergreen.V14.ContributorAccount.RegisterWikiInactive

        Evergreen.V13.ContributorAccount.RegisterUsernameTaken ->
            Evergreen.V14.ContributorAccount.RegisterUsernameTaken

        Evergreen.V13.ContributorAccount.RegisterUsernameEmpty ->
            Evergreen.V14.ContributorAccount.RegisterUsernameEmpty

        Evergreen.V13.ContributorAccount.RegisterUsernameTooShort ->
            Evergreen.V14.ContributorAccount.RegisterUsernameTooShort

        Evergreen.V13.ContributorAccount.RegisterUsernameTooLong ->
            Evergreen.V14.ContributorAccount.RegisterUsernameTooLong

        Evergreen.V13.ContributorAccount.RegisterUsernameInvalidChars ->
            Evergreen.V14.ContributorAccount.RegisterUsernameInvalidChars

        Evergreen.V13.ContributorAccount.RegisterPasswordEmpty ->
            Evergreen.V14.ContributorAccount.RegisterPasswordEmpty


migrate_ContributorWikiSession_ContributorWikiSession : Evergreen.V13.ContributorWikiSession.ContributorWikiSession -> Evergreen.V14.ContributorWikiSession.ContributorWikiSession
migrate_ContributorWikiSession_ContributorWikiSession old =
    { role = old.role |> migrate_WikiRole_WikiRole
    , displayUsername = old.displayUsername
    }


migrate_HostAdmin_CreateHostedWikiError : Evergreen.V13.HostAdmin.CreateHostedWikiError -> Evergreen.V14.HostAdmin.CreateHostedWikiError
migrate_HostAdmin_CreateHostedWikiError old =
    case old of
        Evergreen.V13.HostAdmin.CreateNotHostAuthenticated ->
            Evergreen.V14.HostAdmin.CreateNotHostAuthenticated

        Evergreen.V13.HostAdmin.CreateSlugInvalid p0 ->
            Evergreen.V14.HostAdmin.CreateSlugInvalid (p0 |> migrate_Submission_ValidationError)

        Evergreen.V13.HostAdmin.CreateWikiNameInvalid p0 ->
            Evergreen.V14.HostAdmin.CreateWikiNameInvalid (p0 |> migrate_HostAdmin_WikiNameError)

        Evergreen.V13.HostAdmin.CreateWikiSlugTaken ->
            Evergreen.V14.HostAdmin.CreateWikiSlugTaken

        Evergreen.V13.HostAdmin.CreateInitialAdminInvalid p0 ->
            Evergreen.V14.HostAdmin.CreateInitialAdminInvalid (p0 |> migrate_ContributorAccount_RegisterContributorError)


migrate_HostAdmin_DeleteHostedWikiError : Evergreen.V13.HostAdmin.DeleteHostedWikiError -> Evergreen.V14.HostAdmin.DeleteHostedWikiError
migrate_HostAdmin_DeleteHostedWikiError old =
    case old of
        Evergreen.V13.HostAdmin.DeleteHostedWikiNotHostAuthenticated ->
            Evergreen.V14.HostAdmin.DeleteHostedWikiNotHostAuthenticated

        Evergreen.V13.HostAdmin.DeleteHostedWikiWikiNotFound ->
            Evergreen.V14.HostAdmin.DeleteHostedWikiWikiNotFound

        Evergreen.V13.HostAdmin.DeleteHostedWikiConfirmationMismatch ->
            Evergreen.V14.HostAdmin.DeleteHostedWikiConfirmationMismatch


migrate_HostAdmin_HostWikiDetailError : Evergreen.V13.HostAdmin.HostWikiDetailError -> Evergreen.V14.HostAdmin.HostWikiDetailError
migrate_HostAdmin_HostWikiDetailError old =
    case old of
        Evergreen.V13.HostAdmin.HostWikiDetailNotHostAuthenticated ->
            Evergreen.V14.HostAdmin.HostWikiDetailNotHostAuthenticated

        Evergreen.V13.HostAdmin.HostWikiDetailWikiNotFound ->
            Evergreen.V14.HostAdmin.HostWikiDetailWikiNotFound


migrate_HostAdmin_LoginError : Evergreen.V13.HostAdmin.LoginError -> Evergreen.V14.HostAdmin.LoginError
migrate_HostAdmin_LoginError old =
    case old of
        Evergreen.V13.HostAdmin.WrongPassword ->
            Evergreen.V14.HostAdmin.WrongPassword


migrate_HostAdmin_ProtectedError : Evergreen.V13.HostAdmin.ProtectedError -> Evergreen.V14.HostAdmin.ProtectedError
migrate_HostAdmin_ProtectedError old =
    case old of
        Evergreen.V13.HostAdmin.NotHostAuthenticated ->
            Evergreen.V14.HostAdmin.NotHostAuthenticated


migrate_HostAdmin_UpdateHostedWikiMetadataError : Evergreen.V13.HostAdmin.UpdateHostedWikiMetadataError -> Evergreen.V14.HostAdmin.UpdateHostedWikiMetadataError
migrate_HostAdmin_UpdateHostedWikiMetadataError old =
    case old of
        Evergreen.V13.HostAdmin.UpdateMetadataNotHostAuthenticated ->
            Evergreen.V14.HostAdmin.UpdateMetadataNotHostAuthenticated

        Evergreen.V13.HostAdmin.UpdateMetadataWikiNotFound ->
            Evergreen.V14.HostAdmin.UpdateMetadataWikiNotFound

        Evergreen.V13.HostAdmin.UpdateMetadataWikiNameInvalid p0 ->
            Evergreen.V14.HostAdmin.UpdateMetadataWikiNameInvalid (p0 |> migrate_HostAdmin_WikiNameError)

        Evergreen.V13.HostAdmin.UpdateMetadataWikiSummaryInvalid p0 ->
            Evergreen.V14.HostAdmin.UpdateMetadataWikiSummaryInvalid (p0 |> migrate_HostAdmin_WikiSummaryError)

        Evergreen.V13.HostAdmin.UpdateMetadataWikiSlugInvalid p0 ->
            Evergreen.V14.HostAdmin.UpdateMetadataWikiSlugInvalid (p0 |> migrate_Submission_ValidationError)

        Evergreen.V13.HostAdmin.UpdateMetadataWikiSlugTaken ->
            Evergreen.V14.HostAdmin.UpdateMetadataWikiSlugTaken


migrate_HostAdmin_WikiLifecycleError : Evergreen.V13.HostAdmin.WikiLifecycleError -> Evergreen.V14.HostAdmin.WikiLifecycleError
migrate_HostAdmin_WikiLifecycleError old =
    case old of
        Evergreen.V13.HostAdmin.WikiLifecycleNotHostAuthenticated ->
            Evergreen.V14.HostAdmin.WikiLifecycleNotHostAuthenticated

        Evergreen.V13.HostAdmin.WikiLifecycleWikiNotFound ->
            Evergreen.V14.HostAdmin.WikiLifecycleWikiNotFound


migrate_HostAdmin_WikiNameError : Evergreen.V13.HostAdmin.WikiNameError -> Evergreen.V14.HostAdmin.WikiNameError
migrate_HostAdmin_WikiNameError old =
    case old of
        Evergreen.V13.HostAdmin.WikiNameEmpty ->
            Evergreen.V14.HostAdmin.WikiNameEmpty

        Evergreen.V13.HostAdmin.WikiNameTooLong ->
            Evergreen.V14.HostAdmin.WikiNameTooLong


migrate_HostAdmin_WikiSummaryError : Evergreen.V13.HostAdmin.WikiSummaryError -> Evergreen.V14.HostAdmin.WikiSummaryError
migrate_HostAdmin_WikiSummaryError old =
    case old of
        Evergreen.V13.HostAdmin.WikiSummaryTooLong ->
            Evergreen.V14.HostAdmin.WikiSummaryTooLong


migrate_RemoteData_RemoteData : (e_old -> e_new) -> (a_old -> a_new) -> RemoteData.RemoteData e_old a_old -> RemoteData.RemoteData e_new a_new
migrate_RemoteData_RemoteData migrate_e migrate_a old =
    case old of
        RemoteData.NotAsked ->
            RemoteData.NotAsked

        RemoteData.Loading ->
            RemoteData.Loading

        RemoteData.Failure p0 ->
            RemoteData.Failure (p0 |> migrate_e)

        RemoteData.Success p0 ->
            RemoteData.Success (p0 |> migrate_a)


migrate_Route_Route : Evergreen.V13.Route.Route -> Evergreen.V14.Route.Route
migrate_Route_Route old =
    case old of
        Evergreen.V13.Route.WikiList ->
            Evergreen.V14.Route.WikiList

        Evergreen.V13.Route.HostAdmin p0 ->
            Evergreen.V14.Route.HostAdmin p0

        Evergreen.V13.Route.HostAdminWikis ->
            Evergreen.V14.Route.HostAdminWikis

        Evergreen.V13.Route.HostAdminWikiNew ->
            Evergreen.V14.Route.HostAdminWikiNew

        Evergreen.V13.Route.HostAdminWikiDetail p0 ->
            Evergreen.V14.Route.HostAdminWikiDetail p0

        Evergreen.V13.Route.HostAdminAudit ->
            Evergreen.V14.Route.HostAdminAudit

        Evergreen.V13.Route.HostAdminAuditDiff p0 p1 ->
            Evergreen.V14.Route.HostAdminAuditDiff p0 p1

        Evergreen.V13.Route.HostAdminBackup ->
            Evergreen.V14.Route.HostAdminBackup

        Evergreen.V13.Route.WikiHome p0 ->
            Evergreen.V14.Route.WikiHome p0

        Evergreen.V13.Route.WikiTodos p0 ->
            Evergreen.V14.Route.WikiTodos p0

        Evergreen.V13.Route.WikiGraph p0 ->
            Evergreen.V14.Route.WikiGraph p0

        Evergreen.V13.Route.WikiSearch p0 ->
            Evergreen.V14.Route.WikiSearch p0

        Evergreen.V13.Route.WikiPage p0 p1 ->
            Evergreen.V14.Route.WikiPage p0 p1

        Evergreen.V13.Route.WikiPageGraph p0 p1 ->
            Evergreen.V14.Route.WikiPageGraph p0 p1

        Evergreen.V13.Route.WikiLogin p0 p1 ->
            Evergreen.V14.Route.WikiLogin p0 p1

        Evergreen.V13.Route.WikiRegister p0 ->
            Evergreen.V14.Route.WikiRegister p0

        Evergreen.V13.Route.WikiSubmitNew p0 ->
            Evergreen.V14.Route.WikiSubmitNew p0

        Evergreen.V13.Route.WikiSubmitEdit p0 p1 ->
            Evergreen.V14.Route.WikiSubmitEdit p0 p1

        Evergreen.V13.Route.WikiSubmitDelete p0 p1 ->
            Evergreen.V14.Route.WikiSubmitDelete p0 p1

        Evergreen.V13.Route.WikiSubmissionDetail p0 p1 ->
            Evergreen.V14.Route.WikiSubmissionDetail p0 p1

        Evergreen.V13.Route.WikiMySubmissions p0 ->
            Evergreen.V14.Route.WikiMySubmissions p0

        Evergreen.V13.Route.WikiReview p0 ->
            Evergreen.V14.Route.WikiReview p0

        Evergreen.V13.Route.WikiReviewDetail p0 p1 ->
            Evergreen.V14.Route.WikiReviewDetail p0 p1

        Evergreen.V13.Route.WikiAdminUsers p0 ->
            Evergreen.V14.Route.WikiAdminUsers p0

        Evergreen.V13.Route.WikiAdminAudit p0 ->
            Evergreen.V14.Route.WikiAdminAudit p0

        Evergreen.V13.Route.WikiAdminAuditDiff p0 p1 ->
            Evergreen.V14.Route.WikiAdminAuditDiff p0 p1

        Evergreen.V13.Route.NotFound p0 ->
            Evergreen.V14.Route.NotFound p0


migrate_Store_Store : Evergreen.V13.Store.Store -> Evergreen.V14.Store.Store
migrate_Store_Store old =
    { wikiCatalog = old.wikiCatalog
    , wikiDetails = old.wikiDetails |> Dict.map (\k -> migrate_RemoteData_RemoteData identity migrate_Wiki_FrontendDetails)
    , publishedPages = old.publishedPages
    , reviewQueues = old.reviewQueues |> Dict.map (\k -> migrate_RemoteData_RemoteData identity (Result.mapError migrate_Submission_ReviewQueueError >> Result.map (List.map migrate_Submission_ReviewQueueItem)))
    , myPendingSubmissions = old.myPendingSubmissions |> Dict.map (\k -> migrate_RemoteData_RemoteData identity (Result.mapError migrate_Submission_MyPendingSubmissionsError >> Result.map (List.map migrate_Submission_MyPendingSubmissionListItem)))
    , submissionDetails = old.submissionDetails |> Dict.map (\k -> migrate_RemoteData_RemoteData identity (Result.mapError migrate_Submission_DetailsError >> Result.map migrate_Submission_ContributorView))
    , reviewSubmissionDetails = old.reviewSubmissionDetails |> Dict.map (\k -> migrate_RemoteData_RemoteData identity (Result.mapError migrate_SubmissionReviewDetail_ReviewSubmissionDetailError >> Result.map migrate_SubmissionReviewDetail_SubmissionReviewDetail))
    , wikiUsers = old.wikiUsers |> Dict.map (\k -> migrate_RemoteData_RemoteData identity (Result.mapError migrate_WikiAdminUsers_Error >> Result.map (List.map migrate_WikiAdminUsers_ListedUser)))
    , wikiAuditLogs = old.wikiAuditLogs |> Dict.map (\_ -> Dict.map (\k -> migrate_RemoteData_RemoteData identity (Result.mapError migrate_WikiAuditLog_Error >> Result.map (List.map migrate_WikiAuditLog_AuditEvent))))
    }


migrate_SubmissionReviewDetail_ReviewSubmissionDetailError : Evergreen.V13.SubmissionReviewDetail.ReviewSubmissionDetailError -> Evergreen.V14.SubmissionReviewDetail.ReviewSubmissionDetailError
migrate_SubmissionReviewDetail_ReviewSubmissionDetailError old =
    case old of
        Evergreen.V13.SubmissionReviewDetail.ReviewSubmissionDetailNotLoggedIn ->
            Evergreen.V14.SubmissionReviewDetail.ReviewSubmissionDetailNotLoggedIn

        Evergreen.V13.SubmissionReviewDetail.ReviewSubmissionDetailWrongWikiSession ->
            Evergreen.V14.SubmissionReviewDetail.ReviewSubmissionDetailWrongWikiSession

        Evergreen.V13.SubmissionReviewDetail.ReviewSubmissionDetailForbidden ->
            Evergreen.V14.SubmissionReviewDetail.ReviewSubmissionDetailForbidden

        Evergreen.V13.SubmissionReviewDetail.ReviewSubmissionDetailWikiInactive ->
            Evergreen.V14.SubmissionReviewDetail.ReviewSubmissionDetailWikiInactive

        Evergreen.V13.SubmissionReviewDetail.ReviewSubmissionDetailNotFound ->
            Evergreen.V14.SubmissionReviewDetail.ReviewSubmissionDetailNotFound


migrate_SubmissionReviewDetail_SubmissionReviewDetail : Evergreen.V13.SubmissionReviewDetail.SubmissionReviewDetail -> Evergreen.V14.SubmissionReviewDetail.SubmissionReviewDetail
migrate_SubmissionReviewDetail_SubmissionReviewDetail old =
    case old of
        Evergreen.V13.SubmissionReviewDetail.NewPageDiff p0 ->
            Evergreen.V14.SubmissionReviewDetail.NewPageDiff p0

        Evergreen.V13.SubmissionReviewDetail.EditPageDiff p0 ->
            Evergreen.V14.SubmissionReviewDetail.EditPageDiff p0

        Evergreen.V13.SubmissionReviewDetail.DeletePageDiff p0 ->
            Evergreen.V14.SubmissionReviewDetail.DeletePageDiff p0


migrate_Submission_ApproveSubmissionError : Evergreen.V13.Submission.ApproveSubmissionError -> Evergreen.V14.Submission.ApproveSubmissionError
migrate_Submission_ApproveSubmissionError old =
    case old of
        Evergreen.V13.Submission.ApproveNotLoggedIn ->
            Evergreen.V14.Submission.ApproveNotLoggedIn

        Evergreen.V13.Submission.ApproveWrongWikiSession ->
            Evergreen.V14.Submission.ApproveWrongWikiSession

        Evergreen.V13.Submission.ApproveForbidden ->
            Evergreen.V14.Submission.ApproveForbidden

        Evergreen.V13.Submission.ApproveWikiNotFound ->
            Evergreen.V14.Submission.ApproveWikiNotFound

        Evergreen.V13.Submission.ApproveWikiInactive ->
            Evergreen.V14.Submission.ApproveWikiInactive

        Evergreen.V13.Submission.ApproveSubmissionNotFound ->
            Evergreen.V14.Submission.ApproveSubmissionNotFound

        Evergreen.V13.Submission.ApproveNotPending ->
            Evergreen.V14.Submission.ApproveNotPending

        Evergreen.V13.Submission.ApproveNewPageSlugTaken ->
            Evergreen.V14.Submission.ApproveNewPageSlugTaken

        Evergreen.V13.Submission.ApproveEditTargetNotPublished ->
            Evergreen.V14.Submission.ApproveEditTargetNotPublished

        Evergreen.V13.Submission.ApproveDeleteTargetNotPublished ->
            Evergreen.V14.Submission.ApproveDeleteTargetNotPublished


migrate_Submission_ContributorSubmissionKind : Evergreen.V13.Submission.ContributorSubmissionKind -> Evergreen.V14.Submission.ContributorSubmissionKind
migrate_Submission_ContributorSubmissionKind old =
    case old of
        Evergreen.V13.Submission.ContributorKindNewPage ->
            Evergreen.V14.Submission.ContributorKindNewPage

        Evergreen.V13.Submission.ContributorKindEditPage ->
            Evergreen.V14.Submission.ContributorKindEditPage

        Evergreen.V13.Submission.ContributorKindDeletePage ->
            Evergreen.V14.Submission.ContributorKindDeletePage


migrate_Submission_ContributorView : Evergreen.V13.Submission.ContributorView -> Evergreen.V14.Submission.ContributorView
migrate_Submission_ContributorView old =
    { id = old.id |> migrate_Submission_Id
    , status = old.status |> migrate_Submission_Status
    , kindSummary = old.kindSummary
    , contributionKind = old.contributionKind |> migrate_Submission_ContributorSubmissionKind
    , reviewerNote = old.reviewerNote
    , conflictContext = old.conflictContext
    , compareOriginalMarkdown = old.compareOriginalMarkdown
    , compareNewMarkdown = old.compareNewMarkdown
    , maybeNewPageSlug = old.maybeNewPageSlug
    , maybeEditPageSlug = old.maybeEditPageSlug
    }


migrate_Submission_DeletePublishedPageImmediatelyError : Evergreen.V13.Submission.DeletePublishedPageImmediatelyError -> Evergreen.V14.Submission.DeletePublishedPageImmediatelyError
migrate_Submission_DeletePublishedPageImmediatelyError old =
    case old of
        Evergreen.V13.Submission.DeletePublishedPageImmediatelyPrecondition p0 ->
            Evergreen.V14.Submission.DeletePublishedPageImmediatelyPrecondition (p0 |> migrate_Submission_PageDeletionPreconditionError)

        Evergreen.V13.Submission.DeletePublishedPageImmediatelyForbiddenUntrustedContributor ->
            Evergreen.V14.Submission.DeletePublishedPageImmediatelyForbiddenUntrustedContributor


migrate_Submission_DeleteReasonError : Evergreen.V13.Submission.DeleteReasonError -> Evergreen.V14.Submission.DeleteReasonError
migrate_Submission_DeleteReasonError old =
    case old of
        Evergreen.V13.Submission.ReasonRequired ->
            Evergreen.V14.Submission.ReasonRequired

        Evergreen.V13.Submission.ReasonTooLong ->
            Evergreen.V14.Submission.ReasonTooLong


migrate_Submission_DetailsError : Evergreen.V13.Submission.DetailsError -> Evergreen.V14.Submission.DetailsError
migrate_Submission_DetailsError old =
    case old of
        Evergreen.V13.Submission.DetailsNotLoggedIn ->
            Evergreen.V14.Submission.DetailsNotLoggedIn

        Evergreen.V13.Submission.DetailsWrongWikiSession ->
            Evergreen.V14.Submission.DetailsWrongWikiSession

        Evergreen.V13.Submission.DetailsWikiInactive ->
            Evergreen.V14.Submission.DetailsWikiInactive

        Evergreen.V13.Submission.DetailsNotFound ->
            Evergreen.V14.Submission.DetailsNotFound

        Evergreen.V13.Submission.DetailsForbidden ->
            Evergreen.V14.Submission.DetailsForbidden


migrate_Submission_EditSubmitSuccess : Evergreen.V13.Submission.EditSubmitSuccess -> Evergreen.V14.Submission.EditSubmitSuccess
migrate_Submission_EditSubmitSuccess old =
    case old of
        Evergreen.V13.Submission.EditPublishedImmediately ->
            Evergreen.V14.Submission.EditPublishedImmediately

        Evergreen.V13.Submission.EditSubmittedForReview p0 ->
            Evergreen.V14.Submission.EditSubmittedForReview (p0 |> migrate_Submission_Id)


migrate_Submission_Id : Evergreen.V13.Submission.Id -> Evergreen.V14.Submission.Id
migrate_Submission_Id old =
    case old of
        Evergreen.V13.Submission.Id p0 ->
            Evergreen.V14.Submission.Id p0


migrate_Submission_MyPendingSubmissionListItem : Evergreen.V13.Submission.MyPendingSubmissionListItem -> Evergreen.V14.Submission.MyPendingSubmissionListItem
migrate_Submission_MyPendingSubmissionListItem old =
    { id = old.id |> migrate_Submission_Id
    , status = old.status |> migrate_Submission_Status
    , statusLabel = old.statusLabel
    , kindLabel = old.kindLabel
    , maybePageSlug = old.maybePageSlug
    }


migrate_Submission_MyPendingSubmissionsError : Evergreen.V13.Submission.MyPendingSubmissionsError -> Evergreen.V14.Submission.MyPendingSubmissionsError
migrate_Submission_MyPendingSubmissionsError old =
    case old of
        Evergreen.V13.Submission.MyPendingSubmissionsNotLoggedIn ->
            Evergreen.V14.Submission.MyPendingSubmissionsNotLoggedIn

        Evergreen.V13.Submission.MyPendingSubmissionsWrongWikiSession ->
            Evergreen.V14.Submission.MyPendingSubmissionsWrongWikiSession

        Evergreen.V13.Submission.MyPendingSubmissionsWikiInactive ->
            Evergreen.V14.Submission.MyPendingSubmissionsWikiInactive

        Evergreen.V13.Submission.MyPendingSubmissionsForbiddenTrustedModerator ->
            Evergreen.V14.Submission.MyPendingSubmissionsForbiddenTrustedModerator


migrate_Submission_NewPageSubmitSuccess : Evergreen.V13.Submission.NewPageSubmitSuccess -> Evergreen.V14.Submission.NewPageSubmitSuccess
migrate_Submission_NewPageSubmitSuccess old =
    case old of
        Evergreen.V13.Submission.NewPagePublishedImmediately ->
            Evergreen.V14.Submission.NewPagePublishedImmediately

        Evergreen.V13.Submission.NewPageSubmittedForReview p0 ->
            Evergreen.V14.Submission.NewPageSubmittedForReview (p0 |> migrate_Submission_Id)


migrate_Submission_PageDeleteFormError : Evergreen.V13.Submission.PageDeleteFormError -> Evergreen.V14.Submission.PageDeleteFormError
migrate_Submission_PageDeleteFormError old =
    case old of
        Evergreen.V13.Submission.PageDeleteRequestFailed p0 ->
            Evergreen.V14.Submission.PageDeleteRequestFailed (p0 |> migrate_Submission_RequestPublishedPageDeletionError)

        Evergreen.V13.Submission.PageDeleteImmediateFailed p0 ->
            Evergreen.V14.Submission.PageDeleteImmediateFailed (p0 |> migrate_Submission_DeletePublishedPageImmediatelyError)


migrate_Submission_PageDeleteFormSuccess : Evergreen.V13.Submission.PageDeleteFormSuccess -> Evergreen.V14.Submission.PageDeleteFormSuccess
migrate_Submission_PageDeleteFormSuccess old =
    case old of
        Evergreen.V13.Submission.DeletePublishedImmediately ->
            Evergreen.V14.Submission.DeletePublishedImmediately

        Evergreen.V13.Submission.DeleteSubmittedForReview p0 ->
            Evergreen.V14.Submission.DeleteSubmittedForReview (p0 |> migrate_Submission_Id)


migrate_Submission_PageDeletionPreconditionError : Evergreen.V13.Submission.PageDeletionPreconditionError -> Evergreen.V14.Submission.PageDeletionPreconditionError
migrate_Submission_PageDeletionPreconditionError old =
    case old of
        Evergreen.V13.Submission.PageDeletionNotLoggedIn ->
            Evergreen.V14.Submission.PageDeletionNotLoggedIn

        Evergreen.V13.Submission.PageDeletionWrongWikiSession ->
            Evergreen.V14.Submission.PageDeletionWrongWikiSession

        Evergreen.V13.Submission.PageDeletionWikiNotFound ->
            Evergreen.V14.Submission.PageDeletionWikiNotFound

        Evergreen.V13.Submission.PageDeletionWikiInactive ->
            Evergreen.V14.Submission.PageDeletionWikiInactive

        Evergreen.V13.Submission.PageDeletionValidation p0 ->
            Evergreen.V14.Submission.PageDeletionValidation (p0 |> migrate_Submission_DeleteReasonError)

        Evergreen.V13.Submission.PageDeletionTargetNotPublished ->
            Evergreen.V14.Submission.PageDeletionTargetNotPublished


migrate_Submission_RejectReasonError : Evergreen.V13.Submission.RejectReasonError -> Evergreen.V14.Submission.RejectReasonError
migrate_Submission_RejectReasonError old =
    case old of
        Evergreen.V13.Submission.RejectReasonEmpty ->
            Evergreen.V14.Submission.RejectReasonEmpty

        Evergreen.V13.Submission.RejectReasonTooLong ->
            Evergreen.V14.Submission.RejectReasonTooLong


migrate_Submission_RejectSubmissionError : Evergreen.V13.Submission.RejectSubmissionError -> Evergreen.V14.Submission.RejectSubmissionError
migrate_Submission_RejectSubmissionError old =
    case old of
        Evergreen.V13.Submission.RejectNotLoggedIn ->
            Evergreen.V14.Submission.RejectNotLoggedIn

        Evergreen.V13.Submission.RejectWrongWikiSession ->
            Evergreen.V14.Submission.RejectWrongWikiSession

        Evergreen.V13.Submission.RejectForbidden ->
            Evergreen.V14.Submission.RejectForbidden

        Evergreen.V13.Submission.RejectWikiNotFound ->
            Evergreen.V14.Submission.RejectWikiNotFound

        Evergreen.V13.Submission.RejectWikiInactive ->
            Evergreen.V14.Submission.RejectWikiInactive

        Evergreen.V13.Submission.RejectSubmissionNotFound ->
            Evergreen.V14.Submission.RejectSubmissionNotFound

        Evergreen.V13.Submission.RejectNotPending ->
            Evergreen.V14.Submission.RejectNotPending

        Evergreen.V13.Submission.RejectReasonInvalid p0 ->
            Evergreen.V14.Submission.RejectReasonInvalid (p0 |> migrate_Submission_RejectReasonError)


migrate_Submission_RequestChangesSubmissionError : Evergreen.V13.Submission.RequestChangesSubmissionError -> Evergreen.V14.Submission.RequestChangesSubmissionError
migrate_Submission_RequestChangesSubmissionError old =
    case old of
        Evergreen.V13.Submission.RequestChangesNotLoggedIn ->
            Evergreen.V14.Submission.RequestChangesNotLoggedIn

        Evergreen.V13.Submission.RequestChangesWrongWikiSession ->
            Evergreen.V14.Submission.RequestChangesWrongWikiSession

        Evergreen.V13.Submission.RequestChangesForbidden ->
            Evergreen.V14.Submission.RequestChangesForbidden

        Evergreen.V13.Submission.RequestChangesWikiNotFound ->
            Evergreen.V14.Submission.RequestChangesWikiNotFound

        Evergreen.V13.Submission.RequestChangesWikiInactive ->
            Evergreen.V14.Submission.RequestChangesWikiInactive

        Evergreen.V13.Submission.RequestChangesSubmissionNotFound ->
            Evergreen.V14.Submission.RequestChangesSubmissionNotFound

        Evergreen.V13.Submission.RequestChangesNotPending ->
            Evergreen.V14.Submission.RequestChangesNotPending

        Evergreen.V13.Submission.RequestChangesGuidanceInvalid p0 ->
            Evergreen.V14.Submission.RequestChangesGuidanceInvalid (p0 |> migrate_Submission_RejectReasonError)


migrate_Submission_RequestPublishedPageDeletionError : Evergreen.V13.Submission.RequestPublishedPageDeletionError -> Evergreen.V14.Submission.RequestPublishedPageDeletionError
migrate_Submission_RequestPublishedPageDeletionError old =
    case old of
        Evergreen.V13.Submission.RequestPublishedPageDeletionPrecondition p0 ->
            Evergreen.V14.Submission.RequestPublishedPageDeletionPrecondition (p0 |> migrate_Submission_PageDeletionPreconditionError)

        Evergreen.V13.Submission.RequestPublishedPageDeletionForbiddenTrustedModerator ->
            Evergreen.V14.Submission.RequestPublishedPageDeletionForbiddenTrustedModerator

        Evergreen.V13.Submission.RequestPublishedPageDeletionSubmitDraftStepFailed p0 ->
            Evergreen.V14.Submission.RequestPublishedPageDeletionSubmitDraftStepFailed (p0 |> migrate_Submission_SubmitDraftForReviewError)


migrate_Submission_ReviewQueueError : Evergreen.V13.Submission.ReviewQueueError -> Evergreen.V14.Submission.ReviewQueueError
migrate_Submission_ReviewQueueError old =
    case old of
        Evergreen.V13.Submission.ReviewQueueNotLoggedIn ->
            Evergreen.V14.Submission.ReviewQueueNotLoggedIn

        Evergreen.V13.Submission.ReviewQueueWrongWikiSession ->
            Evergreen.V14.Submission.ReviewQueueWrongWikiSession

        Evergreen.V13.Submission.ReviewQueueForbidden ->
            Evergreen.V14.Submission.ReviewQueueForbidden

        Evergreen.V13.Submission.ReviewQueueWikiInactive ->
            Evergreen.V14.Submission.ReviewQueueWikiInactive


migrate_Submission_ReviewQueueItem : Evergreen.V13.Submission.ReviewQueueItem -> Evergreen.V14.Submission.ReviewQueueItem
migrate_Submission_ReviewQueueItem old =
    { id = old.id |> migrate_Submission_Id
    , kindLabel = old.kindLabel
    , authorDisplay = old.authorDisplay
    , maybePageSlug = old.maybePageSlug
    }


migrate_Submission_SaveNewPageDraftError : Evergreen.V13.Submission.SaveNewPageDraftError -> Evergreen.V14.Submission.SaveNewPageDraftError
migrate_Submission_SaveNewPageDraftError old =
    case old of
        Evergreen.V13.Submission.SaveNewPageDraftNotLoggedIn ->
            Evergreen.V14.Submission.SaveNewPageDraftNotLoggedIn

        Evergreen.V13.Submission.SaveNewPageDraftWrongWikiSession ->
            Evergreen.V14.Submission.SaveNewPageDraftWrongWikiSession

        Evergreen.V13.Submission.SaveNewPageDraftValidation p0 ->
            Evergreen.V14.Submission.SaveNewPageDraftValidation (p0 |> migrate_Submission_ValidationError)

        Evergreen.V13.Submission.SaveNewPageDraftSlugReserved ->
            Evergreen.V14.Submission.SaveNewPageDraftSlugReserved

        Evergreen.V13.Submission.SaveNewPageDraftNotFound ->
            Evergreen.V14.Submission.SaveNewPageDraftNotFound

        Evergreen.V13.Submission.SaveNewPageDraftForbidden ->
            Evergreen.V14.Submission.SaveNewPageDraftForbidden

        Evergreen.V13.Submission.SaveNewPageDraftWikiNotFound ->
            Evergreen.V14.Submission.SaveNewPageDraftWikiNotFound

        Evergreen.V13.Submission.SaveNewPageDraftWikiInactive ->
            Evergreen.V14.Submission.SaveNewPageDraftWikiInactive


migrate_Submission_SavePageDeleteDraftError : Evergreen.V13.Submission.SavePageDeleteDraftError -> Evergreen.V14.Submission.SavePageDeleteDraftError
migrate_Submission_SavePageDeleteDraftError old =
    case old of
        Evergreen.V13.Submission.SavePageDeleteDraftNotLoggedIn ->
            Evergreen.V14.Submission.SavePageDeleteDraftNotLoggedIn

        Evergreen.V13.Submission.SavePageDeleteDraftWrongWikiSession ->
            Evergreen.V14.Submission.SavePageDeleteDraftWrongWikiSession

        Evergreen.V13.Submission.SavePageDeleteDraftReasonInvalid p0 ->
            Evergreen.V14.Submission.SavePageDeleteDraftReasonInvalid (p0 |> migrate_Submission_DeleteReasonError)

        Evergreen.V13.Submission.SavePageDeleteDraftTargetNotPublished ->
            Evergreen.V14.Submission.SavePageDeleteDraftTargetNotPublished

        Evergreen.V13.Submission.SavePageDeleteDraftNotFound ->
            Evergreen.V14.Submission.SavePageDeleteDraftNotFound

        Evergreen.V13.Submission.SavePageDeleteDraftForbidden ->
            Evergreen.V14.Submission.SavePageDeleteDraftForbidden

        Evergreen.V13.Submission.SavePageDeleteDraftWikiNotFound ->
            Evergreen.V14.Submission.SavePageDeleteDraftWikiNotFound

        Evergreen.V13.Submission.SavePageDeleteDraftWikiInactive ->
            Evergreen.V14.Submission.SavePageDeleteDraftWikiInactive

        Evergreen.V13.Submission.SavePageDeleteDraftForbiddenTrustedModerator ->
            Evergreen.V14.Submission.SavePageDeleteDraftForbiddenTrustedModerator


migrate_Submission_SavePageEditDraftError : Evergreen.V13.Submission.SavePageEditDraftError -> Evergreen.V14.Submission.SavePageEditDraftError
migrate_Submission_SavePageEditDraftError old =
    case old of
        Evergreen.V13.Submission.SavePageEditDraftNotLoggedIn ->
            Evergreen.V14.Submission.SavePageEditDraftNotLoggedIn

        Evergreen.V13.Submission.SavePageEditDraftWrongWikiSession ->
            Evergreen.V14.Submission.SavePageEditDraftWrongWikiSession

        Evergreen.V13.Submission.SavePageEditDraftValidation p0 ->
            Evergreen.V14.Submission.SavePageEditDraftValidation (p0 |> migrate_Submission_ValidationError)

        Evergreen.V13.Submission.SavePageEditDraftTargetNotPublished ->
            Evergreen.V14.Submission.SavePageEditDraftTargetNotPublished

        Evergreen.V13.Submission.SavePageEditDraftAlreadyPendingEdit ->
            Evergreen.V14.Submission.SavePageEditDraftAlreadyPendingEdit

        Evergreen.V13.Submission.SavePageEditDraftNotFound ->
            Evergreen.V14.Submission.SavePageEditDraftNotFound

        Evergreen.V13.Submission.SavePageEditDraftForbidden ->
            Evergreen.V14.Submission.SavePageEditDraftForbidden

        Evergreen.V13.Submission.SavePageEditDraftWikiNotFound ->
            Evergreen.V14.Submission.SavePageEditDraftWikiNotFound

        Evergreen.V13.Submission.SavePageEditDraftWikiInactive ->
            Evergreen.V14.Submission.SavePageEditDraftWikiInactive


migrate_Submission_Status : Evergreen.V13.Submission.Status -> Evergreen.V14.Submission.Status
migrate_Submission_Status old =
    case old of
        Evergreen.V13.Submission.Draft ->
            Evergreen.V14.Submission.Draft

        Evergreen.V13.Submission.Pending ->
            Evergreen.V14.Submission.Pending

        Evergreen.V13.Submission.Approved ->
            Evergreen.V14.Submission.Approved

        Evergreen.V13.Submission.Rejected ->
            Evergreen.V14.Submission.Rejected

        Evergreen.V13.Submission.NeedsRevision ->
            Evergreen.V14.Submission.NeedsRevision


migrate_Submission_SubmitDraftForReviewError : Evergreen.V13.Submission.SubmitDraftForReviewError -> Evergreen.V14.Submission.SubmitDraftForReviewError
migrate_Submission_SubmitDraftForReviewError old =
    case old of
        Evergreen.V13.Submission.SubmitDraftForReviewNotLoggedIn ->
            Evergreen.V14.Submission.SubmitDraftForReviewNotLoggedIn

        Evergreen.V13.Submission.SubmitDraftForReviewWrongWikiSession ->
            Evergreen.V14.Submission.SubmitDraftForReviewWrongWikiSession

        Evergreen.V13.Submission.SubmitDraftForReviewWikiNotFound ->
            Evergreen.V14.Submission.SubmitDraftForReviewWikiNotFound

        Evergreen.V13.Submission.SubmitDraftForReviewWikiInactive ->
            Evergreen.V14.Submission.SubmitDraftForReviewWikiInactive

        Evergreen.V13.Submission.SubmitDraftForReviewNotDraft ->
            Evergreen.V14.Submission.SubmitDraftForReviewNotDraft

        Evergreen.V13.Submission.SubmitDraftForReviewValidation p0 ->
            Evergreen.V14.Submission.SubmitDraftForReviewValidation (p0 |> migrate_Submission_ValidationError)

        Evergreen.V13.Submission.SubmitDraftForReviewSlugInUse ->
            Evergreen.V14.Submission.SubmitDraftForReviewSlugInUse

        Evergreen.V13.Submission.SubmitDraftForReviewPageExists ->
            Evergreen.V14.Submission.SubmitDraftForReviewPageExists

        Evergreen.V13.Submission.SubmitDraftForReviewEditTargetNotPublished ->
            Evergreen.V14.Submission.SubmitDraftForReviewEditTargetNotPublished

        Evergreen.V13.Submission.SubmitDraftForReviewEditAlreadyPending ->
            Evergreen.V14.Submission.SubmitDraftForReviewEditAlreadyPending

        Evergreen.V13.Submission.SubmitDraftForReviewDeleteTargetNotPublished ->
            Evergreen.V14.Submission.SubmitDraftForReviewDeleteTargetNotPublished

        Evergreen.V13.Submission.SubmitDraftForReviewDeleteReasonInvalid p0 ->
            Evergreen.V14.Submission.SubmitDraftForReviewDeleteReasonInvalid (p0 |> migrate_Submission_DeleteReasonError)

        Evergreen.V13.Submission.SubmitDraftForReviewNotFound ->
            Evergreen.V14.Submission.SubmitDraftForReviewNotFound

        Evergreen.V13.Submission.SubmitDraftForReviewForbidden ->
            Evergreen.V14.Submission.SubmitDraftForReviewForbidden

        Evergreen.V13.Submission.SubmitDraftForReviewDeleteForbiddenTrustedModerator ->
            Evergreen.V14.Submission.SubmitDraftForReviewDeleteForbiddenTrustedModerator


migrate_Submission_SubmitNewPageError : Evergreen.V13.Submission.SubmitNewPageError -> Evergreen.V14.Submission.SubmitNewPageError
migrate_Submission_SubmitNewPageError old =
    case old of
        Evergreen.V13.Submission.NotLoggedIn ->
            Evergreen.V14.Submission.NotLoggedIn

        Evergreen.V13.Submission.WrongWikiSession ->
            Evergreen.V14.Submission.WrongWikiSession

        Evergreen.V13.Submission.WikiNotFound ->
            Evergreen.V14.Submission.WikiNotFound

        Evergreen.V13.Submission.WikiInactive ->
            Evergreen.V14.Submission.WikiInactive

        Evergreen.V13.Submission.Validation p0 ->
            Evergreen.V14.Submission.Validation (p0 |> migrate_Submission_ValidationError)

        Evergreen.V13.Submission.SlugAlreadyInUse ->
            Evergreen.V14.Submission.SlugAlreadyInUse


migrate_Submission_SubmitPageEditError : Evergreen.V13.Submission.SubmitPageEditError -> Evergreen.V14.Submission.SubmitPageEditError
migrate_Submission_SubmitPageEditError old =
    case old of
        Evergreen.V13.Submission.EditNotLoggedIn ->
            Evergreen.V14.Submission.EditNotLoggedIn

        Evergreen.V13.Submission.EditWrongWikiSession ->
            Evergreen.V14.Submission.EditWrongWikiSession

        Evergreen.V13.Submission.EditWikiNotFound ->
            Evergreen.V14.Submission.EditWikiNotFound

        Evergreen.V13.Submission.EditWikiInactive ->
            Evergreen.V14.Submission.EditWikiInactive

        Evergreen.V13.Submission.EditValidation p0 ->
            Evergreen.V14.Submission.EditValidation (p0 |> migrate_Submission_ValidationError)

        Evergreen.V13.Submission.EditTargetPageNotPublished ->
            Evergreen.V14.Submission.EditTargetPageNotPublished

        Evergreen.V13.Submission.EditAlreadyPendingForAuthor ->
            Evergreen.V14.Submission.EditAlreadyPendingForAuthor


migrate_Submission_ValidationError : Evergreen.V13.Submission.ValidationError -> Evergreen.V14.Submission.ValidationError
migrate_Submission_ValidationError old =
    case old of
        Evergreen.V13.Submission.SlugEmpty ->
            Evergreen.V14.Submission.SlugEmpty

        Evergreen.V13.Submission.SlugTooLong ->
            Evergreen.V14.Submission.SlugTooLong

        Evergreen.V13.Submission.SlugInvalidChars ->
            Evergreen.V14.Submission.SlugInvalidChars

        Evergreen.V13.Submission.BodyEmpty ->
            Evergreen.V14.Submission.BodyEmpty


migrate_Types_FrontendMsg : Evergreen.V13.Types.FrontendMsg -> Evergreen.V14.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V13.Types.UrlClicked p0 ->
            Evergreen.V14.Types.UrlClicked p0

        Evergreen.V13.Types.UrlChanged p0 ->
            Evergreen.V14.Types.UrlChanged p0

        Evergreen.V13.Types.UrlFragmentScrollDone ->
            Evergreen.V14.Types.UrlFragmentScrollDone

        Evergreen.V13.Types.ColorThemeToggled ->
            Evergreen.V14.Types.ColorThemeToggled

        Evergreen.V13.Types.ColorThemeFromJs p0 ->
            Evergreen.V14.Types.ColorThemeFromJs (p0 |> Maybe.map migrate_ColorTheme_Incoming)

        Evergreen.V13.Types.RegisterFormUsernameChanged p0 ->
            Evergreen.V14.Types.RegisterFormUsernameChanged p0

        Evergreen.V13.Types.RegisterFormPasswordChanged p0 ->
            Evergreen.V14.Types.RegisterFormPasswordChanged p0

        Evergreen.V13.Types.RegisterFormSubmitted ->
            Evergreen.V14.Types.RegisterFormSubmitted

        Evergreen.V13.Types.LoginFormUsernameChanged p0 ->
            Evergreen.V14.Types.LoginFormUsernameChanged p0

        Evergreen.V13.Types.LoginFormPasswordChanged p0 ->
            Evergreen.V14.Types.LoginFormPasswordChanged p0

        Evergreen.V13.Types.LoginFormSubmitted ->
            Evergreen.V14.Types.LoginFormSubmitted

        Evergreen.V13.Types.HeaderSearchQueryChanged p0 ->
            Evergreen.V14.Types.HeaderSearchQueryChanged p0

        Evergreen.V13.Types.HeaderSearchSubmitted ->
            Evergreen.V14.Types.HeaderSearchSubmitted

        Evergreen.V13.Types.WikiSearchPageQueryChanged p0 ->
            Evergreen.V14.Types.WikiSearchPageQueryChanged p0

        Evergreen.V13.Types.ContributorLogoutWiki p0 ->
            Evergreen.V14.Types.ContributorLogoutWiki p0

        Evergreen.V13.Types.NewPageSubmitMarkdownChanged p0 ->
            Evergreen.V14.Types.NewPageSubmitMarkdownChanged p0

        Evergreen.V13.Types.NewPageSubmitSlugChanged p0 ->
            Evergreen.V14.Types.NewPageSubmitSlugChanged p0

        Evergreen.V13.Types.NewPageSubmitTagsChanged p0 ->
            Evergreen.V14.Types.NewPageSubmitTagsChanged p0

        Evergreen.V13.Types.NewPageSubmitFormSubmitted ->
            Evergreen.V14.Types.NewPageSubmitFormSubmitted

        Evergreen.V13.Types.PageEditSubmitMarkdownChanged p0 ->
            Evergreen.V14.Types.PageEditSubmitMarkdownChanged p0

        Evergreen.V13.Types.PageEditSubmitTagsChanged p0 ->
            Evergreen.V14.Types.PageEditSubmitTagsChanged p0

        Evergreen.V13.Types.PageEditSubmitFormSubmitted ->
            Evergreen.V14.Types.PageEditSubmitFormSubmitted

        Evergreen.V13.Types.PageDeleteSubmitReasonChanged p0 ->
            Evergreen.V14.Types.PageDeleteSubmitReasonChanged p0

        Evergreen.V13.Types.PageDeleteRequestDeletionSubmitted ->
            Evergreen.V14.Types.PageDeleteRequestDeletionSubmitted

        Evergreen.V13.Types.PageDeletePublishedImmediatelySubmitted ->
            Evergreen.V14.Types.PageDeletePublishedImmediatelySubmitted

        Evergreen.V13.Types.NewPageSaveDraftClicked ->
            Evergreen.V14.Types.NewPageSaveDraftClicked

        Evergreen.V13.Types.PageEditSaveDraftClicked ->
            Evergreen.V14.Types.PageEditSaveDraftClicked

        Evergreen.V13.Types.PageDeleteSaveDraftClicked ->
            Evergreen.V14.Types.PageDeleteSaveDraftClicked

        Evergreen.V13.Types.SubmissionDetailNewMarkdownChanged p0 ->
            Evergreen.V14.Types.SubmissionDetailNewMarkdownChanged p0

        Evergreen.V13.Types.SubmissionDetailNewPageSlugChanged p0 ->
            Evergreen.V14.Types.SubmissionDetailNewPageSlugChanged p0

        Evergreen.V13.Types.SubmissionDetailSaveDraftClicked ->
            Evergreen.V14.Types.SubmissionDetailSaveDraftClicked

        Evergreen.V13.Types.SubmissionDetailSubmitForReviewClicked ->
            Evergreen.V14.Types.SubmissionDetailSubmitForReviewClicked

        Evergreen.V13.Types.SubmissionDetailWithdrawClicked ->
            Evergreen.V14.Types.SubmissionDetailWithdrawClicked

        Evergreen.V13.Types.SubmissionDetailDeleteClicked ->
            Evergreen.V14.Types.SubmissionDetailDeleteClicked

        Evergreen.V13.Types.ReviewDecisionChanged p0 ->
            Evergreen.V14.Types.ReviewDecisionChanged (p0 |> migrate_Types_ReviewDecision)

        Evergreen.V13.Types.ReviewDecisionSubmitted ->
            Evergreen.V14.Types.ReviewDecisionSubmitted

        Evergreen.V13.Types.ReviewRejectReasonChanged p0 ->
            Evergreen.V14.Types.ReviewRejectReasonChanged p0

        Evergreen.V13.Types.ReviewRequestChangesNoteChanged p0 ->
            Evergreen.V14.Types.ReviewRequestChangesNoteChanged p0

        Evergreen.V13.Types.WikiAdminPromoteToTrustedClicked p0 ->
            Evergreen.V14.Types.WikiAdminPromoteToTrustedClicked p0

        Evergreen.V13.Types.WikiAdminDemoteToContributorClicked p0 ->
            Evergreen.V14.Types.WikiAdminDemoteToContributorClicked p0

        Evergreen.V13.Types.WikiAdminGrantAdminClicked p0 ->
            Evergreen.V14.Types.WikiAdminGrantAdminClicked p0

        Evergreen.V13.Types.WikiAdminRevokeAdminClicked p0 ->
            Evergreen.V14.Types.WikiAdminRevokeAdminClicked p0

        Evergreen.V13.Types.WikiAdminAuditFilterActorChanged p0 ->
            Evergreen.V14.Types.WikiAdminAuditFilterActorChanged p0

        Evergreen.V13.Types.WikiAdminAuditFilterPageChanged p0 ->
            Evergreen.V14.Types.WikiAdminAuditFilterPageChanged p0

        Evergreen.V13.Types.WikiAdminAuditFilterTypeTagToggled p0 p1 ->
            Evergreen.V14.Types.WikiAdminAuditFilterTypeTagToggled (p0 |> migrate_WikiAuditLog_AuditEventKindFilterTag)
                p1

        Evergreen.V13.Types.HostAdminLoginPasswordChanged p0 ->
            Evergreen.V14.Types.HostAdminLoginPasswordChanged p0

        Evergreen.V13.Types.HostAdminLoginSubmitted ->
            Evergreen.V14.Types.HostAdminLoginSubmitted

        Evergreen.V13.Types.HostAdminCreateWikiSlugChanged p0 ->
            Evergreen.V14.Types.HostAdminCreateWikiSlugChanged p0

        Evergreen.V13.Types.HostAdminCreateWikiNameChanged p0 ->
            Evergreen.V14.Types.HostAdminCreateWikiNameChanged p0

        Evergreen.V13.Types.HostAdminCreateWikiInitialAdminUsernameChanged p0 ->
            Evergreen.V14.Types.HostAdminCreateWikiInitialAdminUsernameChanged p0

        Evergreen.V13.Types.HostAdminCreateWikiInitialAdminPasswordChanged p0 ->
            Evergreen.V14.Types.HostAdminCreateWikiInitialAdminPasswordChanged p0

        Evergreen.V13.Types.HostAdminCreateWikiSubmitted ->
            Evergreen.V14.Types.HostAdminCreateWikiSubmitted

        Evergreen.V13.Types.HostAdminWikiDetailNameChanged p0 ->
            Evergreen.V14.Types.HostAdminWikiDetailNameChanged p0

        Evergreen.V13.Types.HostAdminWikiDetailSlugChanged p0 ->
            Evergreen.V14.Types.HostAdminWikiDetailSlugChanged p0

        Evergreen.V13.Types.HostAdminWikiDetailSummaryChanged p0 ->
            Evergreen.V14.Types.HostAdminWikiDetailSummaryChanged p0

        Evergreen.V13.Types.HostAdminWikiDetailSaveClicked ->
            Evergreen.V14.Types.HostAdminWikiDetailSaveClicked

        Evergreen.V13.Types.HostAdminWikiDetailDeactivateClicked ->
            Evergreen.V14.Types.HostAdminWikiDetailDeactivateClicked

        Evergreen.V13.Types.HostAdminWikiDetailReactivateClicked ->
            Evergreen.V14.Types.HostAdminWikiDetailReactivateClicked

        Evergreen.V13.Types.HostAdminWikiDetailDeleteConfirmChanged p0 ->
            Evergreen.V14.Types.HostAdminWikiDetailDeleteConfirmChanged p0

        Evergreen.V13.Types.HostAdminWikiDetailDeleteSubmitted ->
            Evergreen.V14.Types.HostAdminWikiDetailDeleteSubmitted

        Evergreen.V13.Types.HostAdminAuditFilterWikiChanged p0 ->
            Evergreen.V14.Types.HostAdminAuditFilterWikiChanged p0

        Evergreen.V13.Types.HostAdminAuditFilterActorChanged p0 ->
            Evergreen.V14.Types.HostAdminAuditFilterActorChanged p0

        Evergreen.V13.Types.HostAdminAuditFilterPageChanged p0 ->
            Evergreen.V14.Types.HostAdminAuditFilterPageChanged p0

        Evergreen.V13.Types.HostAdminAuditFilterTypeTagToggled p0 p1 ->
            Evergreen.V14.Types.HostAdminAuditFilterTypeTagToggled (p0 |> migrate_WikiAuditLog_AuditEventKindFilterTag)
                p1

        Evergreen.V13.Types.HostAdminDataExportClicked ->
            Evergreen.V14.Types.HostAdminDataExportClicked

        Evergreen.V13.Types.HostAdminDataImportPickRequested ->
            Evergreen.V14.Types.HostAdminDataImportPickRequested

        Evergreen.V13.Types.HostAdminDataImportFileSelected p0 ->
            Evergreen.V14.Types.HostAdminDataImportFileSelected p0

        Evergreen.V13.Types.HostAdminDataImportFileRead p0 ->
            Evergreen.V14.Types.HostAdminDataImportFileRead p0

        Evergreen.V13.Types.HostAdminWikisDataImportPickRequested ->
            Evergreen.V14.Types.HostAdminWikisDataImportPickRequested

        Evergreen.V13.Types.HostAdminWikisDataImportFileSelected p0 ->
            Evergreen.V14.Types.HostAdminWikisDataImportFileSelected p0

        Evergreen.V13.Types.HostAdminWikisDataImportFileRead p0 ->
            Evergreen.V14.Types.HostAdminWikisDataImportFileRead p0

        Evergreen.V13.Types.HostAdminWikiDataExportClicked p0 ->
            Evergreen.V14.Types.HostAdminWikiDataExportClicked p0

        Evergreen.V13.Types.HostAdminWikiDataImportPickRequested p0 ->
            Evergreen.V14.Types.HostAdminWikiDataImportPickRequested p0

        Evergreen.V13.Types.HostAdminWikiDataImportFileSelected p0 ->
            Evergreen.V14.Types.HostAdminWikiDataImportFileSelected p0

        Evergreen.V13.Types.HostAdminWikiDataImportFileRead p0 p1 ->
            Evergreen.V14.Types.HostAdminWikiDataImportFileRead p0 p1


migrate_Types_HostAdminCreateWikiDraft : Evergreen.V13.Types.HostAdminCreateWikiDraft -> Evergreen.V14.Types.HostAdminCreateWikiDraft
migrate_Types_HostAdminCreateWikiDraft old =
    { slug = old.slug
    , name = old.name
    , initialAdminUsername = old.initialAdminUsername
    , initialAdminPassword = old.initialAdminPassword
    , inFlight = old.inFlight
    , lastResult = old.lastResult |> Maybe.map (Result.mapError migrate_HostAdmin_CreateHostedWikiError >> Result.map migrate_Wiki_CatalogEntry)
    }


migrate_Types_HostAdminLoginDraft : Evergreen.V13.Types.HostAdminLoginDraft -> Evergreen.V14.Types.HostAdminLoginDraft
migrate_Types_HostAdminLoginDraft old =
    { password = old.password
    , inFlight = old.inFlight
    , lastResult = old.lastResult |> Maybe.map (Result.mapError migrate_HostAdmin_LoginError)
    }


migrate_Types_HostAdminWikiDetailDraft : Evergreen.V13.Types.HostAdminWikiDetailDraft -> Evergreen.V14.Types.HostAdminWikiDetailDraft
migrate_Types_HostAdminWikiDetailDraft old =
    { wikiSlug = old.wikiSlug
    , load = old.load |> migrate_RemoteData_RemoteData identity (Result.mapError migrate_HostAdmin_HostWikiDetailError >> Result.map migrate_Wiki_CatalogEntry)
    , slugDraft = old.slugDraft
    , nameDraft = old.nameDraft
    , summaryDraft = old.summaryDraft
    , saveInFlight = old.saveInFlight
    , lastSaveResult = old.lastSaveResult |> Maybe.map (Result.mapError migrate_HostAdmin_UpdateHostedWikiMetadataError)
    , lifecycleInFlight = old.lifecycleInFlight
    , lastLifecycleResult = old.lastLifecycleResult |> Maybe.map (Result.mapError migrate_HostAdmin_WikiLifecycleError)
    , deleteConfirmDraft = old.deleteConfirmDraft
    , deleteInFlight = old.deleteInFlight
    , lastDeleteResult = old.lastDeleteResult |> Maybe.map (Result.mapError migrate_HostAdmin_DeleteHostedWikiError)
    }


migrate_Types_LoginDraft : Evergreen.V13.Types.LoginDraft -> Evergreen.V14.Types.LoginDraft
migrate_Types_LoginDraft old =
    { username = old.username
    , password = old.password
    , inFlight = old.inFlight
    , lastResult = old.lastResult |> Maybe.map (Result.mapError migrate_ContributorAccount_LoginContributorError)
    }


migrate_Types_NewPageSubmitDraft : Evergreen.V13.Types.NewPageSubmitDraft -> Evergreen.V14.Types.NewPageSubmitDraft
migrate_Types_NewPageSubmitDraft old =
    { pageSlug = old.pageSlug
    , pageSlugLockedFromQuery = old.pageSlugLockedFromQuery
    , markdownBody = old.markdownBody
    , tagsInput = old.tagsInput
    , maybeSavedDraftId = old.maybeSavedDraftId
    , inFlight = old.inFlight
    , saveDraftInFlight = old.saveDraftInFlight
    , pendingSubmitAfterSave = old.pendingSubmitAfterSave
    , lastResult = old.lastResult |> Maybe.map (Result.mapError migrate_Submission_SubmitNewPageError >> Result.map migrate_Submission_NewPageSubmitSuccess)
    , lastSaveDraftResult = old.lastSaveDraftResult |> Maybe.map (Result.mapError migrate_Submission_SaveNewPageDraftError >> Result.map migrate_Submission_Id)
    }


migrate_Types_PageDeleteSubmitDraft : Evergreen.V13.Types.PageDeleteSubmitDraft -> Evergreen.V14.Types.PageDeleteSubmitDraft
migrate_Types_PageDeleteSubmitDraft old =
    { reasonText = old.reasonText
    , maybeSavedDraftId = old.maybeSavedDraftId
    , inFlight = old.inFlight
    , saveDraftInFlight = old.saveDraftInFlight
    , pendingSubmitAfterSave = old.pendingSubmitAfterSave
    , lastResult = old.lastResult |> Maybe.map (Result.mapError migrate_Submission_PageDeleteFormError >> Result.map migrate_Submission_PageDeleteFormSuccess)
    , lastSaveDraftResult = old.lastSaveDraftResult |> Maybe.map (Result.mapError migrate_Submission_SavePageDeleteDraftError >> Result.map migrate_Submission_Id)
    }


migrate_Types_PageEditSubmitDraft : Evergreen.V13.Types.PageEditSubmitDraft -> Evergreen.V14.Types.PageEditSubmitDraft
migrate_Types_PageEditSubmitDraft old =
    { markdownBody = old.markdownBody
    , tagsInput = old.tagsInput
    , publishedRowCollapsed = False
    , maybeSavedDraftId = old.maybeSavedDraftId
    , inFlight = old.inFlight
    , saveDraftInFlight = old.saveDraftInFlight
    , pendingSubmitAfterSave = old.pendingSubmitAfterSave
    , lastResult = old.lastResult |> Maybe.map (Result.mapError migrate_Submission_SubmitPageEditError >> Result.map migrate_Submission_EditSubmitSuccess)
    , lastSaveDraftResult = old.lastSaveDraftResult |> Maybe.map (Result.mapError migrate_Submission_SavePageEditDraftError >> Result.map migrate_Submission_Id)
    }


migrate_Types_RegisterDraft : Evergreen.V13.Types.RegisterDraft -> Evergreen.V14.Types.RegisterDraft
migrate_Types_RegisterDraft old =
    { username = old.username
    , password = old.password
    , inFlight = old.inFlight
    , lastResult = old.lastResult |> Maybe.map (Result.mapError migrate_ContributorAccount_RegisterContributorError)
    }


migrate_Types_ReviewApproveDraft : Evergreen.V13.Types.ReviewApproveDraft -> Evergreen.V14.Types.ReviewApproveDraft
migrate_Types_ReviewApproveDraft old =
    { inFlight = old.inFlight
    , lastResult = old.lastResult |> Maybe.map (Result.mapError migrate_Submission_ApproveSubmissionError)
    }


migrate_Types_ReviewDecision : Evergreen.V13.Types.ReviewDecision -> Evergreen.V14.Types.ReviewDecision
migrate_Types_ReviewDecision old =
    case old of
        Evergreen.V13.Types.ReviewDecisionApprove ->
            Evergreen.V14.Types.ReviewDecisionApprove

        Evergreen.V13.Types.ReviewDecisionRequestChanges ->
            Evergreen.V14.Types.ReviewDecisionRequestChanges

        Evergreen.V13.Types.ReviewDecisionReject ->
            Evergreen.V14.Types.ReviewDecisionReject


migrate_Types_ReviewRejectDraft : Evergreen.V13.Types.ReviewRejectDraft -> Evergreen.V14.Types.ReviewRejectDraft
migrate_Types_ReviewRejectDraft old =
    { reasonText = old.reasonText
    , inFlight = old.inFlight
    , lastResult = old.lastResult |> Maybe.map (Result.mapError migrate_Submission_RejectSubmissionError)
    }


migrate_Types_ReviewRequestChangesDraft : Evergreen.V13.Types.ReviewRequestChangesDraft -> Evergreen.V14.Types.ReviewRequestChangesDraft
migrate_Types_ReviewRequestChangesDraft old =
    { guidanceText = old.guidanceText
    , inFlight = old.inFlight
    , lastResult = old.lastResult |> Maybe.map (Result.mapError migrate_Submission_RequestChangesSubmissionError)
    }


migrate_Types_SubmissionDetailEditDraft : Evergreen.V13.Types.SubmissionDetailEditDraft -> Evergreen.V14.Types.SubmissionDetailEditDraft
migrate_Types_SubmissionDetailEditDraft old =
    old


migrate_WikiAdminUsers_Error : Evergreen.V13.WikiAdminUsers.Error -> Evergreen.V14.WikiAdminUsers.Error
migrate_WikiAdminUsers_Error old =
    case old of
        Evergreen.V13.WikiAdminUsers.NotLoggedIn ->
            Evergreen.V14.WikiAdminUsers.NotLoggedIn

        Evergreen.V13.WikiAdminUsers.WrongWikiSession ->
            Evergreen.V14.WikiAdminUsers.WrongWikiSession

        Evergreen.V13.WikiAdminUsers.Forbidden ->
            Evergreen.V14.WikiAdminUsers.Forbidden

        Evergreen.V13.WikiAdminUsers.WikiNotFound ->
            Evergreen.V14.WikiAdminUsers.WikiNotFound

        Evergreen.V13.WikiAdminUsers.WikiInactive ->
            Evergreen.V14.WikiAdminUsers.WikiInactive


migrate_WikiAdminUsers_ListedUser : Evergreen.V13.WikiAdminUsers.ListedUser -> Evergreen.V14.WikiAdminUsers.ListedUser
migrate_WikiAdminUsers_ListedUser old =
    { username = old.username
    , role = old.role |> migrate_WikiRole_WikiRole
    }


migrate_WikiAuditLog_AuditEvent : Evergreen.V13.WikiAuditLog.AuditEvent -> Evergreen.V14.WikiAuditLog.AuditEvent
migrate_WikiAuditLog_AuditEvent old =
    { at = old.at
    , actorUsername = old.actorUsername
    , kind = old.kind |> migrate_WikiAuditLog_AuditEventKind
    }


migrate_WikiAuditLog_AuditEventKind : Evergreen.V13.WikiAuditLog.AuditEventKind -> Evergreen.V14.WikiAuditLog.AuditEventKind
migrate_WikiAuditLog_AuditEventKind old =
    case old of
        Evergreen.V13.WikiAuditLog.ApprovedSubmission p0 ->
            Evergreen.V14.WikiAuditLog.ApprovedSubmission p0

        Evergreen.V13.WikiAuditLog.RejectedSubmission p0 ->
            Evergreen.V14.WikiAuditLog.RejectedSubmission p0

        Evergreen.V13.WikiAuditLog.RequestedSubmissionChanges p0 ->
            Evergreen.V14.WikiAuditLog.RequestedSubmissionChanges p0

        Evergreen.V13.WikiAuditLog.PromotedContributorToTrusted p0 ->
            Evergreen.V14.WikiAuditLog.PromotedContributorToTrusted p0

        Evergreen.V13.WikiAuditLog.DemotedTrustedToContributor p0 ->
            Evergreen.V14.WikiAuditLog.DemotedTrustedToContributor p0

        Evergreen.V13.WikiAuditLog.GrantedWikiAdmin p0 ->
            Evergreen.V14.WikiAuditLog.GrantedWikiAdmin p0

        Evergreen.V13.WikiAuditLog.RevokedWikiAdmin p0 ->
            Evergreen.V14.WikiAuditLog.RevokedWikiAdmin p0

        Evergreen.V13.WikiAuditLog.TrustedPublishedNewPage p0 ->
            Evergreen.V14.WikiAuditLog.TrustedPublishedNewPage p0

        Evergreen.V13.WikiAuditLog.TrustedPublishedPageEdit p0 ->
            Evergreen.V14.WikiAuditLog.TrustedPublishedPageEdit p0

        Evergreen.V13.WikiAuditLog.TrustedPublishedPageDelete p0 ->
            Evergreen.V14.WikiAuditLog.TrustedPublishedPageDelete p0


migrate_WikiAuditLog_AuditEventKindFilterTag : Evergreen.V13.WikiAuditLog.AuditEventKindFilterTag -> Evergreen.V14.WikiAuditLog.AuditEventKindFilterTag
migrate_WikiAuditLog_AuditEventKindFilterTag old =
    case old of
        Evergreen.V13.WikiAuditLog.ApprovedSubmissionKind ->
            Evergreen.V14.WikiAuditLog.ApprovedSubmissionKind

        Evergreen.V13.WikiAuditLog.RejectedSubmissionKind ->
            Evergreen.V14.WikiAuditLog.RejectedSubmissionKind

        Evergreen.V13.WikiAuditLog.RequestedSubmissionChangesKind ->
            Evergreen.V14.WikiAuditLog.RequestedSubmissionChangesKind

        Evergreen.V13.WikiAuditLog.PromotedContributorToTrustedKind ->
            Evergreen.V14.WikiAuditLog.PromotedContributorToTrustedKind

        Evergreen.V13.WikiAuditLog.DemotedTrustedToContributorKind ->
            Evergreen.V14.WikiAuditLog.DemotedTrustedToContributorKind

        Evergreen.V13.WikiAuditLog.GrantedWikiAdminKind ->
            Evergreen.V14.WikiAuditLog.GrantedWikiAdminKind

        Evergreen.V13.WikiAuditLog.RevokedWikiAdminKind ->
            Evergreen.V14.WikiAuditLog.RevokedWikiAdminKind

        Evergreen.V13.WikiAuditLog.TrustedPublishedNewPageKind ->
            Evergreen.V14.WikiAuditLog.TrustedPublishedNewPageKind

        Evergreen.V13.WikiAuditLog.TrustedPublishedPageEditKind ->
            Evergreen.V14.WikiAuditLog.TrustedPublishedPageEditKind

        Evergreen.V13.WikiAuditLog.TrustedPublishedPageDeleteKind ->
            Evergreen.V14.WikiAuditLog.TrustedPublishedPageDeleteKind


migrate_WikiAuditLog_AuditLogFilter : Evergreen.V13.WikiAuditLog.AuditLogFilter -> Evergreen.V14.WikiAuditLog.AuditLogFilter
migrate_WikiAuditLog_AuditLogFilter old =
    { actorUsernameSubstring = old.actorUsernameSubstring
    , pageSlugSubstring = old.pageSlugSubstring
    , eventKindTags = old.eventKindTags |> List.map migrate_WikiAuditLog_AuditEventKindFilterTag
    }


migrate_WikiAuditLog_Error : Evergreen.V13.WikiAuditLog.Error -> Evergreen.V14.WikiAuditLog.Error
migrate_WikiAuditLog_Error old =
    case old of
        Evergreen.V13.WikiAuditLog.WikiNotFound ->
            Evergreen.V14.WikiAuditLog.WikiNotFound

        Evergreen.V13.WikiAuditLog.WikiInactive ->
            Evergreen.V14.WikiAuditLog.WikiInactive

        Evergreen.V13.WikiAuditLog.NotLoggedIn ->
            Evergreen.V14.WikiAuditLog.NotLoggedIn

        Evergreen.V13.WikiAuditLog.WrongWikiSession ->
            Evergreen.V14.WikiAuditLog.WrongWikiSession

        Evergreen.V13.WikiAuditLog.Forbidden ->
            Evergreen.V14.WikiAuditLog.Forbidden


migrate_WikiAuditLog_HostAuditLogFilter : Evergreen.V13.WikiAuditLog.HostAuditLogFilter -> Evergreen.V14.WikiAuditLog.HostAuditLogFilter
migrate_WikiAuditLog_HostAuditLogFilter old =
    { wikiSlugSubstring = old.wikiSlugSubstring
    , actorUsernameSubstring = old.actorUsernameSubstring
    , pageSlugSubstring = old.pageSlugSubstring
    , eventKindTags = old.eventKindTags |> List.map migrate_WikiAuditLog_AuditEventKindFilterTag
    }


migrate_WikiAuditLog_ScopedAuditEvent : Evergreen.V13.WikiAuditLog.ScopedAuditEvent -> Evergreen.V14.WikiAuditLog.ScopedAuditEvent
migrate_WikiAuditLog_ScopedAuditEvent old =
    { wikiSlug = old.wikiSlug
    , at = old.at
    , actorUsername = old.actorUsername
    , kind = old.kind |> migrate_WikiAuditLog_AuditEventKind
    }


migrate_WikiRole_SubmissionsScope : Evergreen.V13.WikiRole.SubmissionsScope -> Evergreen.V14.WikiRole.SubmissionsScope
migrate_WikiRole_SubmissionsScope old =
    case old of
        Evergreen.V13.WikiRole.SubmissionsScope ->
            Evergreen.V14.WikiRole.SubmissionsScope


migrate_WikiRole_UntrustedContributorCaps : Evergreen.V13.WikiRole.UntrustedContributorCaps -> Evergreen.V14.WikiRole.UntrustedContributorCaps
migrate_WikiRole_UntrustedContributorCaps old =
    { submissions = old.submissions |> migrate_WikiRole_SubmissionsScope
    }


migrate_WikiRole_WikiRole : Evergreen.V13.WikiRole.WikiRole -> Evergreen.V14.WikiRole.WikiRole
migrate_WikiRole_WikiRole old =
    case old of
        Evergreen.V13.WikiRole.UntrustedContributor p0 ->
            Evergreen.V14.WikiRole.UntrustedContributor (p0 |> migrate_WikiRole_UntrustedContributorCaps)

        Evergreen.V13.WikiRole.TrustedContributor ->
            Evergreen.V14.WikiRole.TrustedContributor

        Evergreen.V13.WikiRole.Admin ->
            Evergreen.V14.WikiRole.Admin


migrate_Wiki_CatalogEntry : Evergreen.V13.Wiki.CatalogEntry -> Evergreen.V14.Wiki.CatalogEntry
migrate_Wiki_CatalogEntry old =
    old


migrate_Wiki_FrontendDetails : Evergreen.V13.Wiki.FrontendDetails -> Evergreen.V14.Wiki.FrontendDetails
migrate_Wiki_FrontendDetails old =
    { pageSlugs = old.pageSlugs
    , publishedPageMarkdownSources = old.publishedPageMarkdownSources
    , publishedPageTags = old.publishedPageTags
    , pendingReviewCountForTrustedViewer = old.pendingReviewCountForTrustedViewer
    , viewerSession = old.viewerSession |> Maybe.map migrate_ContributorWikiSession_ContributorWikiSession
    }
