module Evergreen.Migrate.V17 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V16.ColorTheme
import Evergreen.V16.ContributorAccount
import Evergreen.V16.ContributorWikiSession
import Evergreen.V16.HostAdmin
import Evergreen.V16.Route
import Evergreen.V16.Store
import Evergreen.V16.Submission
import Evergreen.V16.SubmissionReviewDetail
import Evergreen.V16.Types
import Evergreen.V16.Wiki
import Evergreen.V16.WikiAdminUsers
import Evergreen.V16.WikiAuditLog
import Evergreen.V16.WikiContributors
import Evergreen.V16.WikiMarkdownEditorPane
import Evergreen.V16.WikiRole
import Evergreen.V16.WikiUser
import Evergreen.V17.ColorTheme
import Evergreen.V17.ContributorAccount
import Evergreen.V17.ContributorWikiSession
import Evergreen.V17.HostAdmin
import Evergreen.V17.Route
import Evergreen.V17.Store
import Evergreen.V17.Submission
import Evergreen.V17.SubmissionReviewDetail
import Evergreen.V17.Types
import Evergreen.V17.Wiki
import Evergreen.V17.WikiAdminUsers
import Evergreen.V17.WikiAuditLog
import Evergreen.V17.WikiContributors
import Evergreen.V17.WikiMarkdownEditorPane
import Evergreen.V17.WikiRole
import Evergreen.V17.WikiUser
import Lamdera.Migrations exposing (..)
import List
import Maybe
import RemoteData
import Result


frontendModel : Evergreen.V16.Types.FrontendModel -> ModelMigration Evergreen.V17.Types.FrontendModel Evergreen.V17.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V16.Types.BackendModel -> ModelMigration Evergreen.V17.Types.BackendModel Evergreen.V17.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V16.Types.FrontendMsg -> MsgMigration Evergreen.V17.Types.FrontendMsg Evergreen.V17.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V16.Types.ToBackend -> MsgMigration Evergreen.V17.Types.ToBackend Evergreen.V17.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V16.Types.BackendMsg -> MsgMigration Evergreen.V17.Types.BackendMsg Evergreen.V17.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V16.Types.ToFrontend -> MsgMigration Evergreen.V17.Types.ToFrontend Evergreen.V17.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_BackendModel : Evergreen.V16.Types.BackendModel -> Evergreen.V17.Types.BackendModel
migrate_Types_BackendModel old =
    { wikis = old.wikis |> Dict.map (\k -> migrate_Wiki_Wiki)
    , contributors = old.contributors |> migrate_WikiContributors_Registry
    , contributorSessions = old.contributorSessions |> migrate_WikiUser_SessionTable
    , hostSessions = old.hostSessions
    , submissions = old.submissions |> Dict.map (\k -> migrate_Submission_Submission)
    , nextSubmissionCounter = old.nextSubmissionCounter
    , wikiAuditEvents = old.wikiAuditEvents |> Dict.map (\k -> List.map migrate_WikiAuditLog_AuditEvent)
    , pendingReviewCounts = old.pendingReviewCounts
    , pendingReviewClients = old.pendingReviewClients
    , wikiFrontendClients = old.wikiFrontendClients
    , wikiSearchIndexes = old.wikiSearchIndexes
    }


migrate_Types_FrontendModel : Evergreen.V16.Types.FrontendModel -> Evergreen.V17.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , colorThemePreference = old.colorThemePreference |> migrate_ColorTheme_ColorThemePreference
    , systemColorTheme = old.systemColorTheme |> migrate_ColorTheme_ColorTheme
    , route = old.route |> migrate_Route_Route
    , navigationFragment = old.navigationFragment
    , store = old.store |> migrate_Store_Store
    , contributorWikiSessions = old.contributorWikiSessions |> Dict.map (\k -> migrate_ContributorWikiSession_ContributorWikiSession)
    , registerDraft = old.registerDraft |> migrate_Types_RegisterDraft
    , loginDraft = old.loginDraft |> migrate_Types_LoginDraft
    , headerSearchQuery = old.headerSearchQuery
    , headerSearchResults = old.headerSearchResults
    , headerSearchPending = old.headerSearchPending
    , wikiSearchPageQuery = old.wikiSearchPageQuery
    , wikiSearchPageResults = old.wikiSearchPageResults
    , wikiSearchPagePending = old.wikiSearchPagePending
    , newPageSubmitDraft = old.newPageSubmitDraft |> migrate_Types_NewPageSubmitDraft
    , pageEditSubmitDraft = old.pageEditSubmitDraft |> migrate_Types_PageEditSubmitDraft
    , pageDeleteSubmitDraft = old.pageDeleteSubmitDraft |> migrate_Types_PageDeleteSubmitDraft
    , reviewApproveDraft = old.reviewApproveDraft |> migrate_Types_ReviewApproveDraft
    , reviewDecision = old.reviewDecision |> migrate_Types_ReviewDecision
    , reviewRejectDraft = old.reviewRejectDraft |> migrate_Types_ReviewRejectDraft
    , reviewRequestChangesDraft = old.reviewRequestChangesDraft |> migrate_Types_ReviewRequestChangesDraft
    , submissionDetailEditDraft = old.submissionDetailEditDraft |> migrate_Types_SubmissionDetailEditDraft
    , adminPromoteError = old.adminPromoteError
    , adminDemoteError = old.adminDemoteError
    , adminGrantAdminError = old.adminGrantAdminError
    , adminRevokeAdminError = old.adminRevokeAdminError
    , wikiAdminAuditFilterActorDraft = old.wikiAdminAuditFilterActorDraft
    , wikiAdminAuditFilterPageDraft = old.wikiAdminAuditFilterPageDraft
    , wikiAdminAuditFilterSelectedKindTags = old.wikiAdminAuditFilterSelectedKindTags |> List.map migrate_WikiAuditLog_AuditEventKindFilterTag
    , wikiAdminAuditAppliedFilter = old.wikiAdminAuditAppliedFilter |> migrate_WikiAuditLog_AuditLogFilter
    , hostAdminAuditFilterWikiDraft = old.hostAdminAuditFilterWikiDraft
    , hostAdminAuditFilterActorDraft = old.hostAdminAuditFilterActorDraft
    , hostAdminAuditFilterPageDraft = old.hostAdminAuditFilterPageDraft
    , hostAdminAuditFilterSelectedKindTags = old.hostAdminAuditFilterSelectedKindTags |> List.map migrate_WikiAuditLog_AuditEventKindFilterTag
    , hostAdminAuditAppliedFilter = old.hostAdminAuditAppliedFilter |> migrate_WikiAuditLog_HostAuditLogFilter
    , hostAdminAuditLog = old.hostAdminAuditLog |> migrate_RemoteData_RemoteData identity (Result.mapError migrate_HostAdmin_ProtectedError >> Result.map (List.map migrate_WikiAuditLog_ScopedAuditEvent))
    , hostAdminLoginDraft = old.hostAdminLoginDraft |> migrate_Types_HostAdminLoginDraft
    , hostAdminCreateWikiDraft = old.hostAdminCreateWikiDraft |> migrate_Types_HostAdminCreateWikiDraft
    , hostAdminWikiDetailDraft = old.hostAdminWikiDetailDraft |> migrate_Types_HostAdminWikiDetailDraft
    , hostAdminWikis = old.hostAdminWikis |> migrate_RemoteData_RemoteData identity (Result.mapError migrate_HostAdmin_ProtectedError)
    , hostAdminSessionAuthenticated = old.hostAdminSessionAuthenticated
    , hostAdminExportInFlight = old.hostAdminExportInFlight
    , hostAdminImportInFlight = old.hostAdminImportInFlight
    , hostAdminBackupNotice = old.hostAdminBackupNotice
    , hostAdminWikiExportInFlightSlug = old.hostAdminWikiExportInFlightSlug
    , hostAdminWikiImportInFlightSlug = old.hostAdminWikiImportInFlightSlug
    , hostAdminWikiImportPendingSlug = old.hostAdminWikiImportPendingSlug
    , hostAdminWikisNotice = old.hostAdminWikisNotice
    , sideNavOpen = old.sideNavOpen
    , wikiMarkdownEditorPane = old.wikiMarkdownEditorPane |> migrate_WikiMarkdownEditorPane_WikiMarkdownEditorPane
    }


migrate_ColorTheme_ColorTheme : Evergreen.V16.ColorTheme.ColorTheme -> Evergreen.V17.ColorTheme.ColorTheme
migrate_ColorTheme_ColorTheme old =
    case old of
        Evergreen.V16.ColorTheme.Light ->
            Evergreen.V17.ColorTheme.Light

        Evergreen.V16.ColorTheme.Dark ->
            Evergreen.V17.ColorTheme.Dark


migrate_ColorTheme_ColorThemePreference : Evergreen.V16.ColorTheme.ColorThemePreference -> Evergreen.V17.ColorTheme.ColorThemePreference
migrate_ColorTheme_ColorThemePreference old =
    case old of
        Evergreen.V16.ColorTheme.FollowSystem ->
            Evergreen.V17.ColorTheme.FollowSystem

        Evergreen.V16.ColorTheme.Fixed p0 ->
            Evergreen.V17.ColorTheme.Fixed (p0 |> migrate_ColorTheme_ColorTheme)


migrate_ContributorAccount_Id : Evergreen.V16.ContributorAccount.Id -> Evergreen.V17.ContributorAccount.Id
migrate_ContributorAccount_Id old =
    case old of
        Evergreen.V16.ContributorAccount.Id p0 ->
            Evergreen.V17.ContributorAccount.Id p0


migrate_ContributorAccount_LoginContributorError : Evergreen.V16.ContributorAccount.LoginContributorError -> Evergreen.V17.ContributorAccount.LoginContributorError
migrate_ContributorAccount_LoginContributorError old =
    case old of
        Evergreen.V16.ContributorAccount.LoginWikiNotFound ->
            Evergreen.V17.ContributorAccount.LoginWikiNotFound

        Evergreen.V16.ContributorAccount.LoginWikiInactive ->
            Evergreen.V17.ContributorAccount.LoginWikiInactive

        Evergreen.V16.ContributorAccount.LoginInvalidCredentials ->
            Evergreen.V17.ContributorAccount.LoginInvalidCredentials

        Evergreen.V16.ContributorAccount.LoginUsernameEmpty ->
            Evergreen.V17.ContributorAccount.LoginUsernameEmpty

        Evergreen.V16.ContributorAccount.LoginPasswordEmpty ->
            Evergreen.V17.ContributorAccount.LoginPasswordEmpty


migrate_ContributorAccount_RegisterContributorError : Evergreen.V16.ContributorAccount.RegisterContributorError -> Evergreen.V17.ContributorAccount.RegisterContributorError
migrate_ContributorAccount_RegisterContributorError old =
    case old of
        Evergreen.V16.ContributorAccount.RegisterWikiNotFound ->
            Evergreen.V17.ContributorAccount.RegisterWikiNotFound

        Evergreen.V16.ContributorAccount.RegisterWikiInactive ->
            Evergreen.V17.ContributorAccount.RegisterWikiInactive

        Evergreen.V16.ContributorAccount.RegisterUsernameTaken ->
            Evergreen.V17.ContributorAccount.RegisterUsernameTaken

        Evergreen.V16.ContributorAccount.RegisterUsernameEmpty ->
            Evergreen.V17.ContributorAccount.RegisterUsernameEmpty

        Evergreen.V16.ContributorAccount.RegisterUsernameTooShort ->
            Evergreen.V17.ContributorAccount.RegisterUsernameTooShort

        Evergreen.V16.ContributorAccount.RegisterUsernameTooLong ->
            Evergreen.V17.ContributorAccount.RegisterUsernameTooLong

        Evergreen.V16.ContributorAccount.RegisterUsernameInvalidChars ->
            Evergreen.V17.ContributorAccount.RegisterUsernameInvalidChars

        Evergreen.V16.ContributorAccount.RegisterPasswordEmpty ->
            Evergreen.V17.ContributorAccount.RegisterPasswordEmpty


migrate_ContributorAccount_Verifier : Evergreen.V16.ContributorAccount.Verifier -> Evergreen.V17.ContributorAccount.Verifier
migrate_ContributorAccount_Verifier old =
    case old of
        Evergreen.V16.ContributorAccount.Verifier p0 ->
            Evergreen.V17.ContributorAccount.Verifier p0


migrate_ContributorWikiSession_ContributorWikiSession : Evergreen.V16.ContributorWikiSession.ContributorWikiSession -> Evergreen.V17.ContributorWikiSession.ContributorWikiSession
migrate_ContributorWikiSession_ContributorWikiSession old =
    { role = old.role |> migrate_WikiRole_WikiRole
    , displayUsername = old.displayUsername
    }


migrate_HostAdmin_CreateHostedWikiError : Evergreen.V16.HostAdmin.CreateHostedWikiError -> Evergreen.V17.HostAdmin.CreateHostedWikiError
migrate_HostAdmin_CreateHostedWikiError old =
    case old of
        Evergreen.V16.HostAdmin.CreateNotHostAuthenticated ->
            Evergreen.V17.HostAdmin.CreateNotHostAuthenticated

        Evergreen.V16.HostAdmin.CreateSlugInvalid p0 ->
            Evergreen.V17.HostAdmin.CreateSlugInvalid (p0 |> migrate_Submission_ValidationError)

        Evergreen.V16.HostAdmin.CreateWikiNameInvalid p0 ->
            Evergreen.V17.HostAdmin.CreateWikiNameInvalid (p0 |> migrate_HostAdmin_WikiNameError)

        Evergreen.V16.HostAdmin.CreateWikiSlugTaken ->
            Evergreen.V17.HostAdmin.CreateWikiSlugTaken

        Evergreen.V16.HostAdmin.CreateInitialAdminInvalid p0 ->
            Evergreen.V17.HostAdmin.CreateInitialAdminInvalid (p0 |> migrate_ContributorAccount_RegisterContributorError)


migrate_HostAdmin_DataExportError : Evergreen.V16.HostAdmin.DataExportError -> Evergreen.V17.HostAdmin.DataExportError
migrate_HostAdmin_DataExportError old =
    case old of
        Evergreen.V16.HostAdmin.DataExportNotHostAuthenticated ->
            Evergreen.V17.HostAdmin.DataExportNotHostAuthenticated


migrate_HostAdmin_DataImportError : Evergreen.V16.HostAdmin.DataImportError -> Evergreen.V17.HostAdmin.DataImportError
migrate_HostAdmin_DataImportError old =
    case old of
        Evergreen.V16.HostAdmin.DataImportNotHostAuthenticated ->
            Evergreen.V17.HostAdmin.DataImportNotHostAuthenticated

        Evergreen.V16.HostAdmin.DataImportInvalid p0 ->
            Evergreen.V17.HostAdmin.DataImportInvalid p0


migrate_HostAdmin_DeleteHostedWikiError : Evergreen.V16.HostAdmin.DeleteHostedWikiError -> Evergreen.V17.HostAdmin.DeleteHostedWikiError
migrate_HostAdmin_DeleteHostedWikiError old =
    case old of
        Evergreen.V16.HostAdmin.DeleteHostedWikiNotHostAuthenticated ->
            Evergreen.V17.HostAdmin.DeleteHostedWikiNotHostAuthenticated

        Evergreen.V16.HostAdmin.DeleteHostedWikiWikiNotFound ->
            Evergreen.V17.HostAdmin.DeleteHostedWikiWikiNotFound

        Evergreen.V16.HostAdmin.DeleteHostedWikiConfirmationMismatch ->
            Evergreen.V17.HostAdmin.DeleteHostedWikiConfirmationMismatch


migrate_HostAdmin_HostWikiDetailError : Evergreen.V16.HostAdmin.HostWikiDetailError -> Evergreen.V17.HostAdmin.HostWikiDetailError
migrate_HostAdmin_HostWikiDetailError old =
    case old of
        Evergreen.V16.HostAdmin.HostWikiDetailNotHostAuthenticated ->
            Evergreen.V17.HostAdmin.HostWikiDetailNotHostAuthenticated

        Evergreen.V16.HostAdmin.HostWikiDetailWikiNotFound ->
            Evergreen.V17.HostAdmin.HostWikiDetailWikiNotFound


migrate_HostAdmin_LoginError : Evergreen.V16.HostAdmin.LoginError -> Evergreen.V17.HostAdmin.LoginError
migrate_HostAdmin_LoginError old =
    case old of
        Evergreen.V16.HostAdmin.WrongPassword ->
            Evergreen.V17.HostAdmin.WrongPassword


migrate_HostAdmin_ProtectedError : Evergreen.V16.HostAdmin.ProtectedError -> Evergreen.V17.HostAdmin.ProtectedError
migrate_HostAdmin_ProtectedError old =
    case old of
        Evergreen.V16.HostAdmin.NotHostAuthenticated ->
            Evergreen.V17.HostAdmin.NotHostAuthenticated


migrate_HostAdmin_UpdateHostedWikiMetadataError : Evergreen.V16.HostAdmin.UpdateHostedWikiMetadataError -> Evergreen.V17.HostAdmin.UpdateHostedWikiMetadataError
migrate_HostAdmin_UpdateHostedWikiMetadataError old =
    case old of
        Evergreen.V16.HostAdmin.UpdateMetadataNotHostAuthenticated ->
            Evergreen.V17.HostAdmin.UpdateMetadataNotHostAuthenticated

        Evergreen.V16.HostAdmin.UpdateMetadataWikiNotFound ->
            Evergreen.V17.HostAdmin.UpdateMetadataWikiNotFound

        Evergreen.V16.HostAdmin.UpdateMetadataWikiNameInvalid p0 ->
            Evergreen.V17.HostAdmin.UpdateMetadataWikiNameInvalid (p0 |> migrate_HostAdmin_WikiNameError)

        Evergreen.V16.HostAdmin.UpdateMetadataWikiSummaryInvalid p0 ->
            Evergreen.V17.HostAdmin.UpdateMetadataWikiSummaryInvalid (p0 |> migrate_HostAdmin_WikiSummaryError)

        Evergreen.V16.HostAdmin.UpdateMetadataWikiSlugInvalid p0 ->
            Evergreen.V17.HostAdmin.UpdateMetadataWikiSlugInvalid (p0 |> migrate_Submission_ValidationError)

        Evergreen.V16.HostAdmin.UpdateMetadataWikiSlugTaken ->
            Evergreen.V17.HostAdmin.UpdateMetadataWikiSlugTaken


migrate_HostAdmin_WikiDataExportError : Evergreen.V16.HostAdmin.WikiDataExportError -> Evergreen.V17.HostAdmin.WikiDataExportError
migrate_HostAdmin_WikiDataExportError old =
    case old of
        Evergreen.V16.HostAdmin.WikiDataExportNotHostAuthenticated ->
            Evergreen.V17.HostAdmin.WikiDataExportNotHostAuthenticated

        Evergreen.V16.HostAdmin.WikiDataExportWikiNotFound ->
            Evergreen.V17.HostAdmin.WikiDataExportWikiNotFound


migrate_HostAdmin_WikiDataImportError : Evergreen.V16.HostAdmin.WikiDataImportError -> Evergreen.V17.HostAdmin.WikiDataImportError
migrate_HostAdmin_WikiDataImportError old =
    case old of
        Evergreen.V16.HostAdmin.WikiDataImportNotHostAuthenticated ->
            Evergreen.V17.HostAdmin.WikiDataImportNotHostAuthenticated

        Evergreen.V16.HostAdmin.WikiDataImportWikiNotFound ->
            Evergreen.V17.HostAdmin.WikiDataImportWikiNotFound

        Evergreen.V16.HostAdmin.WikiDataImportInvalid p0 ->
            Evergreen.V17.HostAdmin.WikiDataImportInvalid p0


migrate_HostAdmin_WikiLifecycleError : Evergreen.V16.HostAdmin.WikiLifecycleError -> Evergreen.V17.HostAdmin.WikiLifecycleError
migrate_HostAdmin_WikiLifecycleError old =
    case old of
        Evergreen.V16.HostAdmin.WikiLifecycleNotHostAuthenticated ->
            Evergreen.V17.HostAdmin.WikiLifecycleNotHostAuthenticated

        Evergreen.V16.HostAdmin.WikiLifecycleWikiNotFound ->
            Evergreen.V17.HostAdmin.WikiLifecycleWikiNotFound


migrate_HostAdmin_WikiNameError : Evergreen.V16.HostAdmin.WikiNameError -> Evergreen.V17.HostAdmin.WikiNameError
migrate_HostAdmin_WikiNameError old =
    case old of
        Evergreen.V16.HostAdmin.WikiNameEmpty ->
            Evergreen.V17.HostAdmin.WikiNameEmpty

        Evergreen.V16.HostAdmin.WikiNameTooLong ->
            Evergreen.V17.HostAdmin.WikiNameTooLong


migrate_HostAdmin_WikiSummaryError : Evergreen.V16.HostAdmin.WikiSummaryError -> Evergreen.V17.HostAdmin.WikiSummaryError
migrate_HostAdmin_WikiSummaryError old =
    case old of
        Evergreen.V16.HostAdmin.WikiSummaryTooLong ->
            Evergreen.V17.HostAdmin.WikiSummaryTooLong


migrate_RemoteData_RemoteData : (e_old -> e_new) -> (a_old -> a_new) -> RemoteData.RemoteData e_old a_old -> RemoteData.RemoteData e_new a_new
migrate_RemoteData_RemoteData migrate_e migrate_a old =
    case old of
        RemoteData.NotAsked ->
            RemoteData.NotAsked

        RemoteData.Loading ->
            RemoteData.Loading

        RemoteData.Failure p0 ->
            RemoteData.Failure (p0 |> migrate_e)

        RemoteData.Success p0 ->
            RemoteData.Success (p0 |> migrate_a)


migrate_Route_Route : Evergreen.V16.Route.Route -> Evergreen.V17.Route.Route
migrate_Route_Route old =
    case old of
        Evergreen.V16.Route.WikiList ->
            Evergreen.V17.Route.WikiList

        Evergreen.V16.Route.HostAdmin p0 ->
            Evergreen.V17.Route.HostAdmin p0

        Evergreen.V16.Route.HostAdminWikis ->
            Evergreen.V17.Route.HostAdminWikis

        Evergreen.V16.Route.HostAdminWikiNew ->
            Evergreen.V17.Route.HostAdminWikiNew

        Evergreen.V16.Route.HostAdminWikiDetail p0 ->
            Evergreen.V17.Route.HostAdminWikiDetail p0

        Evergreen.V16.Route.HostAdminAudit ->
            Evergreen.V17.Route.HostAdminAudit

        Evergreen.V16.Route.HostAdminAuditDiff p0 p1 ->
            Evergreen.V17.Route.HostAdminAuditDiff p0 p1

        Evergreen.V16.Route.HostAdminBackup ->
            Evergreen.V17.Route.HostAdminBackup

        Evergreen.V16.Route.WikiHome p0 ->
            Evergreen.V17.Route.WikiHome p0

        Evergreen.V16.Route.WikiTodos p0 ->
            Evergreen.V17.Route.WikiTodos p0

        Evergreen.V16.Route.WikiGraph p0 ->
            Evergreen.V17.Route.WikiGraph p0

        Evergreen.V16.Route.WikiSearch p0 ->
            Evergreen.V17.Route.WikiSearch p0

        Evergreen.V16.Route.WikiPage p0 p1 ->
            Evergreen.V17.Route.WikiPage p0 p1

        Evergreen.V16.Route.WikiPageGraph p0 p1 ->
            Evergreen.V17.Route.WikiPageGraph p0 p1

        Evergreen.V16.Route.WikiLogin p0 p1 ->
            Evergreen.V17.Route.WikiLogin p0 p1

        Evergreen.V16.Route.WikiRegister p0 ->
            Evergreen.V17.Route.WikiRegister p0

        Evergreen.V16.Route.WikiSubmitNew p0 ->
            Evergreen.V17.Route.WikiSubmitNew p0

        Evergreen.V16.Route.WikiSubmitEdit p0 p1 ->
            Evergreen.V17.Route.WikiSubmitEdit p0 p1

        Evergreen.V16.Route.WikiSubmitDelete p0 p1 ->
            Evergreen.V17.Route.WikiSubmitDelete p0 p1

        Evergreen.V16.Route.WikiSubmissionDetail p0 p1 ->
            Evergreen.V17.Route.WikiSubmissionDetail p0 p1

        Evergreen.V16.Route.WikiMySubmissions p0 ->
            Evergreen.V17.Route.WikiMySubmissions p0

        Evergreen.V16.Route.WikiReview p0 ->
            Evergreen.V17.Route.WikiReview p0

        Evergreen.V16.Route.WikiReviewDetail p0 p1 ->
            Evergreen.V17.Route.WikiReviewDetail p0 p1

        Evergreen.V16.Route.WikiAdminUsers p0 ->
            Evergreen.V17.Route.WikiAdminUsers p0

        Evergreen.V16.Route.WikiAdminAudit p0 ->
            Evergreen.V17.Route.WikiAdminAudit p0

        Evergreen.V16.Route.WikiAdminAuditDiff p0 p1 ->
            Evergreen.V17.Route.WikiAdminAuditDiff p0 p1

        Evergreen.V16.Route.NotFound p0 ->
            Evergreen.V17.Route.NotFound p0


migrate_Store_Store : Evergreen.V16.Store.Store -> Evergreen.V17.Store.Store
migrate_Store_Store old =
    { wikiCatalog = old.wikiCatalog
    , wikiDetails = old.wikiDetails |> Dict.map (\k -> migrate_RemoteData_RemoteData identity migrate_Wiki_FrontendDetails)
    , publishedPages = old.publishedPages
    , reviewQueues = old.reviewQueues |> Dict.map (\k -> migrate_RemoteData_RemoteData identity (Result.mapError migrate_Submission_ReviewQueueError >> Result.map (List.map migrate_Submission_ReviewQueueItem)))
    , myPendingSubmissions = old.myPendingSubmissions |> Dict.map (\k -> migrate_RemoteData_RemoteData identity (Result.mapError migrate_Submission_MyPendingSubmissionsError >> Result.map (List.map migrate_Submission_MyPendingSubmissionListItem)))
    , submissionDetails = old.submissionDetails |> Dict.map (\k -> migrate_RemoteData_RemoteData identity (Result.mapError migrate_Submission_DetailsError >> Result.map migrate_Submission_ContributorView))
    , reviewSubmissionDetails = old.reviewSubmissionDetails |> Dict.map (\k -> migrate_RemoteData_RemoteData identity (Result.mapError migrate_SubmissionReviewDetail_ReviewSubmissionDetailError >> Result.map migrate_SubmissionReviewDetail_SubmissionReviewDetail))
    , wikiUsers = old.wikiUsers |> Dict.map (\k -> migrate_RemoteData_RemoteData identity (Result.mapError migrate_WikiAdminUsers_Error >> Result.map (List.map migrate_WikiAdminUsers_ListedUser)))
    , wikiAuditLogs = old.wikiAuditLogs |> Dict.map (\_ -> Dict.map (\k -> migrate_RemoteData_RemoteData identity (Result.mapError migrate_WikiAuditLog_Error >> Result.map (List.map migrate_WikiAuditLog_AuditEvent))))
    }


migrate_SubmissionReviewDetail_ReviewSubmissionDetailError : Evergreen.V16.SubmissionReviewDetail.ReviewSubmissionDetailError -> Evergreen.V17.SubmissionReviewDetail.ReviewSubmissionDetailError
migrate_SubmissionReviewDetail_ReviewSubmissionDetailError old =
    case old of
        Evergreen.V16.SubmissionReviewDetail.ReviewSubmissionDetailNotLoggedIn ->
            Evergreen.V17.SubmissionReviewDetail.ReviewSubmissionDetailNotLoggedIn

        Evergreen.V16.SubmissionReviewDetail.ReviewSubmissionDetailWrongWikiSession ->
            Evergreen.V17.SubmissionReviewDetail.ReviewSubmissionDetailWrongWikiSession

        Evergreen.V16.SubmissionReviewDetail.ReviewSubmissionDetailForbidden ->
            Evergreen.V17.SubmissionReviewDetail.ReviewSubmissionDetailForbidden

        Evergreen.V16.SubmissionReviewDetail.ReviewSubmissionDetailWikiInactive ->
            Evergreen.V17.SubmissionReviewDetail.ReviewSubmissionDetailWikiInactive

        Evergreen.V16.SubmissionReviewDetail.ReviewSubmissionDetailNotFound ->
            Evergreen.V17.SubmissionReviewDetail.ReviewSubmissionDetailNotFound


migrate_SubmissionReviewDetail_SubmissionReviewDetail : Evergreen.V16.SubmissionReviewDetail.SubmissionReviewDetail -> Evergreen.V17.SubmissionReviewDetail.SubmissionReviewDetail
migrate_SubmissionReviewDetail_SubmissionReviewDetail old =
    case old of
        Evergreen.V16.SubmissionReviewDetail.NewPageDiff p0 ->
            Evergreen.V17.SubmissionReviewDetail.NewPageDiff p0

        Evergreen.V16.SubmissionReviewDetail.EditPageDiff p0 ->
            Evergreen.V17.SubmissionReviewDetail.EditPageDiff p0

        Evergreen.V16.SubmissionReviewDetail.DeletePageDiff p0 ->
            Evergreen.V17.SubmissionReviewDetail.DeletePageDiff p0


migrate_Submission_ApproveSubmissionError : Evergreen.V16.Submission.ApproveSubmissionError -> Evergreen.V17.Submission.ApproveSubmissionError
migrate_Submission_ApproveSubmissionError old =
    case old of
        Evergreen.V16.Submission.ApproveNotLoggedIn ->
            Evergreen.V17.Submission.ApproveNotLoggedIn

        Evergreen.V16.Submission.ApproveWrongWikiSession ->
            Evergreen.V17.Submission.ApproveWrongWikiSession

        Evergreen.V16.Submission.ApproveForbidden ->
            Evergreen.V17.Submission.ApproveForbidden

        Evergreen.V16.Submission.ApproveWikiNotFound ->
            Evergreen.V17.Submission.ApproveWikiNotFound

        Evergreen.V16.Submission.ApproveWikiInactive ->
            Evergreen.V17.Submission.ApproveWikiInactive

        Evergreen.V16.Submission.ApproveSubmissionNotFound ->
            Evergreen.V17.Submission.ApproveSubmissionNotFound

        Evergreen.V16.Submission.ApproveNotPending ->
            Evergreen.V17.Submission.ApproveNotPending

        Evergreen.V16.Submission.ApproveNewPageSlugTaken ->
            Evergreen.V17.Submission.ApproveNewPageSlugTaken

        Evergreen.V16.Submission.ApproveEditTargetNotPublished ->
            Evergreen.V17.Submission.ApproveEditTargetNotPublished

        Evergreen.V16.Submission.ApproveDeleteTargetNotPublished ->
            Evergreen.V17.Submission.ApproveDeleteTargetNotPublished


migrate_Submission_ContributorSubmissionKind : Evergreen.V16.Submission.ContributorSubmissionKind -> Evergreen.V17.Submission.ContributorSubmissionKind
migrate_Submission_ContributorSubmissionKind old =
    case old of
        Evergreen.V16.Submission.ContributorKindNewPage ->
            Evergreen.V17.Submission.ContributorKindNewPage

        Evergreen.V16.Submission.ContributorKindEditPage ->
            Evergreen.V17.Submission.ContributorKindEditPage

        Evergreen.V16.Submission.ContributorKindDeletePage ->
            Evergreen.V17.Submission.ContributorKindDeletePage


migrate_Submission_ContributorView : Evergreen.V16.Submission.ContributorView -> Evergreen.V17.Submission.ContributorView
migrate_Submission_ContributorView old =
    { id = old.id |> migrate_Submission_Id
    , status = old.status |> migrate_Submission_Status
    , kindSummary = old.kindSummary
    , contributionKind = old.contributionKind |> migrate_Submission_ContributorSubmissionKind
    , reviewerNote = old.reviewerNote
    , conflictContext = old.conflictContext
    , compareOriginalMarkdown = old.compareOriginalMarkdown
    , compareNewMarkdown = old.compareNewMarkdown
    , maybeNewPageSlug = old.maybeNewPageSlug
    , maybeEditPageSlug = old.maybeEditPageSlug
    }


migrate_Submission_DeleteMySubmissionError : Evergreen.V16.Submission.DeleteMySubmissionError -> Evergreen.V17.Submission.DeleteMySubmissionError
migrate_Submission_DeleteMySubmissionError old =
    case old of
        Evergreen.V16.Submission.DeleteMySubmissionNotLoggedIn ->
            Evergreen.V17.Submission.DeleteMySubmissionNotLoggedIn

        Evergreen.V16.Submission.DeleteMySubmissionWrongWikiSession ->
            Evergreen.V17.Submission.DeleteMySubmissionWrongWikiSession

        Evergreen.V16.Submission.DeleteMySubmissionWikiNotFound ->
            Evergreen.V17.Submission.DeleteMySubmissionWikiNotFound

        Evergreen.V16.Submission.DeleteMySubmissionWikiInactive ->
            Evergreen.V17.Submission.DeleteMySubmissionWikiInactive

        Evergreen.V16.Submission.DeleteMySubmissionApproved ->
            Evergreen.V17.Submission.DeleteMySubmissionApproved

        Evergreen.V16.Submission.DeleteMySubmissionNotFound ->
            Evergreen.V17.Submission.DeleteMySubmissionNotFound

        Evergreen.V16.Submission.DeleteMySubmissionForbidden ->
            Evergreen.V17.Submission.DeleteMySubmissionForbidden


migrate_Submission_DeletePageBody : Evergreen.V16.Submission.DeletePageBody -> Evergreen.V17.Submission.DeletePageBody
migrate_Submission_DeletePageBody old =
    old


migrate_Submission_DeletePublishedPageImmediatelyError : Evergreen.V16.Submission.DeletePublishedPageImmediatelyError -> Evergreen.V17.Submission.DeletePublishedPageImmediatelyError
migrate_Submission_DeletePublishedPageImmediatelyError old =
    case old of
        Evergreen.V16.Submission.DeletePublishedPageImmediatelyPrecondition p0 ->
            Evergreen.V17.Submission.DeletePublishedPageImmediatelyPrecondition (p0 |> migrate_Submission_PageDeletionPreconditionError)

        Evergreen.V16.Submission.DeletePublishedPageImmediatelyForbiddenUntrustedContributor ->
            Evergreen.V17.Submission.DeletePublishedPageImmediatelyForbiddenUntrustedContributor


migrate_Submission_DeleteReasonError : Evergreen.V16.Submission.DeleteReasonError -> Evergreen.V17.Submission.DeleteReasonError
migrate_Submission_DeleteReasonError old =
    case old of
        Evergreen.V16.Submission.ReasonRequired ->
            Evergreen.V17.Submission.ReasonRequired

        Evergreen.V16.Submission.ReasonTooLong ->
            Evergreen.V17.Submission.ReasonTooLong


migrate_Submission_DetailsError : Evergreen.V16.Submission.DetailsError -> Evergreen.V17.Submission.DetailsError
migrate_Submission_DetailsError old =
    case old of
        Evergreen.V16.Submission.DetailsNotLoggedIn ->
            Evergreen.V17.Submission.DetailsNotLoggedIn

        Evergreen.V16.Submission.DetailsWrongWikiSession ->
            Evergreen.V17.Submission.DetailsWrongWikiSession

        Evergreen.V16.Submission.DetailsWikiInactive ->
            Evergreen.V17.Submission.DetailsWikiInactive

        Evergreen.V16.Submission.DetailsNotFound ->
            Evergreen.V17.Submission.DetailsNotFound

        Evergreen.V16.Submission.DetailsForbidden ->
            Evergreen.V17.Submission.DetailsForbidden


migrate_Submission_EditPageBody : Evergreen.V16.Submission.EditPageBody -> Evergreen.V17.Submission.EditPageBody
migrate_Submission_EditPageBody old =
    old


migrate_Submission_EditSubmitSuccess : Evergreen.V16.Submission.EditSubmitSuccess -> Evergreen.V17.Submission.EditSubmitSuccess
migrate_Submission_EditSubmitSuccess old =
    case old of
        Evergreen.V16.Submission.EditPublishedImmediately ->
            Evergreen.V17.Submission.EditPublishedImmediately

        Evergreen.V16.Submission.EditSubmittedForReview p0 ->
            Evergreen.V17.Submission.EditSubmittedForReview (p0 |> migrate_Submission_Id)


migrate_Submission_Id : Evergreen.V16.Submission.Id -> Evergreen.V17.Submission.Id
migrate_Submission_Id old =
    case old of
        Evergreen.V16.Submission.Id p0 ->
            Evergreen.V17.Submission.Id p0


migrate_Submission_Kind : Evergreen.V16.Submission.Kind -> Evergreen.V17.Submission.Kind
migrate_Submission_Kind old =
    case old of
        Evergreen.V16.Submission.NewPage p0 ->
            Evergreen.V17.Submission.NewPage (p0 |> migrate_Submission_NewPageBody)

        Evergreen.V16.Submission.EditPage p0 ->
            Evergreen.V17.Submission.EditPage (p0 |> migrate_Submission_EditPageBody)

        Evergreen.V16.Submission.DeletePage p0 ->
            Evergreen.V17.Submission.DeletePage (p0 |> migrate_Submission_DeletePageBody)


migrate_Submission_MyPendingSubmissionListItem : Evergreen.V16.Submission.MyPendingSubmissionListItem -> Evergreen.V17.Submission.MyPendingSubmissionListItem
migrate_Submission_MyPendingSubmissionListItem old =
    { id = old.id |> migrate_Submission_Id
    , status = old.status |> migrate_Submission_Status
    , statusLabel = old.statusLabel
    , kindLabel = old.kindLabel
    , maybePageSlug = old.maybePageSlug
    }


migrate_Submission_MyPendingSubmissionsError : Evergreen.V16.Submission.MyPendingSubmissionsError -> Evergreen.V17.Submission.MyPendingSubmissionsError
migrate_Submission_MyPendingSubmissionsError old =
    case old of
        Evergreen.V16.Submission.MyPendingSubmissionsNotLoggedIn ->
            Evergreen.V17.Submission.MyPendingSubmissionsNotLoggedIn

        Evergreen.V16.Submission.MyPendingSubmissionsWrongWikiSession ->
            Evergreen.V17.Submission.MyPendingSubmissionsWrongWikiSession

        Evergreen.V16.Submission.MyPendingSubmissionsWikiInactive ->
            Evergreen.V17.Submission.MyPendingSubmissionsWikiInactive

        Evergreen.V16.Submission.MyPendingSubmissionsForbiddenTrustedModerator ->
            Evergreen.V17.Submission.MyPendingSubmissionsForbiddenTrustedModerator


migrate_Submission_NewPageBody : Evergreen.V16.Submission.NewPageBody -> Evergreen.V17.Submission.NewPageBody
migrate_Submission_NewPageBody old =
    old


migrate_Submission_NewPageSubmitSuccess : Evergreen.V16.Submission.NewPageSubmitSuccess -> Evergreen.V17.Submission.NewPageSubmitSuccess
migrate_Submission_NewPageSubmitSuccess old =
    case old of
        Evergreen.V16.Submission.NewPagePublishedImmediately ->
            Evergreen.V17.Submission.NewPagePublishedImmediately

        Evergreen.V16.Submission.NewPageSubmittedForReview p0 ->
            Evergreen.V17.Submission.NewPageSubmittedForReview (p0 |> migrate_Submission_Id)


migrate_Submission_PageDeleteFormError : Evergreen.V16.Submission.PageDeleteFormError -> Evergreen.V17.Submission.PageDeleteFormError
migrate_Submission_PageDeleteFormError old =
    case old of
        Evergreen.V16.Submission.PageDeleteRequestFailed p0 ->
            Evergreen.V17.Submission.PageDeleteRequestFailed (p0 |> migrate_Submission_RequestPublishedPageDeletionError)

        Evergreen.V16.Submission.PageDeleteImmediateFailed p0 ->
            Evergreen.V17.Submission.PageDeleteImmediateFailed (p0 |> migrate_Submission_DeletePublishedPageImmediatelyError)


migrate_Submission_PageDeleteFormSuccess : Evergreen.V16.Submission.PageDeleteFormSuccess -> Evergreen.V17.Submission.PageDeleteFormSuccess
migrate_Submission_PageDeleteFormSuccess old =
    case old of
        Evergreen.V16.Submission.DeletePublishedImmediately ->
            Evergreen.V17.Submission.DeletePublishedImmediately

        Evergreen.V16.Submission.DeleteSubmittedForReview p0 ->
            Evergreen.V17.Submission.DeleteSubmittedForReview (p0 |> migrate_Submission_Id)


migrate_Submission_PageDeletionPreconditionError : Evergreen.V16.Submission.PageDeletionPreconditionError -> Evergreen.V17.Submission.PageDeletionPreconditionError
migrate_Submission_PageDeletionPreconditionError old =
    case old of
        Evergreen.V16.Submission.PageDeletionNotLoggedIn ->
            Evergreen.V17.Submission.PageDeletionNotLoggedIn

        Evergreen.V16.Submission.PageDeletionWrongWikiSession ->
            Evergreen.V17.Submission.PageDeletionWrongWikiSession

        Evergreen.V16.Submission.PageDeletionWikiNotFound ->
            Evergreen.V17.Submission.PageDeletionWikiNotFound

        Evergreen.V16.Submission.PageDeletionWikiInactive ->
            Evergreen.V17.Submission.PageDeletionWikiInactive

        Evergreen.V16.Submission.PageDeletionValidation p0 ->
            Evergreen.V17.Submission.PageDeletionValidation (p0 |> migrate_Submission_DeleteReasonError)

        Evergreen.V16.Submission.PageDeletionTargetNotPublished ->
            Evergreen.V17.Submission.PageDeletionTargetNotPublished


migrate_Submission_RejectReasonError : Evergreen.V16.Submission.RejectReasonError -> Evergreen.V17.Submission.RejectReasonError
migrate_Submission_RejectReasonError old =
    case old of
        Evergreen.V16.Submission.RejectReasonEmpty ->
            Evergreen.V17.Submission.RejectReasonEmpty

        Evergreen.V16.Submission.RejectReasonTooLong ->
            Evergreen.V17.Submission.RejectReasonTooLong


migrate_Submission_RejectSubmissionError : Evergreen.V16.Submission.RejectSubmissionError -> Evergreen.V17.Submission.RejectSubmissionError
migrate_Submission_RejectSubmissionError old =
    case old of
        Evergreen.V16.Submission.RejectNotLoggedIn ->
            Evergreen.V17.Submission.RejectNotLoggedIn

        Evergreen.V16.Submission.RejectWrongWikiSession ->
            Evergreen.V17.Submission.RejectWrongWikiSession

        Evergreen.V16.Submission.RejectForbidden ->
            Evergreen.V17.Submission.RejectForbidden

        Evergreen.V16.Submission.RejectWikiNotFound ->
            Evergreen.V17.Submission.RejectWikiNotFound

        Evergreen.V16.Submission.RejectWikiInactive ->
            Evergreen.V17.Submission.RejectWikiInactive

        Evergreen.V16.Submission.RejectSubmissionNotFound ->
            Evergreen.V17.Submission.RejectSubmissionNotFound

        Evergreen.V16.Submission.RejectNotPending ->
            Evergreen.V17.Submission.RejectNotPending

        Evergreen.V16.Submission.RejectReasonInvalid p0 ->
            Evergreen.V17.Submission.RejectReasonInvalid (p0 |> migrate_Submission_RejectReasonError)


migrate_Submission_RequestChangesSubmissionError : Evergreen.V16.Submission.RequestChangesSubmissionError -> Evergreen.V17.Submission.RequestChangesSubmissionError
migrate_Submission_RequestChangesSubmissionError old =
    case old of
        Evergreen.V16.Submission.RequestChangesNotLoggedIn ->
            Evergreen.V17.Submission.RequestChangesNotLoggedIn

        Evergreen.V16.Submission.RequestChangesWrongWikiSession ->
            Evergreen.V17.Submission.RequestChangesWrongWikiSession

        Evergreen.V16.Submission.RequestChangesForbidden ->
            Evergreen.V17.Submission.RequestChangesForbidden

        Evergreen.V16.Submission.RequestChangesWikiNotFound ->
            Evergreen.V17.Submission.RequestChangesWikiNotFound

        Evergreen.V16.Submission.RequestChangesWikiInactive ->
            Evergreen.V17.Submission.RequestChangesWikiInactive

        Evergreen.V16.Submission.RequestChangesSubmissionNotFound ->
            Evergreen.V17.Submission.RequestChangesSubmissionNotFound

        Evergreen.V16.Submission.RequestChangesNotPending ->
            Evergreen.V17.Submission.RequestChangesNotPending

        Evergreen.V16.Submission.RequestChangesGuidanceInvalid p0 ->
            Evergreen.V17.Submission.RequestChangesGuidanceInvalid (p0 |> migrate_Submission_RejectReasonError)


migrate_Submission_RequestPublishedPageDeletionError : Evergreen.V16.Submission.RequestPublishedPageDeletionError -> Evergreen.V17.Submission.RequestPublishedPageDeletionError
migrate_Submission_RequestPublishedPageDeletionError old =
    case old of
        Evergreen.V16.Submission.RequestPublishedPageDeletionPrecondition p0 ->
            Evergreen.V17.Submission.RequestPublishedPageDeletionPrecondition (p0 |> migrate_Submission_PageDeletionPreconditionError)

        Evergreen.V16.Submission.RequestPublishedPageDeletionForbiddenTrustedModerator ->
            Evergreen.V17.Submission.RequestPublishedPageDeletionForbiddenTrustedModerator

        Evergreen.V16.Submission.RequestPublishedPageDeletionSubmitDraftStepFailed p0 ->
            Evergreen.V17.Submission.RequestPublishedPageDeletionSubmitDraftStepFailed (p0 |> migrate_Submission_SubmitDraftForReviewError)


migrate_Submission_ReviewQueueError : Evergreen.V16.Submission.ReviewQueueError -> Evergreen.V17.Submission.ReviewQueueError
migrate_Submission_ReviewQueueError old =
    case old of
        Evergreen.V16.Submission.ReviewQueueNotLoggedIn ->
            Evergreen.V17.Submission.ReviewQueueNotLoggedIn

        Evergreen.V16.Submission.ReviewQueueWrongWikiSession ->
            Evergreen.V17.Submission.ReviewQueueWrongWikiSession

        Evergreen.V16.Submission.ReviewQueueForbidden ->
            Evergreen.V17.Submission.ReviewQueueForbidden

        Evergreen.V16.Submission.ReviewQueueWikiInactive ->
            Evergreen.V17.Submission.ReviewQueueWikiInactive


migrate_Submission_ReviewQueueItem : Evergreen.V16.Submission.ReviewQueueItem -> Evergreen.V17.Submission.ReviewQueueItem
migrate_Submission_ReviewQueueItem old =
    { id = old.id |> migrate_Submission_Id
    , kindLabel = old.kindLabel
    , authorDisplay = old.authorDisplay
    , maybePageSlug = old.maybePageSlug
    }


migrate_Submission_SaveNewPageDraftError : Evergreen.V16.Submission.SaveNewPageDraftError -> Evergreen.V17.Submission.SaveNewPageDraftError
migrate_Submission_SaveNewPageDraftError old =
    case old of
        Evergreen.V16.Submission.SaveNewPageDraftNotLoggedIn ->
            Evergreen.V17.Submission.SaveNewPageDraftNotLoggedIn

        Evergreen.V16.Submission.SaveNewPageDraftWrongWikiSession ->
            Evergreen.V17.Submission.SaveNewPageDraftWrongWikiSession

        Evergreen.V16.Submission.SaveNewPageDraftValidation p0 ->
            Evergreen.V17.Submission.SaveNewPageDraftValidation (p0 |> migrate_Submission_ValidationError)

        Evergreen.V16.Submission.SaveNewPageDraftSlugReserved ->
            Evergreen.V17.Submission.SaveNewPageDraftSlugReserved

        Evergreen.V16.Submission.SaveNewPageDraftNotFound ->
            Evergreen.V17.Submission.SaveNewPageDraftNotFound

        Evergreen.V16.Submission.SaveNewPageDraftForbidden ->
            Evergreen.V17.Submission.SaveNewPageDraftForbidden

        Evergreen.V16.Submission.SaveNewPageDraftWikiNotFound ->
            Evergreen.V17.Submission.SaveNewPageDraftWikiNotFound

        Evergreen.V16.Submission.SaveNewPageDraftWikiInactive ->
            Evergreen.V17.Submission.SaveNewPageDraftWikiInactive


migrate_Submission_SavePageDeleteDraftError : Evergreen.V16.Submission.SavePageDeleteDraftError -> Evergreen.V17.Submission.SavePageDeleteDraftError
migrate_Submission_SavePageDeleteDraftError old =
    case old of
        Evergreen.V16.Submission.SavePageDeleteDraftNotLoggedIn ->
            Evergreen.V17.Submission.SavePageDeleteDraftNotLoggedIn

        Evergreen.V16.Submission.SavePageDeleteDraftWrongWikiSession ->
            Evergreen.V17.Submission.SavePageDeleteDraftWrongWikiSession

        Evergreen.V16.Submission.SavePageDeleteDraftReasonInvalid p0 ->
            Evergreen.V17.Submission.SavePageDeleteDraftReasonInvalid (p0 |> migrate_Submission_DeleteReasonError)

        Evergreen.V16.Submission.SavePageDeleteDraftTargetNotPublished ->
            Evergreen.V17.Submission.SavePageDeleteDraftTargetNotPublished

        Evergreen.V16.Submission.SavePageDeleteDraftNotFound ->
            Evergreen.V17.Submission.SavePageDeleteDraftNotFound

        Evergreen.V16.Submission.SavePageDeleteDraftForbidden ->
            Evergreen.V17.Submission.SavePageDeleteDraftForbidden

        Evergreen.V16.Submission.SavePageDeleteDraftWikiNotFound ->
            Evergreen.V17.Submission.SavePageDeleteDraftWikiNotFound

        Evergreen.V16.Submission.SavePageDeleteDraftWikiInactive ->
            Evergreen.V17.Submission.SavePageDeleteDraftWikiInactive

        Evergreen.V16.Submission.SavePageDeleteDraftForbiddenTrustedModerator ->
            Evergreen.V17.Submission.SavePageDeleteDraftForbiddenTrustedModerator


migrate_Submission_SavePageEditDraftError : Evergreen.V16.Submission.SavePageEditDraftError -> Evergreen.V17.Submission.SavePageEditDraftError
migrate_Submission_SavePageEditDraftError old =
    case old of
        Evergreen.V16.Submission.SavePageEditDraftNotLoggedIn ->
            Evergreen.V17.Submission.SavePageEditDraftNotLoggedIn

        Evergreen.V16.Submission.SavePageEditDraftWrongWikiSession ->
            Evergreen.V17.Submission.SavePageEditDraftWrongWikiSession

        Evergreen.V16.Submission.SavePageEditDraftValidation p0 ->
            Evergreen.V17.Submission.SavePageEditDraftValidation (p0 |> migrate_Submission_ValidationError)

        Evergreen.V16.Submission.SavePageEditDraftTargetNotPublished ->
            Evergreen.V17.Submission.SavePageEditDraftTargetNotPublished

        Evergreen.V16.Submission.SavePageEditDraftAlreadyPendingEdit ->
            Evergreen.V17.Submission.SavePageEditDraftAlreadyPendingEdit

        Evergreen.V16.Submission.SavePageEditDraftNotFound ->
            Evergreen.V17.Submission.SavePageEditDraftNotFound

        Evergreen.V16.Submission.SavePageEditDraftForbidden ->
            Evergreen.V17.Submission.SavePageEditDraftForbidden

        Evergreen.V16.Submission.SavePageEditDraftWikiNotFound ->
            Evergreen.V17.Submission.SavePageEditDraftWikiNotFound

        Evergreen.V16.Submission.SavePageEditDraftWikiInactive ->
            Evergreen.V17.Submission.SavePageEditDraftWikiInactive


migrate_Submission_Status : Evergreen.V16.Submission.Status -> Evergreen.V17.Submission.Status
migrate_Submission_Status old =
    case old of
        Evergreen.V16.Submission.Draft ->
            Evergreen.V17.Submission.Draft

        Evergreen.V16.Submission.Pending ->
            Evergreen.V17.Submission.Pending

        Evergreen.V16.Submission.Approved ->
            Evergreen.V17.Submission.Approved

        Evergreen.V16.Submission.Rejected ->
            Evergreen.V17.Submission.Rejected

        Evergreen.V16.Submission.NeedsRevision ->
            Evergreen.V17.Submission.NeedsRevision


migrate_Submission_Submission : Evergreen.V16.Submission.Submission -> Evergreen.V17.Submission.Submission
migrate_Submission_Submission old =
    { id = old.id |> migrate_Submission_Id
    , wikiSlug = old.wikiSlug
    , authorId = old.authorId |> migrate_ContributorAccount_Id
    , kind = old.kind |> migrate_Submission_Kind
    , status = old.status |> migrate_Submission_Status
    , reviewerNote = old.reviewerNote
    }


migrate_Submission_SubmitDraftForReviewError : Evergreen.V16.Submission.SubmitDraftForReviewError -> Evergreen.V17.Submission.SubmitDraftForReviewError
migrate_Submission_SubmitDraftForReviewError old =
    case old of
        Evergreen.V16.Submission.SubmitDraftForReviewNotLoggedIn ->
            Evergreen.V17.Submission.SubmitDraftForReviewNotLoggedIn

        Evergreen.V16.Submission.SubmitDraftForReviewWrongWikiSession ->
            Evergreen.V17.Submission.SubmitDraftForReviewWrongWikiSession

        Evergreen.V16.Submission.SubmitDraftForReviewWikiNotFound ->
            Evergreen.V17.Submission.SubmitDraftForReviewWikiNotFound

        Evergreen.V16.Submission.SubmitDraftForReviewWikiInactive ->
            Evergreen.V17.Submission.SubmitDraftForReviewWikiInactive

        Evergreen.V16.Submission.SubmitDraftForReviewNotDraft ->
            Evergreen.V17.Submission.SubmitDraftForReviewNotDraft

        Evergreen.V16.Submission.SubmitDraftForReviewValidation p0 ->
            Evergreen.V17.Submission.SubmitDraftForReviewValidation (p0 |> migrate_Submission_ValidationError)

        Evergreen.V16.Submission.SubmitDraftForReviewSlugInUse ->
            Evergreen.V17.Submission.SubmitDraftForReviewSlugInUse

        Evergreen.V16.Submission.SubmitDraftForReviewPageExists ->
            Evergreen.V17.Submission.SubmitDraftForReviewPageExists

        Evergreen.V16.Submission.SubmitDraftForReviewEditTargetNotPublished ->
            Evergreen.V17.Submission.SubmitDraftForReviewEditTargetNotPublished

        Evergreen.V16.Submission.SubmitDraftForReviewEditAlreadyPending ->
            Evergreen.V17.Submission.SubmitDraftForReviewEditAlreadyPending

        Evergreen.V16.Submission.SubmitDraftForReviewDeleteTargetNotPublished ->
            Evergreen.V17.Submission.SubmitDraftForReviewDeleteTargetNotPublished

        Evergreen.V16.Submission.SubmitDraftForReviewDeleteReasonInvalid p0 ->
            Evergreen.V17.Submission.SubmitDraftForReviewDeleteReasonInvalid (p0 |> migrate_Submission_DeleteReasonError)

        Evergreen.V16.Submission.SubmitDraftForReviewNotFound ->
            Evergreen.V17.Submission.SubmitDraftForReviewNotFound

        Evergreen.V16.Submission.SubmitDraftForReviewForbidden ->
            Evergreen.V17.Submission.SubmitDraftForReviewForbidden

        Evergreen.V16.Submission.SubmitDraftForReviewDeleteForbiddenTrustedModerator ->
            Evergreen.V17.Submission.SubmitDraftForReviewDeleteForbiddenTrustedModerator


migrate_Submission_SubmitNewPageError : Evergreen.V16.Submission.SubmitNewPageError -> Evergreen.V17.Submission.SubmitNewPageError
migrate_Submission_SubmitNewPageError old =
    case old of
        Evergreen.V16.Submission.NotLoggedIn ->
            Evergreen.V17.Submission.NotLoggedIn

        Evergreen.V16.Submission.WrongWikiSession ->
            Evergreen.V17.Submission.WrongWikiSession

        Evergreen.V16.Submission.WikiNotFound ->
            Evergreen.V17.Submission.WikiNotFound

        Evergreen.V16.Submission.WikiInactive ->
            Evergreen.V17.Submission.WikiInactive

        Evergreen.V16.Submission.Validation p0 ->
            Evergreen.V17.Submission.Validation (p0 |> migrate_Submission_ValidationError)

        Evergreen.V16.Submission.SlugAlreadyInUse ->
            Evergreen.V17.Submission.SlugAlreadyInUse


migrate_Submission_SubmitPageEditError : Evergreen.V16.Submission.SubmitPageEditError -> Evergreen.V17.Submission.SubmitPageEditError
migrate_Submission_SubmitPageEditError old =
    case old of
        Evergreen.V16.Submission.EditNotLoggedIn ->
            Evergreen.V17.Submission.EditNotLoggedIn

        Evergreen.V16.Submission.EditWrongWikiSession ->
            Evergreen.V17.Submission.EditWrongWikiSession

        Evergreen.V16.Submission.EditWikiNotFound ->
            Evergreen.V17.Submission.EditWikiNotFound

        Evergreen.V16.Submission.EditWikiInactive ->
            Evergreen.V17.Submission.EditWikiInactive

        Evergreen.V16.Submission.EditValidation p0 ->
            Evergreen.V17.Submission.EditValidation (p0 |> migrate_Submission_ValidationError)

        Evergreen.V16.Submission.EditTargetPageNotPublished ->
            Evergreen.V17.Submission.EditTargetPageNotPublished

        Evergreen.V16.Submission.EditAlreadyPendingForAuthor ->
            Evergreen.V17.Submission.EditAlreadyPendingForAuthor


migrate_Submission_ValidationError : Evergreen.V16.Submission.ValidationError -> Evergreen.V17.Submission.ValidationError
migrate_Submission_ValidationError old =
    case old of
        Evergreen.V16.Submission.SlugEmpty ->
            Evergreen.V17.Submission.SlugEmpty

        Evergreen.V16.Submission.SlugTooLong ->
            Evergreen.V17.Submission.SlugTooLong

        Evergreen.V16.Submission.SlugInvalidChars ->
            Evergreen.V17.Submission.SlugInvalidChars

        Evergreen.V16.Submission.BodyEmpty ->
            Evergreen.V17.Submission.BodyEmpty


migrate_Submission_WithdrawSubmissionError : Evergreen.V16.Submission.WithdrawSubmissionError -> Evergreen.V17.Submission.WithdrawSubmissionError
migrate_Submission_WithdrawSubmissionError old =
    case old of
        Evergreen.V16.Submission.WithdrawSubmissionNotLoggedIn ->
            Evergreen.V17.Submission.WithdrawSubmissionNotLoggedIn

        Evergreen.V16.Submission.WithdrawSubmissionWrongWikiSession ->
            Evergreen.V17.Submission.WithdrawSubmissionWrongWikiSession

        Evergreen.V16.Submission.WithdrawSubmissionWikiNotFound ->
            Evergreen.V17.Submission.WithdrawSubmissionWikiNotFound

        Evergreen.V16.Submission.WithdrawSubmissionWikiInactive ->
            Evergreen.V17.Submission.WithdrawSubmissionWikiInactive

        Evergreen.V16.Submission.WithdrawSubmissionNotPendingOrNeedsRevision ->
            Evergreen.V17.Submission.WithdrawSubmissionNotPendingOrNeedsRevision

        Evergreen.V16.Submission.WithdrawSubmissionNotFound ->
            Evergreen.V17.Submission.WithdrawSubmissionNotFound

        Evergreen.V16.Submission.WithdrawSubmissionForbidden ->
            Evergreen.V17.Submission.WithdrawSubmissionForbidden


migrate_Types_HostAdminCreateWikiDraft : Evergreen.V16.Types.HostAdminCreateWikiDraft -> Evergreen.V17.Types.HostAdminCreateWikiDraft
migrate_Types_HostAdminCreateWikiDraft old =
    { slug = old.slug
    , name = old.name
    , initialAdminUsername = old.initialAdminUsername
    , initialAdminPassword = old.initialAdminPassword
    , inFlight = old.inFlight
    , lastResult = old.lastResult |> Maybe.map (Result.mapError migrate_HostAdmin_CreateHostedWikiError >> Result.map migrate_Wiki_CatalogEntry)
    }


migrate_Types_HostAdminLoginDraft : Evergreen.V16.Types.HostAdminLoginDraft -> Evergreen.V17.Types.HostAdminLoginDraft
migrate_Types_HostAdminLoginDraft old =
    { password = old.password
    , inFlight = old.inFlight
    , lastResult = old.lastResult |> Maybe.map (Result.mapError migrate_HostAdmin_LoginError)
    }


migrate_Types_HostAdminWikiDetailDraft : Evergreen.V16.Types.HostAdminWikiDetailDraft -> Evergreen.V17.Types.HostAdminWikiDetailDraft
migrate_Types_HostAdminWikiDetailDraft old =
    { wikiSlug = old.wikiSlug
    , load = old.load |> migrate_RemoteData_RemoteData identity (Result.mapError migrate_HostAdmin_HostWikiDetailError >> Result.map migrate_Wiki_CatalogEntry)
    , slugDraft = old.slugDraft
    , nameDraft = old.nameDraft
    , summaryDraft = old.summaryDraft
    , saveInFlight = old.saveInFlight
    , lastSaveResult = old.lastSaveResult |> Maybe.map (Result.mapError migrate_HostAdmin_UpdateHostedWikiMetadataError)
    , lifecycleInFlight = old.lifecycleInFlight
    , lastLifecycleResult = old.lastLifecycleResult |> Maybe.map (Result.mapError migrate_HostAdmin_WikiLifecycleError)
    , deleteConfirmDraft = old.deleteConfirmDraft
    , deleteInFlight = old.deleteInFlight
    , lastDeleteResult = old.lastDeleteResult |> Maybe.map (Result.mapError migrate_HostAdmin_DeleteHostedWikiError)
    }


migrate_Types_LoginDraft : Evergreen.V16.Types.LoginDraft -> Evergreen.V17.Types.LoginDraft
migrate_Types_LoginDraft old =
    { username = old.username
    , password = old.password
    , inFlight = old.inFlight
    , lastResult = old.lastResult |> Maybe.map (Result.mapError migrate_ContributorAccount_LoginContributorError)
    }


migrate_Types_NewPageSubmitDraft : Evergreen.V16.Types.NewPageSubmitDraft -> Evergreen.V17.Types.NewPageSubmitDraft
migrate_Types_NewPageSubmitDraft old =
    { pageSlug = old.pageSlug
    , pageSlugLockedFromQuery = old.pageSlugLockedFromQuery
    , markdownBody = old.markdownBody
    , tagsInput = old.tagsInput
    , maybeSavedDraftId = old.maybeSavedDraftId
    , inFlight = old.inFlight
    , saveDraftInFlight = old.saveDraftInFlight
    , pendingSubmitAfterSave = old.pendingSubmitAfterSave
    , lastResult = old.lastResult |> Maybe.map (Result.mapError migrate_Submission_SubmitNewPageError >> Result.map migrate_Submission_NewPageSubmitSuccess)
    , lastSaveDraftResult = old.lastSaveDraftResult |> Maybe.map (Result.mapError migrate_Submission_SaveNewPageDraftError >> Result.map migrate_Submission_Id)
    }


migrate_Types_PageDeleteSubmitDraft : Evergreen.V16.Types.PageDeleteSubmitDraft -> Evergreen.V17.Types.PageDeleteSubmitDraft
migrate_Types_PageDeleteSubmitDraft old =
    { reasonText = old.reasonText
    , maybeSavedDraftId = old.maybeSavedDraftId
    , inFlight = old.inFlight
    , saveDraftInFlight = old.saveDraftInFlight
    , pendingSubmitAfterSave = old.pendingSubmitAfterSave
    , lastResult = old.lastResult |> Maybe.map (Result.mapError migrate_Submission_PageDeleteFormError >> Result.map migrate_Submission_PageDeleteFormSuccess)
    , lastSaveDraftResult = old.lastSaveDraftResult |> Maybe.map (Result.mapError migrate_Submission_SavePageDeleteDraftError >> Result.map migrate_Submission_Id)
    }


migrate_Types_PageEditSubmitDraft : Evergreen.V16.Types.PageEditSubmitDraft -> Evergreen.V17.Types.PageEditSubmitDraft
migrate_Types_PageEditSubmitDraft old =
    { markdownBody = old.markdownBody
    , tagsInput = old.tagsInput
    , publishedRowCollapsed = old.publishedRowCollapsed
    , maybeSavedDraftId = old.maybeSavedDraftId
    , inFlight = old.inFlight
    , saveDraftInFlight = old.saveDraftInFlight
    , pendingSubmitAfterSave = old.pendingSubmitAfterSave
    , lastResult = old.lastResult |> Maybe.map (Result.mapError migrate_Submission_SubmitPageEditError >> Result.map migrate_Submission_EditSubmitSuccess)
    , lastSaveDraftResult = old.lastSaveDraftResult |> Maybe.map (Result.mapError migrate_Submission_SavePageEditDraftError >> Result.map migrate_Submission_Id)
    }


migrate_Types_RegisterDraft : Evergreen.V16.Types.RegisterDraft -> Evergreen.V17.Types.RegisterDraft
migrate_Types_RegisterDraft old =
    { username = old.username
    , password = old.password
    , inFlight = old.inFlight
    , lastResult = old.lastResult |> Maybe.map (Result.mapError migrate_ContributorAccount_RegisterContributorError)
    }


migrate_Types_ReviewApproveDraft : Evergreen.V16.Types.ReviewApproveDraft -> Evergreen.V17.Types.ReviewApproveDraft
migrate_Types_ReviewApproveDraft old =
    { inFlight = old.inFlight
    , lastResult = old.lastResult |> Maybe.map (Result.mapError migrate_Submission_ApproveSubmissionError)
    }


migrate_Types_ReviewDecision : Evergreen.V16.Types.ReviewDecision -> Evergreen.V17.Types.ReviewDecision
migrate_Types_ReviewDecision old =
    case old of
        Evergreen.V16.Types.ReviewDecisionApprove ->
            Evergreen.V17.Types.ReviewDecisionApprove

        Evergreen.V16.Types.ReviewDecisionRequestChanges ->
            Evergreen.V17.Types.ReviewDecisionRequestChanges

        Evergreen.V16.Types.ReviewDecisionReject ->
            Evergreen.V17.Types.ReviewDecisionReject


migrate_Types_ReviewRejectDraft : Evergreen.V16.Types.ReviewRejectDraft -> Evergreen.V17.Types.ReviewRejectDraft
migrate_Types_ReviewRejectDraft old =
    { reasonText = old.reasonText
    , inFlight = old.inFlight
    , lastResult = old.lastResult |> Maybe.map (Result.mapError migrate_Submission_RejectSubmissionError)
    }


migrate_Types_ReviewRequestChangesDraft : Evergreen.V16.Types.ReviewRequestChangesDraft -> Evergreen.V17.Types.ReviewRequestChangesDraft
migrate_Types_ReviewRequestChangesDraft old =
    { guidanceText = old.guidanceText
    , inFlight = old.inFlight
    , lastResult = old.lastResult |> Maybe.map (Result.mapError migrate_Submission_RequestChangesSubmissionError)
    }


migrate_Types_SubmissionDetailEditDraft : Evergreen.V16.Types.SubmissionDetailEditDraft -> Evergreen.V17.Types.SubmissionDetailEditDraft
migrate_Types_SubmissionDetailEditDraft old =
    old


migrate_Types_ToFrontend : Evergreen.V16.Types.ToFrontend -> Evergreen.V17.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V16.Types.WikiCatalogResponse p0 ->
            Evergreen.V17.Types.WikiCatalogResponse p0

        Evergreen.V16.Types.PendingReviewCountUpdated p0 p1 ->
            Evergreen.V17.Types.PendingReviewCountUpdated p0 p1

        Evergreen.V16.Types.WikiFrontendDetailsResponse p0 p1 ->
            Evergreen.V17.Types.WikiFrontendDetailsResponse p0
                (p1 |> Maybe.map migrate_Wiki_FrontendDetails)

        Evergreen.V16.Types.PageFrontendDetailsResponse p0 p1 p2 ->
            Evergreen.V17.Types.PageFrontendDetailsResponse p0 p1 p2

        Evergreen.V16.Types.WikiSearchResponse p0 p1 p2 ->
            Evergreen.V17.Types.WikiSearchResponse p0 p1 p2

        Evergreen.V16.Types.MyPendingSubmissionsResponse p0 p1 ->
            Evergreen.V17.Types.MyPendingSubmissionsResponse p0
                (p1 |> Result.mapError migrate_Submission_MyPendingSubmissionsError >> Result.map (List.map migrate_Submission_MyPendingSubmissionListItem))

        Evergreen.V16.Types.ReviewQueueResponse p0 p1 ->
            Evergreen.V17.Types.ReviewQueueResponse p0
                (p1 |> Result.mapError migrate_Submission_ReviewQueueError >> Result.map (List.map migrate_Submission_ReviewQueueItem))

        Evergreen.V16.Types.ReviewSubmissionDetailResponse p0 p1 p2 ->
            Evergreen.V17.Types.ReviewSubmissionDetailResponse p0
                p1
                (p2 |> Result.mapError migrate_SubmissionReviewDetail_ReviewSubmissionDetailError >> Result.map migrate_SubmissionReviewDetail_SubmissionReviewDetail)

        Evergreen.V16.Types.WikiUsersResponse p0 p1 ->
            Evergreen.V17.Types.WikiUsersResponse p0
                (p1 |> Result.mapError migrate_WikiAdminUsers_Error >> Result.map (List.map migrate_WikiAdminUsers_ListedUser))

        Evergreen.V16.Types.WikiAuditLogResponse p0 p1 p2 ->
            Evergreen.V17.Types.WikiAuditLogResponse p0
                (p1 |> migrate_WikiAuditLog_AuditLogFilter)
                (p2 |> Result.mapError migrate_WikiAuditLog_Error >> Result.map (List.map migrate_WikiAuditLog_AuditEvent))

        Evergreen.V16.Types.PromoteContributorToTrustedResponse p0 p1 ->
            Evergreen.V17.Types.PromoteContributorToTrustedResponse p0
                (p1 |> Result.mapError migrate_WikiAdminUsers_PromoteContributorError)

        Evergreen.V16.Types.DemoteTrustedToContributorResponse p0 p1 ->
            Evergreen.V17.Types.DemoteTrustedToContributorResponse p0
                (p1 |> Result.mapError migrate_WikiAdminUsers_DemoteTrustedError)

        Evergreen.V16.Types.GrantWikiAdminResponse p0 p1 ->
            Evergreen.V17.Types.GrantWikiAdminResponse p0
                (p1 |> Result.mapError migrate_WikiAdminUsers_GrantTrustedToAdminError)

        Evergreen.V16.Types.RevokeWikiAdminResponse p0 p1 ->
            Evergreen.V17.Types.RevokeWikiAdminResponse p0
                (p1 |> Result.mapError migrate_WikiAdminUsers_RevokeAdminError)

        Evergreen.V16.Types.SubmissionDetailsResponse p0 p1 p2 ->
            Evergreen.V17.Types.SubmissionDetailsResponse p0
                p1
                (p2 |> Result.mapError migrate_Submission_DetailsError >> Result.map migrate_Submission_ContributorView)

        Evergreen.V16.Types.RegisterContributorResponse p0 p1 ->
            Evergreen.V17.Types.RegisterContributorResponse p0
                (p1 |> Result.mapError migrate_ContributorAccount_RegisterContributorError >> Result.map migrate_WikiRole_WikiRole)

        Evergreen.V16.Types.LoginContributorResponse p0 p1 ->
            Evergreen.V17.Types.LoginContributorResponse p0
                (p1 |> Result.mapError migrate_ContributorAccount_LoginContributorError >> Result.map migrate_WikiRole_WikiRole)

        Evergreen.V16.Types.LogoutContributorResponse p0 ->
            Evergreen.V17.Types.LogoutContributorResponse p0

        Evergreen.V16.Types.SubmitNewPageResponse p0 p1 ->
            Evergreen.V17.Types.SubmitNewPageResponse p0
                (p1 |> Result.mapError migrate_Submission_SubmitNewPageError >> Result.map migrate_Submission_NewPageSubmitSuccess)

        Evergreen.V16.Types.SubmitPageEditResponse p0 p1 ->
            Evergreen.V17.Types.SubmitPageEditResponse p0
                (p1 |> Result.mapError migrate_Submission_SubmitPageEditError >> Result.map migrate_Submission_EditSubmitSuccess)

        Evergreen.V16.Types.RequestPublishedPageDeletionResponse p0 p1 ->
            Evergreen.V17.Types.RequestPublishedPageDeletionResponse p0
                (p1 |> Result.mapError migrate_Submission_RequestPublishedPageDeletionError >> Result.map migrate_Submission_Id)

        Evergreen.V16.Types.DeletePublishedPageImmediatelyResponse p0 p1 ->
            Evergreen.V17.Types.DeletePublishedPageImmediatelyResponse p0
                (p1 |> Result.mapError migrate_Submission_DeletePublishedPageImmediatelyError)

        Evergreen.V16.Types.SaveNewPageDraftResponse p0 p1 ->
            Evergreen.V17.Types.SaveNewPageDraftResponse p0
                (p1 |> Result.mapError migrate_Submission_SaveNewPageDraftError >> Result.map migrate_Submission_Id)

        Evergreen.V16.Types.SavePageEditDraftResponse p0 p1 ->
            Evergreen.V17.Types.SavePageEditDraftResponse p0
                (p1 |> Result.mapError migrate_Submission_SavePageEditDraftError >> Result.map migrate_Submission_Id)

        Evergreen.V16.Types.SavePageDeleteDraftResponse p0 p1 ->
            Evergreen.V17.Types.SavePageDeleteDraftResponse p0
                (p1 |> Result.mapError migrate_Submission_SavePageDeleteDraftError >> Result.map migrate_Submission_Id)

        Evergreen.V16.Types.SubmitDraftForReviewResponse p0 p1 p2 ->
            Evergreen.V17.Types.SubmitDraftForReviewResponse p0
                p1
                (p2 |> Result.mapError migrate_Submission_SubmitDraftForReviewError)

        Evergreen.V16.Types.WithdrawSubmissionResponse p0 p1 p2 ->
            Evergreen.V17.Types.WithdrawSubmissionResponse p0
                p1
                (p2 |> Result.mapError migrate_Submission_WithdrawSubmissionError)

        Evergreen.V16.Types.DeleteMySubmissionResponse p0 p1 p2 ->
            Evergreen.V17.Types.DeleteMySubmissionResponse p0
                p1
                (p2 |> Result.mapError migrate_Submission_DeleteMySubmissionError)

        Evergreen.V16.Types.ApproveSubmissionResponse p0 p1 p2 ->
            Evergreen.V17.Types.ApproveSubmissionResponse p0
                p1
                (p2 |> Result.mapError migrate_Submission_ApproveSubmissionError)

        Evergreen.V16.Types.RejectSubmissionResponse p0 p1 p2 ->
            Evergreen.V17.Types.RejectSubmissionResponse p0
                p1
                (p2 |> Result.mapError migrate_Submission_RejectSubmissionError)

        Evergreen.V16.Types.RequestSubmissionChangesResponse p0 p1 p2 ->
            Evergreen.V17.Types.RequestSubmissionChangesResponse p0
                p1
                (p2 |> Result.mapError migrate_Submission_RequestChangesSubmissionError)

        Evergreen.V16.Types.HostAdminLoginResponse p0 ->
            Evergreen.V17.Types.HostAdminLoginResponse (p0 |> Result.mapError migrate_HostAdmin_LoginError)

        Evergreen.V16.Types.HostAdminWikiListResponse p0 ->
            Evergreen.V17.Types.HostAdminWikiListResponse (p0 |> Result.mapError migrate_HostAdmin_ProtectedError)

        Evergreen.V16.Types.HostAuditLogResponse p0 p1 ->
            Evergreen.V17.Types.HostAuditLogResponse (p0 |> migrate_WikiAuditLog_HostAuditLogFilter)
                (p1 |> Result.mapError migrate_HostAdmin_ProtectedError >> Result.map (List.map migrate_WikiAuditLog_ScopedAuditEvent))

        Evergreen.V16.Types.CreateHostedWikiResponse p0 ->
            Evergreen.V17.Types.CreateHostedWikiResponse (p0 |> Result.mapError migrate_HostAdmin_CreateHostedWikiError >> Result.map migrate_Wiki_CatalogEntry)

        Evergreen.V16.Types.HostWikiDetailResponse p0 p1 ->
            Evergreen.V17.Types.HostWikiDetailResponse p0
                (p1 |> Result.mapError migrate_HostAdmin_HostWikiDetailError >> Result.map migrate_Wiki_CatalogEntry)

        Evergreen.V16.Types.UpdateHostedWikiMetadataResponse p0 p1 ->
            Evergreen.V17.Types.UpdateHostedWikiMetadataResponse p0
                (p1 |> Result.mapError migrate_HostAdmin_UpdateHostedWikiMetadataError >> Result.map migrate_Wiki_CatalogEntry)

        Evergreen.V16.Types.DeactivateHostedWikiResponse p0 p1 ->
            Evergreen.V17.Types.DeactivateHostedWikiResponse p0
                (p1 |> Result.mapError migrate_HostAdmin_WikiLifecycleError >> Result.map migrate_Wiki_CatalogEntry)

        Evergreen.V16.Types.ReactivateHostedWikiResponse p0 p1 ->
            Evergreen.V17.Types.ReactivateHostedWikiResponse p0
                (p1 |> Result.mapError migrate_HostAdmin_WikiLifecycleError >> Result.map migrate_Wiki_CatalogEntry)

        Evergreen.V16.Types.DeleteHostedWikiResponse p0 p1 ->
            Evergreen.V17.Types.DeleteHostedWikiResponse p0
                (p1 |> Result.mapError migrate_HostAdmin_DeleteHostedWikiError)

        Evergreen.V16.Types.HostAdminDataExportResponse p0 ->
            Evergreen.V17.Types.HostAdminDataExportResponse (p0 |> Result.mapError migrate_HostAdmin_DataExportError)

        Evergreen.V16.Types.HostAdminDataImportResponse p0 ->
            Evergreen.V17.Types.HostAdminDataImportResponse (p0 |> Result.mapError migrate_HostAdmin_DataImportError)

        Evergreen.V16.Types.HostAdminWikiDataExportResponse p0 p1 ->
            Evergreen.V17.Types.HostAdminWikiDataExportResponse p0
                (p1 |> Result.mapError migrate_HostAdmin_WikiDataExportError)

        Evergreen.V16.Types.HostAdminWikiDataImportResponse p0 p1 ->
            Evergreen.V17.Types.HostAdminWikiDataImportResponse p0
                (p1 |> Result.mapError migrate_HostAdmin_WikiDataImportError)

        Evergreen.V16.Types.HostAdminWikiDataImportAutoResponse p0 ->
            Evergreen.V17.Types.HostAdminWikiDataImportAutoResponse (p0 |> Result.mapError migrate_HostAdmin_WikiDataImportError)


migrate_WikiAdminUsers_DemoteTrustedError : Evergreen.V16.WikiAdminUsers.DemoteTrustedError -> Evergreen.V17.WikiAdminUsers.DemoteTrustedError
migrate_WikiAdminUsers_DemoteTrustedError old =
    case old of
        Evergreen.V16.WikiAdminUsers.DemoteNotLoggedIn ->
            Evergreen.V17.WikiAdminUsers.DemoteNotLoggedIn

        Evergreen.V16.WikiAdminUsers.DemoteWrongWikiSession ->
            Evergreen.V17.WikiAdminUsers.DemoteWrongWikiSession

        Evergreen.V16.WikiAdminUsers.DemoteForbidden ->
            Evergreen.V17.WikiAdminUsers.DemoteForbidden

        Evergreen.V16.WikiAdminUsers.DemoteWikiNotFound ->
            Evergreen.V17.WikiAdminUsers.DemoteWikiNotFound

        Evergreen.V16.WikiAdminUsers.DemoteWikiInactive ->
            Evergreen.V17.WikiAdminUsers.DemoteWikiInactive

        Evergreen.V16.WikiAdminUsers.DemoteTargetNotFound ->
            Evergreen.V17.WikiAdminUsers.DemoteTargetNotFound

        Evergreen.V16.WikiAdminUsers.DemoteTargetNotTrusted ->
            Evergreen.V17.WikiAdminUsers.DemoteTargetNotTrusted


migrate_WikiAdminUsers_Error : Evergreen.V16.WikiAdminUsers.Error -> Evergreen.V17.WikiAdminUsers.Error
migrate_WikiAdminUsers_Error old =
    case old of
        Evergreen.V16.WikiAdminUsers.NotLoggedIn ->
            Evergreen.V17.WikiAdminUsers.NotLoggedIn

        Evergreen.V16.WikiAdminUsers.WrongWikiSession ->
            Evergreen.V17.WikiAdminUsers.WrongWikiSession

        Evergreen.V16.WikiAdminUsers.Forbidden ->
            Evergreen.V17.WikiAdminUsers.Forbidden

        Evergreen.V16.WikiAdminUsers.WikiNotFound ->
            Evergreen.V17.WikiAdminUsers.WikiNotFound

        Evergreen.V16.WikiAdminUsers.WikiInactive ->
            Evergreen.V17.WikiAdminUsers.WikiInactive


migrate_WikiAdminUsers_GrantTrustedToAdminError : Evergreen.V16.WikiAdminUsers.GrantTrustedToAdminError -> Evergreen.V17.WikiAdminUsers.GrantTrustedToAdminError
migrate_WikiAdminUsers_GrantTrustedToAdminError old =
    case old of
        Evergreen.V16.WikiAdminUsers.GrantTrustedNotLoggedIn ->
            Evergreen.V17.WikiAdminUsers.GrantTrustedNotLoggedIn

        Evergreen.V16.WikiAdminUsers.GrantTrustedWrongWikiSession ->
            Evergreen.V17.WikiAdminUsers.GrantTrustedWrongWikiSession

        Evergreen.V16.WikiAdminUsers.GrantTrustedForbidden ->
            Evergreen.V17.WikiAdminUsers.GrantTrustedForbidden

        Evergreen.V16.WikiAdminUsers.GrantTrustedWikiNotFound ->
            Evergreen.V17.WikiAdminUsers.GrantTrustedWikiNotFound

        Evergreen.V16.WikiAdminUsers.GrantTrustedWikiInactive ->
            Evergreen.V17.WikiAdminUsers.GrantTrustedWikiInactive

        Evergreen.V16.WikiAdminUsers.GrantTrustedTargetNotFound ->
            Evergreen.V17.WikiAdminUsers.GrantTrustedTargetNotFound

        Evergreen.V16.WikiAdminUsers.GrantTrustedTargetNotTrusted ->
            Evergreen.V17.WikiAdminUsers.GrantTrustedTargetNotTrusted


migrate_WikiAdminUsers_ListedUser : Evergreen.V16.WikiAdminUsers.ListedUser -> Evergreen.V17.WikiAdminUsers.ListedUser
migrate_WikiAdminUsers_ListedUser old =
    { username = old.username
    , role = old.role |> migrate_WikiRole_WikiRole
    }


migrate_WikiAdminUsers_PromoteContributorError : Evergreen.V16.WikiAdminUsers.PromoteContributorError -> Evergreen.V17.WikiAdminUsers.PromoteContributorError
migrate_WikiAdminUsers_PromoteContributorError old =
    case old of
        Evergreen.V16.WikiAdminUsers.PromoteNotLoggedIn ->
            Evergreen.V17.WikiAdminUsers.PromoteNotLoggedIn

        Evergreen.V16.WikiAdminUsers.PromoteWrongWikiSession ->
            Evergreen.V17.WikiAdminUsers.PromoteWrongWikiSession

        Evergreen.V16.WikiAdminUsers.PromoteForbidden ->
            Evergreen.V17.WikiAdminUsers.PromoteForbidden

        Evergreen.V16.WikiAdminUsers.PromoteWikiNotFound ->
            Evergreen.V17.WikiAdminUsers.PromoteWikiNotFound

        Evergreen.V16.WikiAdminUsers.PromoteWikiInactive ->
            Evergreen.V17.WikiAdminUsers.PromoteWikiInactive

        Evergreen.V16.WikiAdminUsers.PromoteTargetNotFound ->
            Evergreen.V17.WikiAdminUsers.PromoteTargetNotFound

        Evergreen.V16.WikiAdminUsers.PromoteTargetNotContributor ->
            Evergreen.V17.WikiAdminUsers.PromoteTargetNotContributor


migrate_WikiAdminUsers_RevokeAdminError : Evergreen.V16.WikiAdminUsers.RevokeAdminError -> Evergreen.V17.WikiAdminUsers.RevokeAdminError
migrate_WikiAdminUsers_RevokeAdminError old =
    case old of
        Evergreen.V16.WikiAdminUsers.RevokeAdminNotLoggedIn ->
            Evergreen.V17.WikiAdminUsers.RevokeAdminNotLoggedIn

        Evergreen.V16.WikiAdminUsers.RevokeAdminWrongWikiSession ->
            Evergreen.V17.WikiAdminUsers.RevokeAdminWrongWikiSession

        Evergreen.V16.WikiAdminUsers.RevokeAdminForbidden ->
            Evergreen.V17.WikiAdminUsers.RevokeAdminForbidden

        Evergreen.V16.WikiAdminUsers.RevokeAdminWikiNotFound ->
            Evergreen.V17.WikiAdminUsers.RevokeAdminWikiNotFound

        Evergreen.V16.WikiAdminUsers.RevokeAdminWikiInactive ->
            Evergreen.V17.WikiAdminUsers.RevokeAdminWikiInactive

        Evergreen.V16.WikiAdminUsers.RevokeAdminTargetNotFound ->
            Evergreen.V17.WikiAdminUsers.RevokeAdminTargetNotFound

        Evergreen.V16.WikiAdminUsers.RevokeAdminTargetNotAdmin ->
            Evergreen.V17.WikiAdminUsers.RevokeAdminTargetNotAdmin

        Evergreen.V16.WikiAdminUsers.RevokeAdminCannotRevokeSelf ->
            Evergreen.V17.WikiAdminUsers.RevokeAdminCannotRevokeSelf


migrate_WikiAuditLog_AuditEvent : Evergreen.V16.WikiAuditLog.AuditEvent -> Evergreen.V17.WikiAuditLog.AuditEvent
migrate_WikiAuditLog_AuditEvent old =
    { at = old.at
    , actorUsername = old.actorUsername
    , kind = old.kind |> migrate_WikiAuditLog_AuditEventKind
    }


migrate_WikiAuditLog_AuditEventKind : Evergreen.V16.WikiAuditLog.AuditEventKind -> Evergreen.V17.WikiAuditLog.AuditEventKind
migrate_WikiAuditLog_AuditEventKind old =
    case old of
        Evergreen.V16.WikiAuditLog.ApprovedSubmission p0 ->
            Evergreen.V17.WikiAuditLog.ApprovedSubmission p0

        Evergreen.V16.WikiAuditLog.RejectedSubmission p0 ->
            Evergreen.V17.WikiAuditLog.RejectedSubmission p0

        Evergreen.V16.WikiAuditLog.RequestedSubmissionChanges p0 ->
            Evergreen.V17.WikiAuditLog.RequestedSubmissionChanges p0

        Evergreen.V16.WikiAuditLog.PromotedContributorToTrusted p0 ->
            Evergreen.V17.WikiAuditLog.PromotedContributorToTrusted p0

        Evergreen.V16.WikiAuditLog.DemotedTrustedToContributor p0 ->
            Evergreen.V17.WikiAuditLog.DemotedTrustedToContributor p0

        Evergreen.V16.WikiAuditLog.GrantedWikiAdmin p0 ->
            Evergreen.V17.WikiAuditLog.GrantedWikiAdmin p0

        Evergreen.V16.WikiAuditLog.RevokedWikiAdmin p0 ->
            Evergreen.V17.WikiAuditLog.RevokedWikiAdmin p0

        Evergreen.V16.WikiAuditLog.TrustedPublishedNewPage p0 ->
            Evergreen.V17.WikiAuditLog.TrustedPublishedNewPage p0

        Evergreen.V16.WikiAuditLog.TrustedPublishedPageEdit p0 ->
            Evergreen.V17.WikiAuditLog.TrustedPublishedPageEdit p0

        Evergreen.V16.WikiAuditLog.TrustedPublishedPageDelete p0 ->
            Evergreen.V17.WikiAuditLog.TrustedPublishedPageDelete p0


migrate_WikiAuditLog_AuditEventKindFilterTag : Evergreen.V16.WikiAuditLog.AuditEventKindFilterTag -> Evergreen.V17.WikiAuditLog.AuditEventKindFilterTag
migrate_WikiAuditLog_AuditEventKindFilterTag old =
    case old of
        Evergreen.V16.WikiAuditLog.ApprovedSubmissionKind ->
            Evergreen.V17.WikiAuditLog.ApprovedSubmissionKind

        Evergreen.V16.WikiAuditLog.RejectedSubmissionKind ->
            Evergreen.V17.WikiAuditLog.RejectedSubmissionKind

        Evergreen.V16.WikiAuditLog.RequestedSubmissionChangesKind ->
            Evergreen.V17.WikiAuditLog.RequestedSubmissionChangesKind

        Evergreen.V16.WikiAuditLog.PromotedContributorToTrustedKind ->
            Evergreen.V17.WikiAuditLog.PromotedContributorToTrustedKind

        Evergreen.V16.WikiAuditLog.DemotedTrustedToContributorKind ->
            Evergreen.V17.WikiAuditLog.DemotedTrustedToContributorKind

        Evergreen.V16.WikiAuditLog.GrantedWikiAdminKind ->
            Evergreen.V17.WikiAuditLog.GrantedWikiAdminKind

        Evergreen.V16.WikiAuditLog.RevokedWikiAdminKind ->
            Evergreen.V17.WikiAuditLog.RevokedWikiAdminKind

        Evergreen.V16.WikiAuditLog.TrustedPublishedNewPageKind ->
            Evergreen.V17.WikiAuditLog.TrustedPublishedNewPageKind

        Evergreen.V16.WikiAuditLog.TrustedPublishedPageEditKind ->
            Evergreen.V17.WikiAuditLog.TrustedPublishedPageEditKind

        Evergreen.V16.WikiAuditLog.TrustedPublishedPageDeleteKind ->
            Evergreen.V17.WikiAuditLog.TrustedPublishedPageDeleteKind


migrate_WikiAuditLog_AuditLogFilter : Evergreen.V16.WikiAuditLog.AuditLogFilter -> Evergreen.V17.WikiAuditLog.AuditLogFilter
migrate_WikiAuditLog_AuditLogFilter old =
    { actorUsernameSubstring = old.actorUsernameSubstring
    , pageSlugSubstring = old.pageSlugSubstring
    , eventKindTags = old.eventKindTags |> List.map migrate_WikiAuditLog_AuditEventKindFilterTag
    }


migrate_WikiAuditLog_Error : Evergreen.V16.WikiAuditLog.Error -> Evergreen.V17.WikiAuditLog.Error
migrate_WikiAuditLog_Error old =
    case old of
        Evergreen.V16.WikiAuditLog.WikiNotFound ->
            Evergreen.V17.WikiAuditLog.WikiNotFound

        Evergreen.V16.WikiAuditLog.WikiInactive ->
            Evergreen.V17.WikiAuditLog.WikiInactive

        Evergreen.V16.WikiAuditLog.NotLoggedIn ->
            Evergreen.V17.WikiAuditLog.NotLoggedIn

        Evergreen.V16.WikiAuditLog.WrongWikiSession ->
            Evergreen.V17.WikiAuditLog.WrongWikiSession

        Evergreen.V16.WikiAuditLog.Forbidden ->
            Evergreen.V17.WikiAuditLog.Forbidden


migrate_WikiAuditLog_HostAuditLogFilter : Evergreen.V16.WikiAuditLog.HostAuditLogFilter -> Evergreen.V17.WikiAuditLog.HostAuditLogFilter
migrate_WikiAuditLog_HostAuditLogFilter old =
    { wikiSlugSubstring = old.wikiSlugSubstring
    , actorUsernameSubstring = old.actorUsernameSubstring
    , pageSlugSubstring = old.pageSlugSubstring
    , eventKindTags = old.eventKindTags |> List.map migrate_WikiAuditLog_AuditEventKindFilterTag
    }


migrate_WikiAuditLog_ScopedAuditEvent : Evergreen.V16.WikiAuditLog.ScopedAuditEvent -> Evergreen.V17.WikiAuditLog.ScopedAuditEvent
migrate_WikiAuditLog_ScopedAuditEvent old =
    { wikiSlug = old.wikiSlug
    , at = old.at
    , actorUsername = old.actorUsername
    , kind = old.kind |> migrate_WikiAuditLog_AuditEventKind
    }


migrate_WikiContributors_Registry : Evergreen.V16.WikiContributors.Registry -> Evergreen.V17.WikiContributors.Registry
migrate_WikiContributors_Registry old =
    old |> Dict.map (\_ -> Dict.map (\k -> migrate_WikiContributors_StoredContributor))


migrate_WikiContributors_StoredContributor : Evergreen.V16.WikiContributors.StoredContributor -> Evergreen.V17.WikiContributors.StoredContributor
migrate_WikiContributors_StoredContributor old =
    { id = old.id |> migrate_ContributorAccount_Id
    , passwordVerifier = old.passwordVerifier |> migrate_ContributorAccount_Verifier
    , role = old.role |> migrate_WikiRole_WikiRole
    }


migrate_WikiMarkdownEditorPane_WikiMarkdownEditorPane : Evergreen.V16.WikiMarkdownEditorPane.WikiMarkdownEditorPane -> Evergreen.V17.WikiMarkdownEditorPane.WikiMarkdownEditorPane
migrate_WikiMarkdownEditorPane_WikiMarkdownEditorPane old =
    case old of
        Evergreen.V16.WikiMarkdownEditorPane.EditorWrite ->
            Evergreen.V17.WikiMarkdownEditorPane.EditorWrite

        Evergreen.V16.WikiMarkdownEditorPane.EditorPreview ->
            Evergreen.V17.WikiMarkdownEditorPane.EditorPreview


migrate_WikiRole_SubmissionsScope : Evergreen.V16.WikiRole.SubmissionsScope -> Evergreen.V17.WikiRole.SubmissionsScope
migrate_WikiRole_SubmissionsScope old =
    case old of
        Evergreen.V16.WikiRole.SubmissionsScope ->
            Evergreen.V17.WikiRole.SubmissionsScope


migrate_WikiRole_UntrustedContributorCaps : Evergreen.V16.WikiRole.UntrustedContributorCaps -> Evergreen.V17.WikiRole.UntrustedContributorCaps
migrate_WikiRole_UntrustedContributorCaps old =
    { submissions = old.submissions |> migrate_WikiRole_SubmissionsScope
    }


migrate_WikiRole_WikiRole : Evergreen.V16.WikiRole.WikiRole -> Evergreen.V17.WikiRole.WikiRole
migrate_WikiRole_WikiRole old =
    case old of
        Evergreen.V16.WikiRole.UntrustedContributor p0 ->
            Evergreen.V17.WikiRole.UntrustedContributor (p0 |> migrate_WikiRole_UntrustedContributorCaps)

        Evergreen.V16.WikiRole.TrustedContributor ->
            Evergreen.V17.WikiRole.TrustedContributor

        Evergreen.V16.WikiRole.Admin ->
            Evergreen.V17.WikiRole.Admin


migrate_WikiUser_SessionTable : Evergreen.V16.WikiUser.SessionTable -> Evergreen.V17.WikiUser.SessionTable
migrate_WikiUser_SessionTable old =
    old |> Dict.map (\k -> migrate_WikiUser_WikiBindings)


migrate_WikiUser_WikiBindings : Evergreen.V16.WikiUser.WikiBindings -> Evergreen.V17.WikiUser.WikiBindings
migrate_WikiUser_WikiBindings old =
    old |> Dict.map (\k -> migrate_ContributorAccount_Id)


migrate_Wiki_CatalogEntry : Evergreen.V16.Wiki.CatalogEntry -> Evergreen.V17.Wiki.CatalogEntry
migrate_Wiki_CatalogEntry old =
    old


migrate_Wiki_FrontendDetails : Evergreen.V16.Wiki.FrontendDetails -> Evergreen.V17.Wiki.FrontendDetails
migrate_Wiki_FrontendDetails old =
    { pageSlugs = old.pageSlugs
    , publishedPageMarkdownSources = old.publishedPageMarkdownSources
    , publishedPageTags = old.publishedPageTags
    , contentVersion = 1
    , pendingReviewCountForTrustedViewer = old.pendingReviewCountForTrustedViewer
    , viewerSession = old.viewerSession |> Maybe.map migrate_ContributorWikiSession_ContributorWikiSession
    }


migrate_Wiki_Wiki : Evergreen.V16.Wiki.Wiki -> Evergreen.V17.Wiki.Wiki
migrate_Wiki_Wiki old =
    { slug = old.slug
    , name = old.name
    , summary = old.summary
    , active = old.active
    , contentVersion = 1
    , pages = old.pages
    }
