module Evergreen.Migrate.V2 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V1.ColorTheme
import Evergreen.V1.ContributorAccount
import Evergreen.V1.HostAdmin
import Evergreen.V1.Submission
import Evergreen.V1.SubmissionReviewDetail
import Evergreen.V1.Types
import Evergreen.V1.Wiki
import Evergreen.V1.WikiAdminUsers
import Evergreen.V1.WikiAuditLog
import Evergreen.V1.WikiRole
import Evergreen.V2.ColorTheme
import Evergreen.V2.ContributorAccount
import Evergreen.V2.HostAdmin
import Evergreen.V2.Submission
import Evergreen.V2.SubmissionReviewDetail
import Evergreen.V2.Types
import Evergreen.V2.Wiki
import Evergreen.V2.WikiAdminUsers
import Evergreen.V2.WikiAuditLog
import Evergreen.V2.WikiRole
import Lamdera.Migrations exposing (..)
import List


frontendModel : Evergreen.V1.Types.FrontendModel -> ModelMigration Evergreen.V2.Types.FrontendModel Evergreen.V2.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V1.Types.BackendModel -> ModelMigration Evergreen.V2.Types.BackendModel Evergreen.V2.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V1.Types.FrontendMsg -> MsgMigration Evergreen.V2.Types.FrontendMsg Evergreen.V2.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V1.Types.ToBackend -> MsgMigration Evergreen.V2.Types.ToBackend Evergreen.V2.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V1.Types.BackendMsg -> MsgMigration Evergreen.V2.Types.BackendMsg Evergreen.V2.Types.BackendMsg
backendMsg old =
    MsgMigrated ( migrate_Types_BackendMsg old, Cmd.none )


toFrontend : Evergreen.V1.Types.ToFrontend -> MsgMigration Evergreen.V2.Types.ToFrontend Evergreen.V2.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_ColorTheme_ColorTheme : Evergreen.V1.ColorTheme.ColorTheme -> Evergreen.V2.ColorTheme.ColorTheme
migrate_ColorTheme_ColorTheme old =
    case old of
        Evergreen.V1.ColorTheme.Light ->
            Evergreen.V2.ColorTheme.Light

        Evergreen.V1.ColorTheme.Dark ->
            Evergreen.V2.ColorTheme.Dark


migrate_ColorTheme_ColorThemePreference : Evergreen.V1.ColorTheme.ColorThemePreference -> Evergreen.V2.ColorTheme.ColorThemePreference
migrate_ColorTheme_ColorThemePreference old =
    case old of
        Evergreen.V1.ColorTheme.FollowSystem ->
            Evergreen.V2.ColorTheme.FollowSystem

        Evergreen.V1.ColorTheme.Fixed p0 ->
            Evergreen.V2.ColorTheme.Fixed (p0 |> migrate_ColorTheme_ColorTheme)


migrate_ColorTheme_Incoming : Evergreen.V1.ColorTheme.Incoming -> Evergreen.V2.ColorTheme.Incoming
migrate_ColorTheme_Incoming old =
    case old of
        Evergreen.V1.ColorTheme.Sync p0 p1 ->
            Evergreen.V2.ColorTheme.Sync (p0 |> migrate_ColorTheme_ColorThemePreference)
                (p1 |> migrate_ColorTheme_ColorTheme)

        Evergreen.V1.ColorTheme.System p0 ->
            Evergreen.V2.ColorTheme.System (p0 |> migrate_ColorTheme_ColorTheme)


migrate_ContributorAccount_LoginContributorError : Evergreen.V1.ContributorAccount.LoginContributorError -> Evergreen.V2.ContributorAccount.LoginContributorError
migrate_ContributorAccount_LoginContributorError old =
    case old of
        Evergreen.V1.ContributorAccount.LoginWikiNotFound ->
            Evergreen.V2.ContributorAccount.LoginWikiNotFound

        Evergreen.V1.ContributorAccount.LoginWikiInactive ->
            Evergreen.V2.ContributorAccount.LoginWikiInactive

        Evergreen.V1.ContributorAccount.LoginInvalidCredentials ->
            Evergreen.V2.ContributorAccount.LoginInvalidCredentials

        Evergreen.V1.ContributorAccount.LoginUsernameEmpty ->
            Evergreen.V2.ContributorAccount.LoginUsernameEmpty

        Evergreen.V1.ContributorAccount.LoginPasswordEmpty ->
            Evergreen.V2.ContributorAccount.LoginPasswordEmpty


migrate_ContributorAccount_RegisterContributorError : Evergreen.V1.ContributorAccount.RegisterContributorError -> Evergreen.V2.ContributorAccount.RegisterContributorError
migrate_ContributorAccount_RegisterContributorError old =
    case old of
        Evergreen.V1.ContributorAccount.RegisterWikiNotFound ->
            Evergreen.V2.ContributorAccount.RegisterWikiNotFound

        Evergreen.V1.ContributorAccount.RegisterWikiInactive ->
            Evergreen.V2.ContributorAccount.RegisterWikiInactive

        Evergreen.V1.ContributorAccount.RegisterUsernameTaken ->
            Evergreen.V2.ContributorAccount.RegisterUsernameTaken

        Evergreen.V1.ContributorAccount.RegisterUsernameEmpty ->
            Evergreen.V2.ContributorAccount.RegisterUsernameEmpty

        Evergreen.V1.ContributorAccount.RegisterUsernameTooShort ->
            Evergreen.V2.ContributorAccount.RegisterUsernameTooShort

        Evergreen.V1.ContributorAccount.RegisterUsernameTooLong ->
            Evergreen.V2.ContributorAccount.RegisterUsernameTooLong

        Evergreen.V1.ContributorAccount.RegisterUsernameInvalidChars ->
            Evergreen.V2.ContributorAccount.RegisterUsernameInvalidChars

        Evergreen.V1.ContributorAccount.RegisterPasswordEmpty ->
            Evergreen.V2.ContributorAccount.RegisterPasswordEmpty


migrate_HostAdmin_CreateHostedWikiError : Evergreen.V1.HostAdmin.CreateHostedWikiError -> Evergreen.V2.HostAdmin.CreateHostedWikiError
migrate_HostAdmin_CreateHostedWikiError old =
    case old of
        Evergreen.V1.HostAdmin.CreateNotHostAuthenticated ->
            Evergreen.V2.HostAdmin.CreateNotHostAuthenticated

        Evergreen.V1.HostAdmin.CreateSlugInvalid p0 ->
            Evergreen.V2.HostAdmin.CreateSlugInvalid (p0 |> migrate_Submission_ValidationError)

        Evergreen.V1.HostAdmin.CreateWikiNameInvalid p0 ->
            Evergreen.V2.HostAdmin.CreateWikiNameInvalid (p0 |> migrate_HostAdmin_WikiNameError)

        Evergreen.V1.HostAdmin.CreateWikiSlugTaken ->
            Evergreen.V2.HostAdmin.CreateWikiSlugTaken

        Evergreen.V1.HostAdmin.CreateInitialAdminInvalid p0 ->
            Evergreen.V2.HostAdmin.CreateInitialAdminInvalid (p0 |> migrate_ContributorAccount_RegisterContributorError)


migrate_HostAdmin_DataExportError : Evergreen.V1.HostAdmin.DataExportError -> Evergreen.V2.HostAdmin.DataExportError
migrate_HostAdmin_DataExportError old =
    case old of
        Evergreen.V1.HostAdmin.DataExportNotHostAuthenticated ->
            Evergreen.V2.HostAdmin.DataExportNotHostAuthenticated


migrate_HostAdmin_DataImportError : Evergreen.V1.HostAdmin.DataImportError -> Evergreen.V2.HostAdmin.DataImportError
migrate_HostAdmin_DataImportError old =
    case old of
        Evergreen.V1.HostAdmin.DataImportNotHostAuthenticated ->
            Evergreen.V2.HostAdmin.DataImportNotHostAuthenticated

        Evergreen.V1.HostAdmin.DataImportInvalid p0 ->
            Evergreen.V2.HostAdmin.DataImportInvalid p0


migrate_HostAdmin_DeleteHostedWikiError : Evergreen.V1.HostAdmin.DeleteHostedWikiError -> Evergreen.V2.HostAdmin.DeleteHostedWikiError
migrate_HostAdmin_DeleteHostedWikiError old =
    case old of
        Evergreen.V1.HostAdmin.DeleteHostedWikiNotHostAuthenticated ->
            Evergreen.V2.HostAdmin.DeleteHostedWikiNotHostAuthenticated

        Evergreen.V1.HostAdmin.DeleteHostedWikiWikiNotFound ->
            Evergreen.V2.HostAdmin.DeleteHostedWikiWikiNotFound

        Evergreen.V1.HostAdmin.DeleteHostedWikiConfirmationMismatch ->
            Evergreen.V2.HostAdmin.DeleteHostedWikiConfirmationMismatch


migrate_HostAdmin_HostWikiDetailError : Evergreen.V1.HostAdmin.HostWikiDetailError -> Evergreen.V2.HostAdmin.HostWikiDetailError
migrate_HostAdmin_HostWikiDetailError old =
    case old of
        Evergreen.V1.HostAdmin.HostWikiDetailNotHostAuthenticated ->
            Evergreen.V2.HostAdmin.HostWikiDetailNotHostAuthenticated

        Evergreen.V1.HostAdmin.HostWikiDetailWikiNotFound ->
            Evergreen.V2.HostAdmin.HostWikiDetailWikiNotFound


migrate_HostAdmin_LoginError : Evergreen.V1.HostAdmin.LoginError -> Evergreen.V2.HostAdmin.LoginError
migrate_HostAdmin_LoginError old =
    case old of
        Evergreen.V1.HostAdmin.WrongPassword ->
            Evergreen.V2.HostAdmin.WrongPassword


migrate_HostAdmin_ProtectedError : Evergreen.V1.HostAdmin.ProtectedError -> Evergreen.V2.HostAdmin.ProtectedError
migrate_HostAdmin_ProtectedError old =
    case old of
        Evergreen.V1.HostAdmin.NotHostAuthenticated ->
            Evergreen.V2.HostAdmin.NotHostAuthenticated


migrate_HostAdmin_UpdateHostedWikiMetadataError : Evergreen.V1.HostAdmin.UpdateHostedWikiMetadataError -> Evergreen.V2.HostAdmin.UpdateHostedWikiMetadataError
migrate_HostAdmin_UpdateHostedWikiMetadataError old =
    case old of
        Evergreen.V1.HostAdmin.UpdateMetadataNotHostAuthenticated ->
            Evergreen.V2.HostAdmin.UpdateMetadataNotHostAuthenticated

        Evergreen.V1.HostAdmin.UpdateMetadataWikiNotFound ->
            Evergreen.V2.HostAdmin.UpdateMetadataWikiNotFound

        Evergreen.V1.HostAdmin.UpdateMetadataWikiNameInvalid p0 ->
            Evergreen.V2.HostAdmin.UpdateMetadataWikiNameInvalid (p0 |> migrate_HostAdmin_WikiNameError)

        Evergreen.V1.HostAdmin.UpdateMetadataWikiSummaryInvalid p0 ->
            Evergreen.V2.HostAdmin.UpdateMetadataWikiSummaryInvalid (p0 |> migrate_HostAdmin_WikiSummaryError)

        Evergreen.V1.HostAdmin.UpdateMetadataWikiSlugInvalid p0 ->
            Evergreen.V2.HostAdmin.UpdateMetadataWikiSlugInvalid (p0 |> migrate_Submission_ValidationError)

        Evergreen.V1.HostAdmin.UpdateMetadataWikiSlugTaken ->
            Evergreen.V2.HostAdmin.UpdateMetadataWikiSlugTaken


migrate_HostAdmin_WikiDataExportError : Evergreen.V1.HostAdmin.WikiDataExportError -> Evergreen.V2.HostAdmin.WikiDataExportError
migrate_HostAdmin_WikiDataExportError old =
    case old of
        Evergreen.V1.HostAdmin.WikiDataExportNotHostAuthenticated ->
            Evergreen.V2.HostAdmin.WikiDataExportNotHostAuthenticated

        Evergreen.V1.HostAdmin.WikiDataExportWikiNotFound ->
            Evergreen.V2.HostAdmin.WikiDataExportWikiNotFound


migrate_HostAdmin_WikiDataImportError : Evergreen.V1.HostAdmin.WikiDataImportError -> Evergreen.V2.HostAdmin.WikiDataImportError
migrate_HostAdmin_WikiDataImportError old =
    case old of
        Evergreen.V1.HostAdmin.WikiDataImportNotHostAuthenticated ->
            Evergreen.V2.HostAdmin.WikiDataImportNotHostAuthenticated

        Evergreen.V1.HostAdmin.WikiDataImportWikiNotFound ->
            Evergreen.V2.HostAdmin.WikiDataImportWikiNotFound

        Evergreen.V1.HostAdmin.WikiDataImportInvalid p0 ->
            Evergreen.V2.HostAdmin.WikiDataImportInvalid p0


migrate_HostAdmin_WikiLifecycleError : Evergreen.V1.HostAdmin.WikiLifecycleError -> Evergreen.V2.HostAdmin.WikiLifecycleError
migrate_HostAdmin_WikiLifecycleError old =
    case old of
        Evergreen.V1.HostAdmin.WikiLifecycleNotHostAuthenticated ->
            Evergreen.V2.HostAdmin.WikiLifecycleNotHostAuthenticated

        Evergreen.V1.HostAdmin.WikiLifecycleWikiNotFound ->
            Evergreen.V2.HostAdmin.WikiLifecycleWikiNotFound


migrate_HostAdmin_WikiNameError : Evergreen.V1.HostAdmin.WikiNameError -> Evergreen.V2.HostAdmin.WikiNameError
migrate_HostAdmin_WikiNameError old =
    case old of
        Evergreen.V1.HostAdmin.WikiNameEmpty ->
            Evergreen.V2.HostAdmin.WikiNameEmpty

        Evergreen.V1.HostAdmin.WikiNameTooLong ->
            Evergreen.V2.HostAdmin.WikiNameTooLong


migrate_HostAdmin_WikiSummaryError : Evergreen.V1.HostAdmin.WikiSummaryError -> Evergreen.V2.HostAdmin.WikiSummaryError
migrate_HostAdmin_WikiSummaryError old =
    case old of
        Evergreen.V1.HostAdmin.WikiSummaryTooLong ->
            Evergreen.V2.HostAdmin.WikiSummaryTooLong


migrate_SubmissionReviewDetail_ReviewSubmissionDetailError : Evergreen.V1.SubmissionReviewDetail.ReviewSubmissionDetailError -> Evergreen.V2.SubmissionReviewDetail.ReviewSubmissionDetailError
migrate_SubmissionReviewDetail_ReviewSubmissionDetailError old =
    case old of
        Evergreen.V1.SubmissionReviewDetail.ReviewSubmissionDetailNotLoggedIn ->
            Evergreen.V2.SubmissionReviewDetail.ReviewSubmissionDetailNotLoggedIn

        Evergreen.V1.SubmissionReviewDetail.ReviewSubmissionDetailWrongWikiSession ->
            Evergreen.V2.SubmissionReviewDetail.ReviewSubmissionDetailWrongWikiSession

        Evergreen.V1.SubmissionReviewDetail.ReviewSubmissionDetailForbidden ->
            Evergreen.V2.SubmissionReviewDetail.ReviewSubmissionDetailForbidden

        Evergreen.V1.SubmissionReviewDetail.ReviewSubmissionDetailWikiInactive ->
            Evergreen.V2.SubmissionReviewDetail.ReviewSubmissionDetailWikiInactive

        Evergreen.V1.SubmissionReviewDetail.ReviewSubmissionDetailNotFound ->
            Evergreen.V2.SubmissionReviewDetail.ReviewSubmissionDetailNotFound


migrate_SubmissionReviewDetail_SubmissionReviewDetail : Evergreen.V1.SubmissionReviewDetail.SubmissionReviewDetail -> Evergreen.V2.SubmissionReviewDetail.SubmissionReviewDetail
migrate_SubmissionReviewDetail_SubmissionReviewDetail old =
    case old of
        Evergreen.V1.SubmissionReviewDetail.NewPageDiff p0 ->
            Evergreen.V2.SubmissionReviewDetail.NewPageDiff p0

        Evergreen.V1.SubmissionReviewDetail.EditPageDiff p0 ->
            Evergreen.V2.SubmissionReviewDetail.EditPageDiff p0

        Evergreen.V1.SubmissionReviewDetail.DeletePageDiff p0 ->
            Evergreen.V2.SubmissionReviewDetail.DeletePageDiff p0


migrate_Submission_ApproveSubmissionError : Evergreen.V1.Submission.ApproveSubmissionError -> Evergreen.V2.Submission.ApproveSubmissionError
migrate_Submission_ApproveSubmissionError old =
    case old of
        Evergreen.V1.Submission.ApproveNotLoggedIn ->
            Evergreen.V2.Submission.ApproveNotLoggedIn

        Evergreen.V1.Submission.ApproveWrongWikiSession ->
            Evergreen.V2.Submission.ApproveWrongWikiSession

        Evergreen.V1.Submission.ApproveForbidden ->
            Evergreen.V2.Submission.ApproveForbidden

        Evergreen.V1.Submission.ApproveWikiNotFound ->
            Evergreen.V2.Submission.ApproveWikiNotFound

        Evergreen.V1.Submission.ApproveWikiInactive ->
            Evergreen.V2.Submission.ApproveWikiInactive

        Evergreen.V1.Submission.ApproveSubmissionNotFound ->
            Evergreen.V2.Submission.ApproveSubmissionNotFound

        Evergreen.V1.Submission.ApproveNotPending ->
            Evergreen.V2.Submission.ApproveNotPending

        Evergreen.V1.Submission.ApproveNewPageSlugTaken ->
            Evergreen.V2.Submission.ApproveNewPageSlugTaken

        Evergreen.V1.Submission.ApproveEditTargetNotPublished ->
            Evergreen.V2.Submission.ApproveEditTargetNotPublished

        Evergreen.V1.Submission.ApproveDeleteTargetNotPublished ->
            Evergreen.V2.Submission.ApproveDeleteTargetNotPublished


migrate_Submission_ContributorSubmissionKind : Evergreen.V1.Submission.ContributorSubmissionKind -> Evergreen.V2.Submission.ContributorSubmissionKind
migrate_Submission_ContributorSubmissionKind old =
    case old of
        Evergreen.V1.Submission.ContributorKindNewPage ->
            Evergreen.V2.Submission.ContributorKindNewPage

        Evergreen.V1.Submission.ContributorKindEditPage ->
            Evergreen.V2.Submission.ContributorKindEditPage

        Evergreen.V1.Submission.ContributorKindDeletePage ->
            Evergreen.V2.Submission.ContributorKindDeletePage


migrate_Submission_ContributorView : Evergreen.V1.Submission.ContributorView -> Evergreen.V2.Submission.ContributorView
migrate_Submission_ContributorView old =
    { id = old.id |> migrate_Submission_Id
    , status = old.status |> migrate_Submission_Status
    , kindSummary = old.kindSummary
    , contributionKind = old.contributionKind |> migrate_Submission_ContributorSubmissionKind
    , reviewerNote = old.reviewerNote
    , conflictContext = old.conflictContext
    , compareOriginalMarkdown = old.compareOriginalMarkdown
    , compareNewMarkdown = old.compareNewMarkdown
    , maybeNewPageSlug = old.maybeNewPageSlug
    , maybeEditPageSlug = old.maybeEditPageSlug
    }


migrate_Submission_DeleteMySubmissionError : Evergreen.V1.Submission.DeleteMySubmissionError -> Evergreen.V2.Submission.DeleteMySubmissionError
migrate_Submission_DeleteMySubmissionError old =
    case old of
        Evergreen.V1.Submission.DeleteMySubmissionNotLoggedIn ->
            Evergreen.V2.Submission.DeleteMySubmissionNotLoggedIn

        Evergreen.V1.Submission.DeleteMySubmissionWrongWikiSession ->
            Evergreen.V2.Submission.DeleteMySubmissionWrongWikiSession

        Evergreen.V1.Submission.DeleteMySubmissionWikiNotFound ->
            Evergreen.V2.Submission.DeleteMySubmissionWikiNotFound

        Evergreen.V1.Submission.DeleteMySubmissionWikiInactive ->
            Evergreen.V2.Submission.DeleteMySubmissionWikiInactive

        Evergreen.V1.Submission.DeleteMySubmissionApproved ->
            Evergreen.V2.Submission.DeleteMySubmissionApproved

        Evergreen.V1.Submission.DeleteMySubmissionNotFound ->
            Evergreen.V2.Submission.DeleteMySubmissionNotFound

        Evergreen.V1.Submission.DeleteMySubmissionForbidden ->
            Evergreen.V2.Submission.DeleteMySubmissionForbidden


migrate_Submission_DeletePublishedPageImmediatelyError : Evergreen.V1.Submission.DeletePublishedPageImmediatelyError -> Evergreen.V2.Submission.DeletePublishedPageImmediatelyError
migrate_Submission_DeletePublishedPageImmediatelyError old =
    case old of
        Evergreen.V1.Submission.DeletePublishedPageImmediatelyPrecondition p0 ->
            Evergreen.V2.Submission.DeletePublishedPageImmediatelyPrecondition (p0 |> migrate_Submission_PageDeletionPreconditionError)

        Evergreen.V1.Submission.DeletePublishedPageImmediatelyForbiddenUntrustedContributor ->
            Evergreen.V2.Submission.DeletePublishedPageImmediatelyForbiddenUntrustedContributor


migrate_Submission_DeleteReasonError : Evergreen.V1.Submission.DeleteReasonError -> Evergreen.V2.Submission.DeleteReasonError
migrate_Submission_DeleteReasonError old =
    case old of
        Evergreen.V1.Submission.ReasonRequired ->
            Evergreen.V2.Submission.ReasonRequired

        Evergreen.V1.Submission.ReasonTooLong ->
            Evergreen.V2.Submission.ReasonTooLong


migrate_Submission_DetailsError : Evergreen.V1.Submission.DetailsError -> Evergreen.V2.Submission.DetailsError
migrate_Submission_DetailsError old =
    case old of
        Evergreen.V1.Submission.DetailsNotLoggedIn ->
            Evergreen.V2.Submission.DetailsNotLoggedIn

        Evergreen.V1.Submission.DetailsWrongWikiSession ->
            Evergreen.V2.Submission.DetailsWrongWikiSession

        Evergreen.V1.Submission.DetailsWikiInactive ->
            Evergreen.V2.Submission.DetailsWikiInactive

        Evergreen.V1.Submission.DetailsNotFound ->
            Evergreen.V2.Submission.DetailsNotFound

        Evergreen.V1.Submission.DetailsForbidden ->
            Evergreen.V2.Submission.DetailsForbidden


migrate_Submission_EditSubmitSuccess : Evergreen.V1.Submission.EditSubmitSuccess -> Evergreen.V2.Submission.EditSubmitSuccess
migrate_Submission_EditSubmitSuccess old =
    case old of
        Evergreen.V1.Submission.EditPublishedImmediately ->
            Evergreen.V2.Submission.EditPublishedImmediately

        Evergreen.V1.Submission.EditSubmittedForReview p0 ->
            Evergreen.V2.Submission.EditSubmittedForReview (p0 |> migrate_Submission_Id)


migrate_Submission_Id : Evergreen.V1.Submission.Id -> Evergreen.V2.Submission.Id
migrate_Submission_Id old =
    case old of
        Evergreen.V1.Submission.Id p0 ->
            Evergreen.V2.Submission.Id p0


migrate_Submission_MyPendingSubmissionListItem : Evergreen.V1.Submission.MyPendingSubmissionListItem -> Evergreen.V2.Submission.MyPendingSubmissionListItem
migrate_Submission_MyPendingSubmissionListItem old =
    { id = old.id |> migrate_Submission_Id
    , status = old.status |> migrate_Submission_Status
    , statusLabel = old.statusLabel
    , kindLabel = old.kindLabel
    , maybePageSlug = old.maybePageSlug
    }


migrate_Submission_MyPendingSubmissionsError : Evergreen.V1.Submission.MyPendingSubmissionsError -> Evergreen.V2.Submission.MyPendingSubmissionsError
migrate_Submission_MyPendingSubmissionsError old =
    case old of
        Evergreen.V1.Submission.MyPendingSubmissionsNotLoggedIn ->
            Evergreen.V2.Submission.MyPendingSubmissionsNotLoggedIn

        Evergreen.V1.Submission.MyPendingSubmissionsWrongWikiSession ->
            Evergreen.V2.Submission.MyPendingSubmissionsWrongWikiSession

        Evergreen.V1.Submission.MyPendingSubmissionsWikiInactive ->
            Evergreen.V2.Submission.MyPendingSubmissionsWikiInactive

        Evergreen.V1.Submission.MyPendingSubmissionsForbiddenTrustedModerator ->
            Evergreen.V2.Submission.MyPendingSubmissionsForbiddenTrustedModerator


migrate_Submission_NewPageSubmitSuccess : Evergreen.V1.Submission.NewPageSubmitSuccess -> Evergreen.V2.Submission.NewPageSubmitSuccess
migrate_Submission_NewPageSubmitSuccess old =
    case old of
        Evergreen.V1.Submission.NewPagePublishedImmediately ->
            Evergreen.V2.Submission.NewPagePublishedImmediately

        Evergreen.V1.Submission.NewPageSubmittedForReview p0 ->
            Evergreen.V2.Submission.NewPageSubmittedForReview (p0 |> migrate_Submission_Id)


migrate_Submission_PageDeletionPreconditionError : Evergreen.V1.Submission.PageDeletionPreconditionError -> Evergreen.V2.Submission.PageDeletionPreconditionError
migrate_Submission_PageDeletionPreconditionError old =
    case old of
        Evergreen.V1.Submission.PageDeletionNotLoggedIn ->
            Evergreen.V2.Submission.PageDeletionNotLoggedIn

        Evergreen.V1.Submission.PageDeletionWrongWikiSession ->
            Evergreen.V2.Submission.PageDeletionWrongWikiSession

        Evergreen.V1.Submission.PageDeletionWikiNotFound ->
            Evergreen.V2.Submission.PageDeletionWikiNotFound

        Evergreen.V1.Submission.PageDeletionWikiInactive ->
            Evergreen.V2.Submission.PageDeletionWikiInactive

        Evergreen.V1.Submission.PageDeletionValidation p0 ->
            Evergreen.V2.Submission.PageDeletionValidation (p0 |> migrate_Submission_DeleteReasonError)

        Evergreen.V1.Submission.PageDeletionTargetNotPublished ->
            Evergreen.V2.Submission.PageDeletionTargetNotPublished


migrate_Submission_RejectReasonError : Evergreen.V1.Submission.RejectReasonError -> Evergreen.V2.Submission.RejectReasonError
migrate_Submission_RejectReasonError old =
    case old of
        Evergreen.V1.Submission.RejectReasonEmpty ->
            Evergreen.V2.Submission.RejectReasonEmpty

        Evergreen.V1.Submission.RejectReasonTooLong ->
            Evergreen.V2.Submission.RejectReasonTooLong


migrate_Submission_RejectSubmissionError : Evergreen.V1.Submission.RejectSubmissionError -> Evergreen.V2.Submission.RejectSubmissionError
migrate_Submission_RejectSubmissionError old =
    case old of
        Evergreen.V1.Submission.RejectNotLoggedIn ->
            Evergreen.V2.Submission.RejectNotLoggedIn

        Evergreen.V1.Submission.RejectWrongWikiSession ->
            Evergreen.V2.Submission.RejectWrongWikiSession

        Evergreen.V1.Submission.RejectForbidden ->
            Evergreen.V2.Submission.RejectForbidden

        Evergreen.V1.Submission.RejectWikiNotFound ->
            Evergreen.V2.Submission.RejectWikiNotFound

        Evergreen.V1.Submission.RejectWikiInactive ->
            Evergreen.V2.Submission.RejectWikiInactive

        Evergreen.V1.Submission.RejectSubmissionNotFound ->
            Evergreen.V2.Submission.RejectSubmissionNotFound

        Evergreen.V1.Submission.RejectNotPending ->
            Evergreen.V2.Submission.RejectNotPending

        Evergreen.V1.Submission.RejectReasonInvalid p0 ->
            Evergreen.V2.Submission.RejectReasonInvalid (p0 |> migrate_Submission_RejectReasonError)


migrate_Submission_RequestChangesSubmissionError : Evergreen.V1.Submission.RequestChangesSubmissionError -> Evergreen.V2.Submission.RequestChangesSubmissionError
migrate_Submission_RequestChangesSubmissionError old =
    case old of
        Evergreen.V1.Submission.RequestChangesNotLoggedIn ->
            Evergreen.V2.Submission.RequestChangesNotLoggedIn

        Evergreen.V1.Submission.RequestChangesWrongWikiSession ->
            Evergreen.V2.Submission.RequestChangesWrongWikiSession

        Evergreen.V1.Submission.RequestChangesForbidden ->
            Evergreen.V2.Submission.RequestChangesForbidden

        Evergreen.V1.Submission.RequestChangesWikiNotFound ->
            Evergreen.V2.Submission.RequestChangesWikiNotFound

        Evergreen.V1.Submission.RequestChangesWikiInactive ->
            Evergreen.V2.Submission.RequestChangesWikiInactive

        Evergreen.V1.Submission.RequestChangesSubmissionNotFound ->
            Evergreen.V2.Submission.RequestChangesSubmissionNotFound

        Evergreen.V1.Submission.RequestChangesNotPending ->
            Evergreen.V2.Submission.RequestChangesNotPending

        Evergreen.V1.Submission.RequestChangesGuidanceInvalid p0 ->
            Evergreen.V2.Submission.RequestChangesGuidanceInvalid (p0 |> migrate_Submission_RejectReasonError)


migrate_Submission_RequestPublishedPageDeletionError : Evergreen.V1.Submission.RequestPublishedPageDeletionError -> Evergreen.V2.Submission.RequestPublishedPageDeletionError
migrate_Submission_RequestPublishedPageDeletionError old =
    case old of
        Evergreen.V1.Submission.RequestPublishedPageDeletionPrecondition p0 ->
            Evergreen.V2.Submission.RequestPublishedPageDeletionPrecondition (p0 |> migrate_Submission_PageDeletionPreconditionError)

        Evergreen.V1.Submission.RequestPublishedPageDeletionForbiddenTrustedModerator ->
            Evergreen.V2.Submission.RequestPublishedPageDeletionForbiddenTrustedModerator

        Evergreen.V1.Submission.RequestPublishedPageDeletionSubmitDraftStepFailed p0 ->
            Evergreen.V2.Submission.RequestPublishedPageDeletionSubmitDraftStepFailed (p0 |> migrate_Submission_SubmitDraftForReviewError)


migrate_Submission_ReviewQueueError : Evergreen.V1.Submission.ReviewQueueError -> Evergreen.V2.Submission.ReviewQueueError
migrate_Submission_ReviewQueueError old =
    case old of
        Evergreen.V1.Submission.ReviewQueueNotLoggedIn ->
            Evergreen.V2.Submission.ReviewQueueNotLoggedIn

        Evergreen.V1.Submission.ReviewQueueWrongWikiSession ->
            Evergreen.V2.Submission.ReviewQueueWrongWikiSession

        Evergreen.V1.Submission.ReviewQueueForbidden ->
            Evergreen.V2.Submission.ReviewQueueForbidden

        Evergreen.V1.Submission.ReviewQueueWikiInactive ->
            Evergreen.V2.Submission.ReviewQueueWikiInactive


migrate_Submission_ReviewQueueItem : Evergreen.V1.Submission.ReviewQueueItem -> Evergreen.V2.Submission.ReviewQueueItem
migrate_Submission_ReviewQueueItem old =
    { id = old.id |> migrate_Submission_Id
    , kindLabel = old.kindLabel
    , authorDisplay = old.authorDisplay
    , maybePageSlug = old.maybePageSlug
    }


migrate_Submission_SaveNewPageDraftError : Evergreen.V1.Submission.SaveNewPageDraftError -> Evergreen.V2.Submission.SaveNewPageDraftError
migrate_Submission_SaveNewPageDraftError old =
    case old of
        Evergreen.V1.Submission.SaveNewPageDraftNotLoggedIn ->
            Evergreen.V2.Submission.SaveNewPageDraftNotLoggedIn

        Evergreen.V1.Submission.SaveNewPageDraftWrongWikiSession ->
            Evergreen.V2.Submission.SaveNewPageDraftWrongWikiSession

        Evergreen.V1.Submission.SaveNewPageDraftValidation p0 ->
            Evergreen.V2.Submission.SaveNewPageDraftValidation (p0 |> migrate_Submission_ValidationError)

        Evergreen.V1.Submission.SaveNewPageDraftSlugReserved ->
            Evergreen.V2.Submission.SaveNewPageDraftSlugReserved

        Evergreen.V1.Submission.SaveNewPageDraftNotFound ->
            Evergreen.V2.Submission.SaveNewPageDraftNotFound

        Evergreen.V1.Submission.SaveNewPageDraftForbidden ->
            Evergreen.V2.Submission.SaveNewPageDraftForbidden

        Evergreen.V1.Submission.SaveNewPageDraftWikiNotFound ->
            Evergreen.V2.Submission.SaveNewPageDraftWikiNotFound

        Evergreen.V1.Submission.SaveNewPageDraftWikiInactive ->
            Evergreen.V2.Submission.SaveNewPageDraftWikiInactive


migrate_Submission_SavePageDeleteDraftError : Evergreen.V1.Submission.SavePageDeleteDraftError -> Evergreen.V2.Submission.SavePageDeleteDraftError
migrate_Submission_SavePageDeleteDraftError old =
    case old of
        Evergreen.V1.Submission.SavePageDeleteDraftNotLoggedIn ->
            Evergreen.V2.Submission.SavePageDeleteDraftNotLoggedIn

        Evergreen.V1.Submission.SavePageDeleteDraftWrongWikiSession ->
            Evergreen.V2.Submission.SavePageDeleteDraftWrongWikiSession

        Evergreen.V1.Submission.SavePageDeleteDraftReasonInvalid p0 ->
            Evergreen.V2.Submission.SavePageDeleteDraftReasonInvalid (p0 |> migrate_Submission_DeleteReasonError)

        Evergreen.V1.Submission.SavePageDeleteDraftTargetNotPublished ->
            Evergreen.V2.Submission.SavePageDeleteDraftTargetNotPublished

        Evergreen.V1.Submission.SavePageDeleteDraftNotFound ->
            Evergreen.V2.Submission.SavePageDeleteDraftNotFound

        Evergreen.V1.Submission.SavePageDeleteDraftForbidden ->
            Evergreen.V2.Submission.SavePageDeleteDraftForbidden

        Evergreen.V1.Submission.SavePageDeleteDraftWikiNotFound ->
            Evergreen.V2.Submission.SavePageDeleteDraftWikiNotFound

        Evergreen.V1.Submission.SavePageDeleteDraftWikiInactive ->
            Evergreen.V2.Submission.SavePageDeleteDraftWikiInactive

        Evergreen.V1.Submission.SavePageDeleteDraftForbiddenTrustedModerator ->
            Evergreen.V2.Submission.SavePageDeleteDraftForbiddenTrustedModerator


migrate_Submission_SavePageEditDraftError : Evergreen.V1.Submission.SavePageEditDraftError -> Evergreen.V2.Submission.SavePageEditDraftError
migrate_Submission_SavePageEditDraftError old =
    case old of
        Evergreen.V1.Submission.SavePageEditDraftNotLoggedIn ->
            Evergreen.V2.Submission.SavePageEditDraftNotLoggedIn

        Evergreen.V1.Submission.SavePageEditDraftWrongWikiSession ->
            Evergreen.V2.Submission.SavePageEditDraftWrongWikiSession

        Evergreen.V1.Submission.SavePageEditDraftValidation p0 ->
            Evergreen.V2.Submission.SavePageEditDraftValidation (p0 |> migrate_Submission_ValidationError)

        Evergreen.V1.Submission.SavePageEditDraftTargetNotPublished ->
            Evergreen.V2.Submission.SavePageEditDraftTargetNotPublished

        Evergreen.V1.Submission.SavePageEditDraftAlreadyPendingEdit ->
            Evergreen.V2.Submission.SavePageEditDraftAlreadyPendingEdit

        Evergreen.V1.Submission.SavePageEditDraftNotFound ->
            Evergreen.V2.Submission.SavePageEditDraftNotFound

        Evergreen.V1.Submission.SavePageEditDraftForbidden ->
            Evergreen.V2.Submission.SavePageEditDraftForbidden

        Evergreen.V1.Submission.SavePageEditDraftWikiNotFound ->
            Evergreen.V2.Submission.SavePageEditDraftWikiNotFound

        Evergreen.V1.Submission.SavePageEditDraftWikiInactive ->
            Evergreen.V2.Submission.SavePageEditDraftWikiInactive


migrate_Submission_Status : Evergreen.V1.Submission.Status -> Evergreen.V2.Submission.Status
migrate_Submission_Status old =
    case old of
        Evergreen.V1.Submission.Draft ->
            Evergreen.V2.Submission.Draft

        Evergreen.V1.Submission.Pending ->
            Evergreen.V2.Submission.Pending

        Evergreen.V1.Submission.Approved ->
            Evergreen.V2.Submission.Approved

        Evergreen.V1.Submission.Rejected ->
            Evergreen.V2.Submission.Rejected

        Evergreen.V1.Submission.NeedsRevision ->
            Evergreen.V2.Submission.NeedsRevision


migrate_Submission_SubmitDraftForReviewError : Evergreen.V1.Submission.SubmitDraftForReviewError -> Evergreen.V2.Submission.SubmitDraftForReviewError
migrate_Submission_SubmitDraftForReviewError old =
    case old of
        Evergreen.V1.Submission.SubmitDraftForReviewNotLoggedIn ->
            Evergreen.V2.Submission.SubmitDraftForReviewNotLoggedIn

        Evergreen.V1.Submission.SubmitDraftForReviewWrongWikiSession ->
            Evergreen.V2.Submission.SubmitDraftForReviewWrongWikiSession

        Evergreen.V1.Submission.SubmitDraftForReviewWikiNotFound ->
            Evergreen.V2.Submission.SubmitDraftForReviewWikiNotFound

        Evergreen.V1.Submission.SubmitDraftForReviewWikiInactive ->
            Evergreen.V2.Submission.SubmitDraftForReviewWikiInactive

        Evergreen.V1.Submission.SubmitDraftForReviewNotDraft ->
            Evergreen.V2.Submission.SubmitDraftForReviewNotDraft

        Evergreen.V1.Submission.SubmitDraftForReviewValidation p0 ->
            Evergreen.V2.Submission.SubmitDraftForReviewValidation (p0 |> migrate_Submission_ValidationError)

        Evergreen.V1.Submission.SubmitDraftForReviewSlugInUse ->
            Evergreen.V2.Submission.SubmitDraftForReviewSlugInUse

        Evergreen.V1.Submission.SubmitDraftForReviewPageExists ->
            Evergreen.V2.Submission.SubmitDraftForReviewPageExists

        Evergreen.V1.Submission.SubmitDraftForReviewEditTargetNotPublished ->
            Evergreen.V2.Submission.SubmitDraftForReviewEditTargetNotPublished

        Evergreen.V1.Submission.SubmitDraftForReviewEditAlreadyPending ->
            Evergreen.V2.Submission.SubmitDraftForReviewEditAlreadyPending

        Evergreen.V1.Submission.SubmitDraftForReviewDeleteTargetNotPublished ->
            Evergreen.V2.Submission.SubmitDraftForReviewDeleteTargetNotPublished

        Evergreen.V1.Submission.SubmitDraftForReviewDeleteReasonInvalid p0 ->
            Evergreen.V2.Submission.SubmitDraftForReviewDeleteReasonInvalid (p0 |> migrate_Submission_DeleteReasonError)

        Evergreen.V1.Submission.SubmitDraftForReviewNotFound ->
            Evergreen.V2.Submission.SubmitDraftForReviewNotFound

        Evergreen.V1.Submission.SubmitDraftForReviewForbidden ->
            Evergreen.V2.Submission.SubmitDraftForReviewForbidden

        Evergreen.V1.Submission.SubmitDraftForReviewDeleteForbiddenTrustedModerator ->
            Evergreen.V2.Submission.SubmitDraftForReviewDeleteForbiddenTrustedModerator


migrate_Submission_SubmitNewPageError : Evergreen.V1.Submission.SubmitNewPageError -> Evergreen.V2.Submission.SubmitNewPageError
migrate_Submission_SubmitNewPageError old =
    case old of
        Evergreen.V1.Submission.NotLoggedIn ->
            Evergreen.V2.Submission.NotLoggedIn

        Evergreen.V1.Submission.WrongWikiSession ->
            Evergreen.V2.Submission.WrongWikiSession

        Evergreen.V1.Submission.WikiNotFound ->
            Evergreen.V2.Submission.WikiNotFound

        Evergreen.V1.Submission.WikiInactive ->
            Evergreen.V2.Submission.WikiInactive

        Evergreen.V1.Submission.Validation p0 ->
            Evergreen.V2.Submission.Validation (p0 |> migrate_Submission_ValidationError)

        Evergreen.V1.Submission.SlugAlreadyInUse ->
            Evergreen.V2.Submission.SlugAlreadyInUse


migrate_Submission_SubmitPageEditError : Evergreen.V1.Submission.SubmitPageEditError -> Evergreen.V2.Submission.SubmitPageEditError
migrate_Submission_SubmitPageEditError old =
    case old of
        Evergreen.V1.Submission.EditNotLoggedIn ->
            Evergreen.V2.Submission.EditNotLoggedIn

        Evergreen.V1.Submission.EditWrongWikiSession ->
            Evergreen.V2.Submission.EditWrongWikiSession

        Evergreen.V1.Submission.EditWikiNotFound ->
            Evergreen.V2.Submission.EditWikiNotFound

        Evergreen.V1.Submission.EditWikiInactive ->
            Evergreen.V2.Submission.EditWikiInactive

        Evergreen.V1.Submission.EditValidation p0 ->
            Evergreen.V2.Submission.EditValidation (p0 |> migrate_Submission_ValidationError)

        Evergreen.V1.Submission.EditTargetPageNotPublished ->
            Evergreen.V2.Submission.EditTargetPageNotPublished

        Evergreen.V1.Submission.EditAlreadyPendingForAuthor ->
            Evergreen.V2.Submission.EditAlreadyPendingForAuthor


migrate_Submission_ValidationError : Evergreen.V1.Submission.ValidationError -> Evergreen.V2.Submission.ValidationError
migrate_Submission_ValidationError old =
    case old of
        Evergreen.V1.Submission.SlugEmpty ->
            Evergreen.V2.Submission.SlugEmpty

        Evergreen.V1.Submission.SlugTooLong ->
            Evergreen.V2.Submission.SlugTooLong

        Evergreen.V1.Submission.SlugInvalidChars ->
            Evergreen.V2.Submission.SlugInvalidChars

        Evergreen.V1.Submission.BodyEmpty ->
            Evergreen.V2.Submission.BodyEmpty


migrate_Submission_WithdrawSubmissionError : Evergreen.V1.Submission.WithdrawSubmissionError -> Evergreen.V2.Submission.WithdrawSubmissionError
migrate_Submission_WithdrawSubmissionError old =
    case old of
        Evergreen.V1.Submission.WithdrawSubmissionNotLoggedIn ->
            Evergreen.V2.Submission.WithdrawSubmissionNotLoggedIn

        Evergreen.V1.Submission.WithdrawSubmissionWrongWikiSession ->
            Evergreen.V2.Submission.WithdrawSubmissionWrongWikiSession

        Evergreen.V1.Submission.WithdrawSubmissionWikiNotFound ->
            Evergreen.V2.Submission.WithdrawSubmissionWikiNotFound

        Evergreen.V1.Submission.WithdrawSubmissionWikiInactive ->
            Evergreen.V2.Submission.WithdrawSubmissionWikiInactive

        Evergreen.V1.Submission.WithdrawSubmissionNotPendingOrNeedsRevision ->
            Evergreen.V2.Submission.WithdrawSubmissionNotPendingOrNeedsRevision

        Evergreen.V1.Submission.WithdrawSubmissionNotFound ->
            Evergreen.V2.Submission.WithdrawSubmissionNotFound

        Evergreen.V1.Submission.WithdrawSubmissionForbidden ->
            Evergreen.V2.Submission.WithdrawSubmissionForbidden


migrate_Types_BackendMsg : Evergreen.V1.Types.BackendMsg -> Evergreen.V2.Types.BackendMsg
migrate_Types_BackendMsg old =
    case old of
        Evergreen.V1.Types.ToBackendGotTime p0 p1 p2 p3 ->
            Evergreen.V2.Types.ToBackendGotTime p0 p1 (p2 |> migrate_Types_ToBackend) p3


migrate_Types_CreateHostedWikiPayload : Evergreen.V1.Types.CreateHostedWikiPayload -> Evergreen.V2.Types.CreateHostedWikiPayload
migrate_Types_CreateHostedWikiPayload old =
    old


migrate_Types_FrontendMsg : Evergreen.V1.Types.FrontendMsg -> Evergreen.V2.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V1.Types.UrlClicked p0 ->
            Evergreen.V2.Types.UrlClicked p0

        Evergreen.V1.Types.UrlChanged p0 ->
            Evergreen.V2.Types.UrlChanged p0

        Evergreen.V1.Types.UrlFragmentScrollDone ->
            Evergreen.V2.Types.UrlFragmentScrollDone

        Evergreen.V1.Types.ColorThemeToggled ->
            Evergreen.V2.Types.ColorThemeToggled

        Evergreen.V1.Types.ColorThemeFromJs p0 ->
            Evergreen.V2.Types.ColorThemeFromJs (p0 |> Maybe.map migrate_ColorTheme_Incoming)

        Evergreen.V1.Types.RegisterFormUsernameChanged p0 ->
            Evergreen.V2.Types.RegisterFormUsernameChanged p0

        Evergreen.V1.Types.RegisterFormPasswordChanged p0 ->
            Evergreen.V2.Types.RegisterFormPasswordChanged p0

        Evergreen.V1.Types.RegisterFormSubmitted ->
            Evergreen.V2.Types.RegisterFormSubmitted

        Evergreen.V1.Types.LoginFormUsernameChanged p0 ->
            Evergreen.V2.Types.LoginFormUsernameChanged p0

        Evergreen.V1.Types.LoginFormPasswordChanged p0 ->
            Evergreen.V2.Types.LoginFormPasswordChanged p0

        Evergreen.V1.Types.LoginFormSubmitted ->
            Evergreen.V2.Types.LoginFormSubmitted

        Evergreen.V1.Types.ContributorLogoutWiki p0 ->
            Evergreen.V2.Types.ContributorLogoutWiki p0

        Evergreen.V1.Types.NewPageSubmitMarkdownChanged p0 ->
            Evergreen.V2.Types.NewPageSubmitMarkdownChanged p0

        Evergreen.V1.Types.NewPageSubmitSlugChanged p0 ->
            Evergreen.V2.Types.NewPageSubmitSlugChanged p0

        Evergreen.V1.Types.NewPageSubmitFormSubmitted ->
            Evergreen.V2.Types.NewPageSubmitFormSubmitted

        Evergreen.V1.Types.PageEditSubmitMarkdownChanged p0 ->
            Evergreen.V2.Types.PageEditSubmitMarkdownChanged p0

        Evergreen.V1.Types.PageEditSubmitFormSubmitted ->
            Evergreen.V2.Types.PageEditSubmitFormSubmitted

        Evergreen.V1.Types.PageDeleteSubmitReasonChanged p0 ->
            Evergreen.V2.Types.PageDeleteSubmitReasonChanged p0

        Evergreen.V1.Types.PageDeleteRequestDeletionSubmitted ->
            Evergreen.V2.Types.PageDeleteRequestDeletionSubmitted

        Evergreen.V1.Types.PageDeletePublishedImmediatelySubmitted ->
            Evergreen.V2.Types.PageDeletePublishedImmediatelySubmitted

        Evergreen.V1.Types.NewPageSaveDraftClicked ->
            Evergreen.V2.Types.NewPageSaveDraftClicked

        Evergreen.V1.Types.PageEditSaveDraftClicked ->
            Evergreen.V2.Types.PageEditSaveDraftClicked

        Evergreen.V1.Types.PageDeleteSaveDraftClicked ->
            Evergreen.V2.Types.PageDeleteSaveDraftClicked

        Evergreen.V1.Types.SubmissionDetailNewMarkdownChanged p0 ->
            Evergreen.V2.Types.SubmissionDetailNewMarkdownChanged p0

        Evergreen.V1.Types.SubmissionDetailNewPageSlugChanged p0 ->
            Evergreen.V2.Types.SubmissionDetailNewPageSlugChanged p0

        Evergreen.V1.Types.SubmissionDetailSaveDraftClicked ->
            Evergreen.V2.Types.SubmissionDetailSaveDraftClicked

        Evergreen.V1.Types.SubmissionDetailSubmitForReviewClicked ->
            Evergreen.V2.Types.SubmissionDetailSubmitForReviewClicked

        Evergreen.V1.Types.SubmissionDetailWithdrawClicked ->
            Evergreen.V2.Types.SubmissionDetailWithdrawClicked

        Evergreen.V1.Types.SubmissionDetailDeleteClicked ->
            Evergreen.V2.Types.SubmissionDetailDeleteClicked

        Evergreen.V1.Types.ReviewDecisionChanged p0 ->
            Evergreen.V2.Types.ReviewDecisionChanged (p0 |> migrate_Types_ReviewDecision)

        Evergreen.V1.Types.ReviewDecisionSubmitted ->
            Evergreen.V2.Types.ReviewDecisionSubmitted

        Evergreen.V1.Types.ReviewRejectReasonChanged p0 ->
            Evergreen.V2.Types.ReviewRejectReasonChanged p0

        Evergreen.V1.Types.ReviewRequestChangesNoteChanged p0 ->
            Evergreen.V2.Types.ReviewRequestChangesNoteChanged p0

        Evergreen.V1.Types.WikiAdminPromoteToTrustedClicked p0 ->
            Evergreen.V2.Types.WikiAdminPromoteToTrustedClicked p0

        Evergreen.V1.Types.WikiAdminDemoteToContributorClicked p0 ->
            Evergreen.V2.Types.WikiAdminDemoteToContributorClicked p0

        Evergreen.V1.Types.WikiAdminGrantAdminClicked p0 ->
            Evergreen.V2.Types.WikiAdminGrantAdminClicked p0

        Evergreen.V1.Types.WikiAdminRevokeAdminClicked p0 ->
            Evergreen.V2.Types.WikiAdminRevokeAdminClicked p0

        Evergreen.V1.Types.WikiAdminAuditFilterActorChanged p0 ->
            Evergreen.V2.Types.WikiAdminAuditFilterActorChanged p0

        Evergreen.V1.Types.WikiAdminAuditFilterPageChanged p0 ->
            Evergreen.V2.Types.WikiAdminAuditFilterPageChanged p0

        Evergreen.V1.Types.WikiAdminAuditFilterTypeTagToggled p0 p1 ->
            Evergreen.V2.Types.WikiAdminAuditFilterTypeTagToggled (p0 |> migrate_WikiAuditLog_AuditEventKindFilterTag)
                p1

        Evergreen.V1.Types.HostAdminLoginPasswordChanged p0 ->
            Evergreen.V2.Types.HostAdminLoginPasswordChanged p0

        Evergreen.V1.Types.HostAdminLoginSubmitted ->
            Evergreen.V2.Types.HostAdminLoginSubmitted

        Evergreen.V1.Types.HostAdminCreateWikiSlugChanged p0 ->
            Evergreen.V2.Types.HostAdminCreateWikiSlugChanged p0

        Evergreen.V1.Types.HostAdminCreateWikiNameChanged p0 ->
            Evergreen.V2.Types.HostAdminCreateWikiNameChanged p0

        Evergreen.V1.Types.HostAdminCreateWikiInitialAdminUsernameChanged p0 ->
            Evergreen.V2.Types.HostAdminCreateWikiInitialAdminUsernameChanged p0

        Evergreen.V1.Types.HostAdminCreateWikiInitialAdminPasswordChanged p0 ->
            Evergreen.V2.Types.HostAdminCreateWikiInitialAdminPasswordChanged p0

        Evergreen.V1.Types.HostAdminCreateWikiSubmitted ->
            Evergreen.V2.Types.HostAdminCreateWikiSubmitted

        Evergreen.V1.Types.HostAdminWikiDetailNameChanged p0 ->
            Evergreen.V2.Types.HostAdminWikiDetailNameChanged p0

        Evergreen.V1.Types.HostAdminWikiDetailSlugChanged p0 ->
            Evergreen.V2.Types.HostAdminWikiDetailSlugChanged p0

        Evergreen.V1.Types.HostAdminWikiDetailSummaryChanged p0 ->
            Evergreen.V2.Types.HostAdminWikiDetailSummaryChanged p0

        Evergreen.V1.Types.HostAdminWikiDetailSaveClicked ->
            Evergreen.V2.Types.HostAdminWikiDetailSaveClicked

        Evergreen.V1.Types.HostAdminWikiDetailDeactivateClicked ->
            Evergreen.V2.Types.HostAdminWikiDetailDeactivateClicked

        Evergreen.V1.Types.HostAdminWikiDetailReactivateClicked ->
            Evergreen.V2.Types.HostAdminWikiDetailReactivateClicked

        Evergreen.V1.Types.HostAdminWikiDetailDeleteConfirmChanged p0 ->
            Evergreen.V2.Types.HostAdminWikiDetailDeleteConfirmChanged p0

        Evergreen.V1.Types.HostAdminWikiDetailDeleteSubmitted ->
            Evergreen.V2.Types.HostAdminWikiDetailDeleteSubmitted

        Evergreen.V1.Types.HostAdminAuditFilterWikiChanged p0 ->
            Evergreen.V2.Types.HostAdminAuditFilterWikiChanged p0

        Evergreen.V1.Types.HostAdminAuditFilterActorChanged p0 ->
            Evergreen.V2.Types.HostAdminAuditFilterActorChanged p0

        Evergreen.V1.Types.HostAdminAuditFilterPageChanged p0 ->
            Evergreen.V2.Types.HostAdminAuditFilterPageChanged p0

        Evergreen.V1.Types.HostAdminAuditFilterTypeTagToggled p0 p1 ->
            Evergreen.V2.Types.HostAdminAuditFilterTypeTagToggled (p0 |> migrate_WikiAuditLog_AuditEventKindFilterTag)
                p1

        Evergreen.V1.Types.HostAdminDataExportClicked ->
            Evergreen.V2.Types.HostAdminDataExportClicked

        Evergreen.V1.Types.HostAdminDataImportPickRequested ->
            Evergreen.V2.Types.HostAdminDataImportPickRequested

        Evergreen.V1.Types.HostAdminDataImportFileSelected p0 ->
            Evergreen.V2.Types.HostAdminDataImportFileSelected p0

        Evergreen.V1.Types.HostAdminDataImportFileRead p0 ->
            Evergreen.V2.Types.HostAdminDataImportFileRead p0

        Evergreen.V1.Types.HostAdminWikiDataExportClicked p0 ->
            Evergreen.V2.Types.HostAdminWikiDataExportClicked p0

        Evergreen.V1.Types.HostAdminWikiDataImportPickRequested p0 ->
            Evergreen.V2.Types.HostAdminWikiDataImportPickRequested p0

        Evergreen.V1.Types.HostAdminWikiDataImportFileSelected p0 ->
            Evergreen.V2.Types.HostAdminWikiDataImportFileSelected p0

        Evergreen.V1.Types.HostAdminWikiDataImportFileRead p0 p1 ->
            Evergreen.V2.Types.HostAdminWikiDataImportFileRead p0 p1


migrate_Types_LoginContributorPayload : Evergreen.V1.Types.LoginContributorPayload -> Evergreen.V2.Types.LoginContributorPayload
migrate_Types_LoginContributorPayload old =
    old


migrate_Types_RegisterContributorPayload : Evergreen.V1.Types.RegisterContributorPayload -> Evergreen.V2.Types.RegisterContributorPayload
migrate_Types_RegisterContributorPayload old =
    old


migrate_Types_RejectSubmissionPayload : Evergreen.V1.Types.RejectSubmissionPayload -> Evergreen.V2.Types.RejectSubmissionPayload
migrate_Types_RejectSubmissionPayload old =
    old


migrate_Types_RequestSubmissionChangesPayload : Evergreen.V1.Types.RequestSubmissionChangesPayload -> Evergreen.V2.Types.RequestSubmissionChangesPayload
migrate_Types_RequestSubmissionChangesPayload old =
    old


migrate_Types_ReviewDecision : Evergreen.V1.Types.ReviewDecision -> Evergreen.V2.Types.ReviewDecision
migrate_Types_ReviewDecision old =
    case old of
        Evergreen.V1.Types.ReviewDecisionApprove ->
            Evergreen.V2.Types.ReviewDecisionApprove

        Evergreen.V1.Types.ReviewDecisionRequestChanges ->
            Evergreen.V2.Types.ReviewDecisionRequestChanges

        Evergreen.V1.Types.ReviewDecisionReject ->
            Evergreen.V2.Types.ReviewDecisionReject


migrate_Types_SubmitNewPagePayload : Evergreen.V1.Types.SubmitNewPagePayload -> Evergreen.V2.Types.SubmitNewPagePayload
migrate_Types_SubmitNewPagePayload old =
    old


migrate_Types_ToBackend : Evergreen.V1.Types.ToBackend -> Evergreen.V2.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V1.Types.RequestWikiCatalog ->
            Evergreen.V2.Types.RequestWikiCatalog

        Evergreen.V1.Types.RequestWikiFrontendDetails p0 ->
            Evergreen.V2.Types.RequestWikiFrontendDetails p0

        Evergreen.V1.Types.RequestPageFrontendDetails p0 p1 ->
            Evergreen.V2.Types.RequestPageFrontendDetails p0 p1

        Evergreen.V1.Types.RequestMyPendingSubmissions p0 ->
            Evergreen.V2.Types.RequestMyPendingSubmissions p0

        Evergreen.V1.Types.RequestReviewQueue p0 ->
            Evergreen.V2.Types.RequestReviewQueue p0

        Evergreen.V1.Types.RequestReviewSubmissionDetail p0 p1 ->
            Evergreen.V2.Types.RequestReviewSubmissionDetail p0 p1

        Evergreen.V1.Types.RequestWikiUsers p0 ->
            Evergreen.V2.Types.RequestWikiUsers p0

        Evergreen.V1.Types.RequestWikiAuditLog p0 p1 ->
            Evergreen.V2.Types.RequestWikiAuditLog p0 (p1 |> migrate_WikiAuditLog_AuditLogFilter)

        Evergreen.V1.Types.PromoteContributorToTrusted p0 p1 ->
            Evergreen.V2.Types.PromoteContributorToTrusted p0 p1

        Evergreen.V1.Types.DemoteTrustedToContributor p0 p1 ->
            Evergreen.V2.Types.DemoteTrustedToContributor p0 p1

        Evergreen.V1.Types.GrantWikiAdmin p0 p1 ->
            Evergreen.V2.Types.GrantWikiAdmin p0 p1

        Evergreen.V1.Types.RevokeWikiAdmin p0 p1 ->
            Evergreen.V2.Types.RevokeWikiAdmin p0 p1

        Evergreen.V1.Types.RequestSubmissionDetails p0 p1 ->
            Evergreen.V2.Types.RequestSubmissionDetails p0 p1

        Evergreen.V1.Types.RegisterContributor p0 p1 ->
            Evergreen.V2.Types.RegisterContributor p0
                (p1 |> migrate_Types_RegisterContributorPayload)

        Evergreen.V1.Types.LoginContributor p0 p1 ->
            Evergreen.V2.Types.LoginContributor p0 (p1 |> migrate_Types_LoginContributorPayload)

        Evergreen.V1.Types.LogoutContributor p0 ->
            Evergreen.V2.Types.LogoutContributor p0

        Evergreen.V1.Types.SubmitNewPage p0 p1 ->
            Evergreen.V2.Types.SubmitNewPage p0 (p1 |> migrate_Types_SubmitNewPagePayload)

        Evergreen.V1.Types.SubmitPageEdit p0 p1 p2 ->
            Evergreen.V2.Types.SubmitPageEdit p0 p1 p2

        Evergreen.V1.Types.RequestPublishedPageDeletion p0 p1 p2 ->
            Evergreen.V2.Types.RequestPublishedPageDeletion p0 p1 p2

        Evergreen.V1.Types.DeletePublishedPageImmediately p0 p1 p2 ->
            Evergreen.V2.Types.DeletePublishedPageImmediately p0 p1 p2

        Evergreen.V1.Types.SaveNewPageDraft p0 p1 ->
            Evergreen.V2.Types.SaveNewPageDraft p0 p1

        Evergreen.V1.Types.SavePageEditDraft p0 p1 ->
            Evergreen.V2.Types.SavePageEditDraft p0 p1

        Evergreen.V1.Types.SavePageDeleteDraft p0 p1 ->
            Evergreen.V2.Types.SavePageDeleteDraft p0 p1

        Evergreen.V1.Types.SubmitDraftForReview p0 p1 ->
            Evergreen.V2.Types.SubmitDraftForReview p0 p1

        Evergreen.V1.Types.WithdrawSubmission p0 p1 ->
            Evergreen.V2.Types.WithdrawSubmission p0 p1

        Evergreen.V1.Types.DeleteMySubmission p0 p1 ->
            Evergreen.V2.Types.DeleteMySubmission p0 p1

        Evergreen.V1.Types.ApproveSubmission p0 p1 ->
            Evergreen.V2.Types.ApproveSubmission p0 p1

        Evergreen.V1.Types.RejectSubmission p0 p1 ->
            Evergreen.V2.Types.RejectSubmission p0 (p1 |> migrate_Types_RejectSubmissionPayload)

        Evergreen.V1.Types.RequestSubmissionChanges p0 p1 ->
            Evergreen.V2.Types.RequestSubmissionChanges p0
                (p1 |> migrate_Types_RequestSubmissionChangesPayload)

        Evergreen.V1.Types.HostAdminLogin p0 ->
            Evergreen.V2.Types.HostAdminLogin p0

        Evergreen.V1.Types.RequestHostWikiList ->
            Evergreen.V2.Types.RequestHostWikiList

        Evergreen.V1.Types.RequestHostAuditLog p0 ->
            Evergreen.V2.Types.RequestHostAuditLog (p0 |> migrate_WikiAuditLog_HostAuditLogFilter)

        Evergreen.V1.Types.RequestHostWikiDetail p0 ->
            Evergreen.V2.Types.RequestHostWikiDetail p0

        Evergreen.V1.Types.CreateHostedWiki p0 ->
            Evergreen.V2.Types.CreateHostedWiki (p0 |> migrate_Types_CreateHostedWikiPayload)

        Evergreen.V1.Types.UpdateHostedWikiMetadata p0 p1 ->
            Evergreen.V2.Types.UpdateHostedWikiMetadata p0
                (p1 |> migrate_Types_UpdateHostedWikiMetadataPayload)

        Evergreen.V1.Types.DeactivateHostedWiki p0 ->
            Evergreen.V2.Types.DeactivateHostedWiki p0

        Evergreen.V1.Types.ReactivateHostedWiki p0 ->
            Evergreen.V2.Types.ReactivateHostedWiki p0

        Evergreen.V1.Types.DeleteHostedWiki p0 p1 ->
            Evergreen.V2.Types.DeleteHostedWiki p0 p1

        Evergreen.V1.Types.RequestHostAdminDataExport ->
            Evergreen.V2.Types.RequestHostAdminDataExport

        Evergreen.V1.Types.ImportHostAdminDataSnapshot p0 ->
            Evergreen.V2.Types.ImportHostAdminDataSnapshot p0

        Evergreen.V1.Types.RequestHostAdminWikiDataExport p0 ->
            Evergreen.V2.Types.RequestHostAdminWikiDataExport p0

        Evergreen.V1.Types.ImportHostAdminWikiDataSnapshot p0 p1 ->
            Evergreen.V2.Types.ImportHostAdminWikiDataSnapshot p0 p1

        Evergreen.V1.Types.ImportHostAdminWikiDataSnapshotAuto p0 ->
            Evergreen.V2.Types.ImportHostAdminWikiDataSnapshotAuto p0


migrate_Types_ToFrontend : Evergreen.V1.Types.ToFrontend -> Evergreen.V2.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V1.Types.WikiCatalogResponse p0 ->
            Evergreen.V2.Types.WikiCatalogResponse p0

        Evergreen.V1.Types.WikiFrontendDetailsResponse p0 p1 ->
            Evergreen.V2.Types.WikiFrontendDetailsResponse p0 p1

        Evergreen.V1.Types.PageFrontendDetailsResponse p0 p1 p2 ->
            Evergreen.V2.Types.PageFrontendDetailsResponse p0 p1 p2

        Evergreen.V1.Types.MyPendingSubmissionsResponse p0 p1 ->
            Evergreen.V2.Types.MyPendingSubmissionsResponse p0
                (p1 |> Result.mapError migrate_Submission_MyPendingSubmissionsError >> Result.map (List.map migrate_Submission_MyPendingSubmissionListItem))

        Evergreen.V1.Types.ReviewQueueResponse p0 p1 ->
            Evergreen.V2.Types.ReviewQueueResponse p0
                (p1 |> Result.mapError migrate_Submission_ReviewQueueError >> Result.map (List.map migrate_Submission_ReviewQueueItem))

        Evergreen.V1.Types.ReviewSubmissionDetailResponse p0 p1 p2 ->
            Evergreen.V2.Types.ReviewSubmissionDetailResponse p0
                p1
                (p2 |> Result.mapError migrate_SubmissionReviewDetail_ReviewSubmissionDetailError >> Result.map migrate_SubmissionReviewDetail_SubmissionReviewDetail)

        Evergreen.V1.Types.WikiUsersResponse p0 p1 ->
            Evergreen.V2.Types.WikiUsersResponse p0
                (p1 |> Result.mapError migrate_WikiAdminUsers_Error >> Result.map (List.map migrate_WikiAdminUsers_ListedUser))

        Evergreen.V1.Types.WikiAuditLogResponse p0 p1 p2 ->
            Evergreen.V2.Types.WikiAuditLogResponse p0
                (p1 |> migrate_WikiAuditLog_AuditLogFilter)
                (p2 |> Result.mapError migrate_WikiAuditLog_Error >> Result.map (List.map migrate_WikiAuditLog_AuditEvent))

        Evergreen.V1.Types.PromoteContributorToTrustedResponse p0 p1 ->
            Evergreen.V2.Types.PromoteContributorToTrustedResponse p0
                (p1 |> Result.mapError migrate_WikiAdminUsers_PromoteContributorError)

        Evergreen.V1.Types.DemoteTrustedToContributorResponse p0 p1 ->
            Evergreen.V2.Types.DemoteTrustedToContributorResponse p0
                (p1 |> Result.mapError migrate_WikiAdminUsers_DemoteTrustedError)

        Evergreen.V1.Types.GrantWikiAdminResponse p0 p1 ->
            Evergreen.V2.Types.GrantWikiAdminResponse p0
                (p1 |> Result.mapError migrate_WikiAdminUsers_GrantTrustedToAdminError)

        Evergreen.V1.Types.RevokeWikiAdminResponse p0 p1 ->
            Evergreen.V2.Types.RevokeWikiAdminResponse p0
                (p1 |> Result.mapError migrate_WikiAdminUsers_RevokeAdminError)

        Evergreen.V1.Types.SubmissionDetailsResponse p0 p1 p2 ->
            Evergreen.V2.Types.SubmissionDetailsResponse p0
                p1
                (p2 |> Result.mapError migrate_Submission_DetailsError >> Result.map migrate_Submission_ContributorView)

        Evergreen.V1.Types.RegisterContributorResponse p0 p1 ->
            Evergreen.V2.Types.RegisterContributorResponse p0
                (p1 |> Result.mapError migrate_ContributorAccount_RegisterContributorError >> Result.map migrate_WikiRole_WikiRole)

        Evergreen.V1.Types.LoginContributorResponse p0 p1 ->
            Evergreen.V2.Types.LoginContributorResponse p0
                (p1 |> Result.mapError migrate_ContributorAccount_LoginContributorError >> Result.map migrate_WikiRole_WikiRole)

        Evergreen.V1.Types.LogoutContributorResponse p0 ->
            Evergreen.V2.Types.LogoutContributorResponse p0

        Evergreen.V1.Types.SubmitNewPageResponse p0 p1 ->
            Evergreen.V2.Types.SubmitNewPageResponse p0
                (p1 |> Result.mapError migrate_Submission_SubmitNewPageError >> Result.map migrate_Submission_NewPageSubmitSuccess)

        Evergreen.V1.Types.SubmitPageEditResponse p0 p1 ->
            Evergreen.V2.Types.SubmitPageEditResponse p0
                (p1 |> Result.mapError migrate_Submission_SubmitPageEditError >> Result.map migrate_Submission_EditSubmitSuccess)

        Evergreen.V1.Types.RequestPublishedPageDeletionResponse p0 p1 ->
            Evergreen.V2.Types.RequestPublishedPageDeletionResponse p0
                (p1 |> Result.mapError migrate_Submission_RequestPublishedPageDeletionError >> Result.map migrate_Submission_Id)

        Evergreen.V1.Types.DeletePublishedPageImmediatelyResponse p0 p1 ->
            Evergreen.V2.Types.DeletePublishedPageImmediatelyResponse p0
                (p1 |> Result.mapError migrate_Submission_DeletePublishedPageImmediatelyError)

        Evergreen.V1.Types.SaveNewPageDraftResponse p0 p1 ->
            Evergreen.V2.Types.SaveNewPageDraftResponse p0
                (p1 |> Result.mapError migrate_Submission_SaveNewPageDraftError >> Result.map migrate_Submission_Id)

        Evergreen.V1.Types.SavePageEditDraftResponse p0 p1 ->
            Evergreen.V2.Types.SavePageEditDraftResponse p0
                (p1 |> Result.mapError migrate_Submission_SavePageEditDraftError >> Result.map migrate_Submission_Id)

        Evergreen.V1.Types.SavePageDeleteDraftResponse p0 p1 ->
            Evergreen.V2.Types.SavePageDeleteDraftResponse p0
                (p1 |> Result.mapError migrate_Submission_SavePageDeleteDraftError >> Result.map migrate_Submission_Id)

        Evergreen.V1.Types.SubmitDraftForReviewResponse p0 p1 p2 ->
            Evergreen.V2.Types.SubmitDraftForReviewResponse p0
                p1
                (p2 |> Result.mapError migrate_Submission_SubmitDraftForReviewError)

        Evergreen.V1.Types.WithdrawSubmissionResponse p0 p1 p2 ->
            Evergreen.V2.Types.WithdrawSubmissionResponse p0
                p1
                (p2 |> Result.mapError migrate_Submission_WithdrawSubmissionError)

        Evergreen.V1.Types.DeleteMySubmissionResponse p0 p1 p2 ->
            Evergreen.V2.Types.DeleteMySubmissionResponse p0
                p1
                (p2 |> Result.mapError migrate_Submission_DeleteMySubmissionError)

        Evergreen.V1.Types.ApproveSubmissionResponse p0 p1 p2 ->
            Evergreen.V2.Types.ApproveSubmissionResponse p0
                p1
                (p2 |> Result.mapError migrate_Submission_ApproveSubmissionError)

        Evergreen.V1.Types.RejectSubmissionResponse p0 p1 p2 ->
            Evergreen.V2.Types.RejectSubmissionResponse p0
                p1
                (p2 |> Result.mapError migrate_Submission_RejectSubmissionError)

        Evergreen.V1.Types.RequestSubmissionChangesResponse p0 p1 p2 ->
            Evergreen.V2.Types.RequestSubmissionChangesResponse p0
                p1
                (p2 |> Result.mapError migrate_Submission_RequestChangesSubmissionError)

        Evergreen.V1.Types.HostAdminLoginResponse p0 ->
            Evergreen.V2.Types.HostAdminLoginResponse (p0 |> Result.mapError migrate_HostAdmin_LoginError)

        Evergreen.V1.Types.HostAdminWikiListResponse p0 ->
            Evergreen.V2.Types.HostAdminWikiListResponse (p0 |> Result.mapError migrate_HostAdmin_ProtectedError)

        Evergreen.V1.Types.HostAuditLogResponse p0 p1 ->
            Evergreen.V2.Types.HostAuditLogResponse (p0 |> migrate_WikiAuditLog_HostAuditLogFilter)
                (p1 |> Result.mapError migrate_HostAdmin_ProtectedError >> Result.map (List.map migrate_WikiAuditLog_ScopedAuditEvent))

        Evergreen.V1.Types.CreateHostedWikiResponse p0 ->
            Evergreen.V2.Types.CreateHostedWikiResponse (p0 |> Result.mapError migrate_HostAdmin_CreateHostedWikiError >> Result.map migrate_Wiki_CatalogEntry)

        Evergreen.V1.Types.HostWikiDetailResponse p0 p1 ->
            Evergreen.V2.Types.HostWikiDetailResponse p0
                (p1 |> Result.mapError migrate_HostAdmin_HostWikiDetailError >> Result.map migrate_Wiki_CatalogEntry)

        Evergreen.V1.Types.UpdateHostedWikiMetadataResponse p0 p1 ->
            Evergreen.V2.Types.UpdateHostedWikiMetadataResponse p0
                (p1 |> Result.mapError migrate_HostAdmin_UpdateHostedWikiMetadataError >> Result.map migrate_Wiki_CatalogEntry)

        Evergreen.V1.Types.DeactivateHostedWikiResponse p0 p1 ->
            Evergreen.V2.Types.DeactivateHostedWikiResponse p0
                (p1 |> Result.mapError migrate_HostAdmin_WikiLifecycleError >> Result.map migrate_Wiki_CatalogEntry)

        Evergreen.V1.Types.ReactivateHostedWikiResponse p0 p1 ->
            Evergreen.V2.Types.ReactivateHostedWikiResponse p0
                (p1 |> Result.mapError migrate_HostAdmin_WikiLifecycleError >> Result.map migrate_Wiki_CatalogEntry)

        Evergreen.V1.Types.DeleteHostedWikiResponse p0 p1 ->
            Evergreen.V2.Types.DeleteHostedWikiResponse p0
                (p1 |> Result.mapError migrate_HostAdmin_DeleteHostedWikiError)

        Evergreen.V1.Types.HostAdminDataExportResponse p0 ->
            Evergreen.V2.Types.HostAdminDataExportResponse (p0 |> Result.mapError migrate_HostAdmin_DataExportError)

        Evergreen.V1.Types.HostAdminDataImportResponse p0 ->
            Evergreen.V2.Types.HostAdminDataImportResponse (p0 |> Result.mapError migrate_HostAdmin_DataImportError)

        Evergreen.V1.Types.HostAdminWikiDataExportResponse p0 p1 ->
            Evergreen.V2.Types.HostAdminWikiDataExportResponse p0
                (p1 |> Result.mapError migrate_HostAdmin_WikiDataExportError)

        Evergreen.V1.Types.HostAdminWikiDataImportResponse p0 p1 ->
            Evergreen.V2.Types.HostAdminWikiDataImportResponse p0
                (p1 |> Result.mapError migrate_HostAdmin_WikiDataImportError)

        Evergreen.V1.Types.HostAdminWikiDataImportAutoResponse p0 ->
            Evergreen.V2.Types.HostAdminWikiDataImportAutoResponse (p0 |> Result.mapError migrate_HostAdmin_WikiDataImportError)


migrate_Types_UpdateHostedWikiMetadataPayload : Evergreen.V1.Types.UpdateHostedWikiMetadataPayload -> Evergreen.V2.Types.UpdateHostedWikiMetadataPayload
migrate_Types_UpdateHostedWikiMetadataPayload old =
    old


migrate_WikiAdminUsers_DemoteTrustedError : Evergreen.V1.WikiAdminUsers.DemoteTrustedError -> Evergreen.V2.WikiAdminUsers.DemoteTrustedError
migrate_WikiAdminUsers_DemoteTrustedError old =
    case old of
        Evergreen.V1.WikiAdminUsers.DemoteNotLoggedIn ->
            Evergreen.V2.WikiAdminUsers.DemoteNotLoggedIn

        Evergreen.V1.WikiAdminUsers.DemoteWrongWikiSession ->
            Evergreen.V2.WikiAdminUsers.DemoteWrongWikiSession

        Evergreen.V1.WikiAdminUsers.DemoteForbidden ->
            Evergreen.V2.WikiAdminUsers.DemoteForbidden

        Evergreen.V1.WikiAdminUsers.DemoteWikiNotFound ->
            Evergreen.V2.WikiAdminUsers.DemoteWikiNotFound

        Evergreen.V1.WikiAdminUsers.DemoteWikiInactive ->
            Evergreen.V2.WikiAdminUsers.DemoteWikiInactive

        Evergreen.V1.WikiAdminUsers.DemoteTargetNotFound ->
            Evergreen.V2.WikiAdminUsers.DemoteTargetNotFound

        Evergreen.V1.WikiAdminUsers.DemoteTargetNotTrusted ->
            Evergreen.V2.WikiAdminUsers.DemoteTargetNotTrusted


migrate_WikiAdminUsers_Error : Evergreen.V1.WikiAdminUsers.Error -> Evergreen.V2.WikiAdminUsers.Error
migrate_WikiAdminUsers_Error old =
    case old of
        Evergreen.V1.WikiAdminUsers.NotLoggedIn ->
            Evergreen.V2.WikiAdminUsers.NotLoggedIn

        Evergreen.V1.WikiAdminUsers.WrongWikiSession ->
            Evergreen.V2.WikiAdminUsers.WrongWikiSession

        Evergreen.V1.WikiAdminUsers.Forbidden ->
            Evergreen.V2.WikiAdminUsers.Forbidden

        Evergreen.V1.WikiAdminUsers.WikiNotFound ->
            Evergreen.V2.WikiAdminUsers.WikiNotFound

        Evergreen.V1.WikiAdminUsers.WikiInactive ->
            Evergreen.V2.WikiAdminUsers.WikiInactive


migrate_WikiAdminUsers_GrantTrustedToAdminError : Evergreen.V1.WikiAdminUsers.GrantTrustedToAdminError -> Evergreen.V2.WikiAdminUsers.GrantTrustedToAdminError
migrate_WikiAdminUsers_GrantTrustedToAdminError old =
    case old of
        Evergreen.V1.WikiAdminUsers.GrantTrustedNotLoggedIn ->
            Evergreen.V2.WikiAdminUsers.GrantTrustedNotLoggedIn

        Evergreen.V1.WikiAdminUsers.GrantTrustedWrongWikiSession ->
            Evergreen.V2.WikiAdminUsers.GrantTrustedWrongWikiSession

        Evergreen.V1.WikiAdminUsers.GrantTrustedForbidden ->
            Evergreen.V2.WikiAdminUsers.GrantTrustedForbidden

        Evergreen.V1.WikiAdminUsers.GrantTrustedWikiNotFound ->
            Evergreen.V2.WikiAdminUsers.GrantTrustedWikiNotFound

        Evergreen.V1.WikiAdminUsers.GrantTrustedWikiInactive ->
            Evergreen.V2.WikiAdminUsers.GrantTrustedWikiInactive

        Evergreen.V1.WikiAdminUsers.GrantTrustedTargetNotFound ->
            Evergreen.V2.WikiAdminUsers.GrantTrustedTargetNotFound

        Evergreen.V1.WikiAdminUsers.GrantTrustedTargetNotTrusted ->
            Evergreen.V2.WikiAdminUsers.GrantTrustedTargetNotTrusted


migrate_WikiAdminUsers_ListedUser : Evergreen.V1.WikiAdminUsers.ListedUser -> Evergreen.V2.WikiAdminUsers.ListedUser
migrate_WikiAdminUsers_ListedUser old =
    { username = old.username
    , role = old.role |> migrate_WikiRole_WikiRole
    }


migrate_WikiAdminUsers_PromoteContributorError : Evergreen.V1.WikiAdminUsers.PromoteContributorError -> Evergreen.V2.WikiAdminUsers.PromoteContributorError
migrate_WikiAdminUsers_PromoteContributorError old =
    case old of
        Evergreen.V1.WikiAdminUsers.PromoteNotLoggedIn ->
            Evergreen.V2.WikiAdminUsers.PromoteNotLoggedIn

        Evergreen.V1.WikiAdminUsers.PromoteWrongWikiSession ->
            Evergreen.V2.WikiAdminUsers.PromoteWrongWikiSession

        Evergreen.V1.WikiAdminUsers.PromoteForbidden ->
            Evergreen.V2.WikiAdminUsers.PromoteForbidden

        Evergreen.V1.WikiAdminUsers.PromoteWikiNotFound ->
            Evergreen.V2.WikiAdminUsers.PromoteWikiNotFound

        Evergreen.V1.WikiAdminUsers.PromoteWikiInactive ->
            Evergreen.V2.WikiAdminUsers.PromoteWikiInactive

        Evergreen.V1.WikiAdminUsers.PromoteTargetNotFound ->
            Evergreen.V2.WikiAdminUsers.PromoteTargetNotFound

        Evergreen.V1.WikiAdminUsers.PromoteTargetNotContributor ->
            Evergreen.V2.WikiAdminUsers.PromoteTargetNotContributor


migrate_WikiAdminUsers_RevokeAdminError : Evergreen.V1.WikiAdminUsers.RevokeAdminError -> Evergreen.V2.WikiAdminUsers.RevokeAdminError
migrate_WikiAdminUsers_RevokeAdminError old =
    case old of
        Evergreen.V1.WikiAdminUsers.RevokeAdminNotLoggedIn ->
            Evergreen.V2.WikiAdminUsers.RevokeAdminNotLoggedIn

        Evergreen.V1.WikiAdminUsers.RevokeAdminWrongWikiSession ->
            Evergreen.V2.WikiAdminUsers.RevokeAdminWrongWikiSession

        Evergreen.V1.WikiAdminUsers.RevokeAdminForbidden ->
            Evergreen.V2.WikiAdminUsers.RevokeAdminForbidden

        Evergreen.V1.WikiAdminUsers.RevokeAdminWikiNotFound ->
            Evergreen.V2.WikiAdminUsers.RevokeAdminWikiNotFound

        Evergreen.V1.WikiAdminUsers.RevokeAdminWikiInactive ->
            Evergreen.V2.WikiAdminUsers.RevokeAdminWikiInactive

        Evergreen.V1.WikiAdminUsers.RevokeAdminTargetNotFound ->
            Evergreen.V2.WikiAdminUsers.RevokeAdminTargetNotFound

        Evergreen.V1.WikiAdminUsers.RevokeAdminTargetNotAdmin ->
            Evergreen.V2.WikiAdminUsers.RevokeAdminTargetNotAdmin

        Evergreen.V1.WikiAdminUsers.RevokeAdminCannotRevokeSelf ->
            Evergreen.V2.WikiAdminUsers.RevokeAdminCannotRevokeSelf


migrate_WikiAuditLog_AuditEvent : Evergreen.V1.WikiAuditLog.AuditEvent -> Evergreen.V2.WikiAuditLog.AuditEvent
migrate_WikiAuditLog_AuditEvent old =
    { at = old.at
    , actorUsername = old.actorUsername
    , kind = old.kind |> migrate_WikiAuditLog_AuditEventKind
    }


migrate_WikiAuditLog_AuditEventKind : Evergreen.V1.WikiAuditLog.AuditEventKind -> Evergreen.V2.WikiAuditLog.AuditEventKind
migrate_WikiAuditLog_AuditEventKind old =
    case old of
        Evergreen.V1.WikiAuditLog.ApprovedSubmission p0 ->
            Evergreen.V2.WikiAuditLog.ApprovedSubmission p0

        Evergreen.V1.WikiAuditLog.RejectedSubmission p0 ->
            Evergreen.V2.WikiAuditLog.RejectedSubmission p0

        Evergreen.V1.WikiAuditLog.RequestedSubmissionChanges p0 ->
            Evergreen.V2.WikiAuditLog.RequestedSubmissionChanges p0

        Evergreen.V1.WikiAuditLog.PromotedContributorToTrusted p0 ->
            Evergreen.V2.WikiAuditLog.PromotedContributorToTrusted p0

        Evergreen.V1.WikiAuditLog.DemotedTrustedToContributor p0 ->
            Evergreen.V2.WikiAuditLog.DemotedTrustedToContributor p0

        Evergreen.V1.WikiAuditLog.GrantedWikiAdmin p0 ->
            Evergreen.V2.WikiAuditLog.GrantedWikiAdmin p0

        Evergreen.V1.WikiAuditLog.RevokedWikiAdmin p0 ->
            Evergreen.V2.WikiAuditLog.RevokedWikiAdmin p0

        Evergreen.V1.WikiAuditLog.TrustedPublishedNewPage p0 ->
            Evergreen.V2.WikiAuditLog.TrustedPublishedNewPage p0

        Evergreen.V1.WikiAuditLog.TrustedPublishedPageEdit p0 ->
            Evergreen.V2.WikiAuditLog.TrustedPublishedPageEdit p0

        Evergreen.V1.WikiAuditLog.TrustedPublishedPageDelete p0 ->
            Evergreen.V2.WikiAuditLog.TrustedPublishedPageDelete p0


migrate_WikiAuditLog_AuditEventKindFilterTag : Evergreen.V1.WikiAuditLog.AuditEventKindFilterTag -> Evergreen.V2.WikiAuditLog.AuditEventKindFilterTag
migrate_WikiAuditLog_AuditEventKindFilterTag old =
    case old of
        Evergreen.V1.WikiAuditLog.ApprovedSubmissionKind ->
            Evergreen.V2.WikiAuditLog.ApprovedSubmissionKind

        Evergreen.V1.WikiAuditLog.RejectedSubmissionKind ->
            Evergreen.V2.WikiAuditLog.RejectedSubmissionKind

        Evergreen.V1.WikiAuditLog.RequestedSubmissionChangesKind ->
            Evergreen.V2.WikiAuditLog.RequestedSubmissionChangesKind

        Evergreen.V1.WikiAuditLog.PromotedContributorToTrustedKind ->
            Evergreen.V2.WikiAuditLog.PromotedContributorToTrustedKind

        Evergreen.V1.WikiAuditLog.DemotedTrustedToContributorKind ->
            Evergreen.V2.WikiAuditLog.DemotedTrustedToContributorKind

        Evergreen.V1.WikiAuditLog.GrantedWikiAdminKind ->
            Evergreen.V2.WikiAuditLog.GrantedWikiAdminKind

        Evergreen.V1.WikiAuditLog.RevokedWikiAdminKind ->
            Evergreen.V2.WikiAuditLog.RevokedWikiAdminKind

        Evergreen.V1.WikiAuditLog.TrustedPublishedNewPageKind ->
            Evergreen.V2.WikiAuditLog.TrustedPublishedNewPageKind

        Evergreen.V1.WikiAuditLog.TrustedPublishedPageEditKind ->
            Evergreen.V2.WikiAuditLog.TrustedPublishedPageEditKind

        Evergreen.V1.WikiAuditLog.TrustedPublishedPageDeleteKind ->
            Evergreen.V2.WikiAuditLog.TrustedPublishedPageDeleteKind


migrate_WikiAuditLog_AuditLogFilter : Evergreen.V1.WikiAuditLog.AuditLogFilter -> Evergreen.V2.WikiAuditLog.AuditLogFilter
migrate_WikiAuditLog_AuditLogFilter old =
    { actorUsernameSubstring = old.actorUsernameSubstring
    , pageSlugSubstring = old.pageSlugSubstring
    , eventKindTags = old.eventKindTags |> List.map migrate_WikiAuditLog_AuditEventKindFilterTag
    }


migrate_WikiAuditLog_Error : Evergreen.V1.WikiAuditLog.Error -> Evergreen.V2.WikiAuditLog.Error
migrate_WikiAuditLog_Error old =
    case old of
        Evergreen.V1.WikiAuditLog.WikiNotFound ->
            Evergreen.V2.WikiAuditLog.WikiNotFound

        Evergreen.V1.WikiAuditLog.WikiInactive ->
            Evergreen.V2.WikiAuditLog.WikiInactive

        Evergreen.V1.WikiAuditLog.NotLoggedIn ->
            Evergreen.V2.WikiAuditLog.NotLoggedIn

        Evergreen.V1.WikiAuditLog.WrongWikiSession ->
            Evergreen.V2.WikiAuditLog.WrongWikiSession

        Evergreen.V1.WikiAuditLog.Forbidden ->
            Evergreen.V2.WikiAuditLog.Forbidden


migrate_WikiAuditLog_HostAuditLogFilter : Evergreen.V1.WikiAuditLog.HostAuditLogFilter -> Evergreen.V2.WikiAuditLog.HostAuditLogFilter
migrate_WikiAuditLog_HostAuditLogFilter old =
    { wikiSlugSubstring = old.wikiSlugSubstring
    , actorUsernameSubstring = old.actorUsernameSubstring
    , pageSlugSubstring = old.pageSlugSubstring
    , eventKindTags = old.eventKindTags |> List.map migrate_WikiAuditLog_AuditEventKindFilterTag
    }


migrate_WikiAuditLog_ScopedAuditEvent : Evergreen.V1.WikiAuditLog.ScopedAuditEvent -> Evergreen.V2.WikiAuditLog.ScopedAuditEvent
migrate_WikiAuditLog_ScopedAuditEvent old =
    { wikiSlug = old.wikiSlug
    , at = old.at
    , actorUsername = old.actorUsername
    , kind = old.kind |> migrate_WikiAuditLog_AuditEventKind
    }


migrate_WikiRole_SubmissionsScope : Evergreen.V1.WikiRole.SubmissionsScope -> Evergreen.V2.WikiRole.SubmissionsScope
migrate_WikiRole_SubmissionsScope old =
    case old of
        Evergreen.V1.WikiRole.SubmissionsScope ->
            Evergreen.V2.WikiRole.SubmissionsScope


migrate_WikiRole_UntrustedContributorCaps : Evergreen.V1.WikiRole.UntrustedContributorCaps -> Evergreen.V2.WikiRole.UntrustedContributorCaps
migrate_WikiRole_UntrustedContributorCaps old =
    { submissions = old.submissions |> migrate_WikiRole_SubmissionsScope
    }


migrate_WikiRole_WikiRole : Evergreen.V1.WikiRole.WikiRole -> Evergreen.V2.WikiRole.WikiRole
migrate_WikiRole_WikiRole old =
    case old of
        Evergreen.V1.WikiRole.UntrustedContributor p0 ->
            Evergreen.V2.WikiRole.UntrustedContributor (p0 |> migrate_WikiRole_UntrustedContributorCaps)

        Evergreen.V1.WikiRole.TrustedContributor ->
            Evergreen.V2.WikiRole.TrustedContributor

        Evergreen.V1.WikiRole.Admin ->
            Evergreen.V2.WikiRole.Admin


migrate_Wiki_CatalogEntry : Evergreen.V1.Wiki.CatalogEntry -> Evergreen.V2.Wiki.CatalogEntry
migrate_Wiki_CatalogEntry old =
    old
